const soundtracksData = [
  [
    {
      id: 1,
      nameEn: 'Titanic',
      nameRu: 'Титаник',
      trackEn: 'My Heart Will Go On',
      trackRu: 'Моё сердце будет биться',
      authorEn: 'Céline Dion',
      authorRu: 'Селин Дион',
      descriptionEn: '"My Heart Will Go On" is a 1997 song recorded by Canadian singer Celine Dion.<br><br>The song serves as the main soundtrack to James Cameron\'s blockbuster film Titanic, based on an account of the transatlantic ocean liner of the same name which sank in 1912 after colliding with an iceberg in the North Atlantic Ocean.<br><br>The song\'s music was composed by James Horner, its lyrics were written by Will Jennings, while the production was handled by Walter Afanasieff, Horner and Simon Franglen.',
      descriptionRu: '"Моё сердце будет биться дальше" — песня канадской певицы Селин Дион, главная тема к фильму Джеймса Кэмерона "Титаник".<br><br>Автор музыки — Джеймс Хорнер, слова написал Уилл Дженнингс, продюсером стал Уолтер Афанасьефф. Композиция была выпущена на альбоме Дион Let\'s Talk About Love в 1997 году, она возглавила чарты по всему миру, включая США, Великобританию и Австралию.<br><br>Релиз сингла состоялся в Австралии и Германии 8 декабря 1997 года и в январе и феврале 1998 года в остальном мире, композиция стала одной из самых популярных за всю историю музыки и самой продаваемой в мире песней 1998 года.емыми в более чем 18 миллионов копий, это второй самый продаваемый сингл на физическом носителе в истории музыки и один из самых продаваемых синглов всех времен.<br><br>Он также был самым продаваемым синглом в мире за 1998 год. Песня также была включена в список "Песни века" Американской ассоциацией звукозаписывающей индустрии и Национальным фондом искусств.<br><br>Дион исполнила песню в честь 20-летия фильма "Титаник" на церемонии вручения премии Billboard Music Awards 21 мая 2017 года.',
      image: 'url(../../assets/img/titanic.webp',
      audio: '../../assets/sound/titanic.mp3',
      duration: '00:17',
      wikiEn: 'https://en.wikipedia.org/wiki/My_Heart_Will_Go_On',
      wikiRu: 'https://ru.wikipedia.org/wiki/My_Heart_Will_Go_On',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 2,
      nameEn: 'Star Wars',
      nameRu: 'Звёздные войны',
      trackEn: 'The Imperial March',
      trackRu: 'Имперский марш',
      authorEn: 'John Williams',
      authorRu: 'Джон Уильямс',
      descriptionEn: '"The Imperial March (Darth Vader\'s Theme)" is a musical theme present in the Star Wars franchise. It was composed by John Williams for the film The Empire Strikes Back.<br><br>Together with "Yoda\'s Theme", "The Imperial March" was premiered on April 29, 1980, three weeks before the opening of the film, on the occasion of John Williams first concert as official conductor-in-residence of the Boston Pops Orchestra.<br><br>One of the best known symphonic movie themes, it is used as a leitmotif throughout the Star Wars franchise.',
      descriptionRu: '«Имперский марш (Тема Дарта Вейдера)» — музыкальная тема, представленная во франшизе «Звёздные войны». Она была написана Джоном Уильямсом для фильма «Звёздные войны. Эпизод V: Империя наносит ответный удар».<br><br>Вместе с «темой Йоды» премьера «Имперского марша» состоялась 29 апреля 1980 года, за три недели до открытия фильма, по случаю первого концерта Джона Уильямса в качестве официального дирижёра Boston Pops Orchestra.<br><br>Одна из самых известных тем симфонического кино, это пример лейтмотива, повторяющейся темы, связанной с персонажами или событиями в драме.',
      image: 'url(../../assets/img/star-wars.webp',
      audio: '../../assets/sound/star-wars.mp3',
      duration: '00:21',
      wikiEn: 'https://en.wikipedia.org/wiki/The_Imperial_March',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%98%D0%BC%D0%BF%D0%B5%D1%80%D1%81%D0%BA%D0%B8%D0%B9_%D0%BC%D0%B0%D1%80%D1%88',
      youtube: 'https://youtu.be/vsMWVW4xtwI'
    },
    {
      id: 3,
      nameEn: 'The Godfather',
      nameRu: 'Крёстный отец',
      trackEn: 'Speak Softly Love',
      trackRu: 'Говори тихо, любовь моя',
      authorEn: 'Nino Rota',
      authorRu: 'Нино Рота',
      descriptionEn: '"Love Theme from The Godfather" is an instrumental theme from the 1972 film The Godfather, composed by Nino Rota.<br><br>The piece was lyricized in English by Larry Kusik into "Speak Softly, Love", a popular song released in 1972.<br><br>The highest-charting rendition of either version was by vocalist Andy Williams, who took "Speak Softly Love" to number 34 on Billboard magazine\'s Hot 100 and number seven on its Easy Listening chart.',
      descriptionRu: '«Говори тихо, любовь моя» — песня композитора Нино Рота на слова Ларри Кьюзика, впервые прозвучавшая в инструментальном исполнении в фильме «Крёстный отец» (1972).<br><br>Наибольшей популярности песня достигла в исполнении Энди Уильямса, поднявшись до 43-й позиции в Billboard Hot 100 и седьмого места в хит-параде Easy Listening.<br><br>Позднее эту песню исполняли также Эл Мартино, София Ротару («Скажи, що любиш», 1975), Бобби Винтон, Муслим Магомаев, Олег Погудин и другие певцы.',
      image: 'url(../../assets/img/godfather.webp',
      audio: '../../assets/sound/godfather.mp3',
      duration: '00:15',
      wikiEn: 'https://en.wikipedia.org/wiki/Love_Theme_from_The_Godfather',
      wikiRu: 'https://ru.wikipedia.org/wiki/Speak_Softly_Love',
      youtube: 'https://youtu.be/zbSMCyJkUmI'
    },
    {
      id: 4,
      nameEn: 'Pulp Fiction',
      nameRu: 'Криминальное чтиво',
      trackEn: 'You Never Can Tell',
      trackRu: 'Никак не угадать',
      authorEn: 'Chuck Berry',
      authorRu: 'Чак Берри',
      descriptionEn: '"You Never Can Tell", also known as "C\'est La Vie" or "Teenage Wedding", is a song written by Chuck Berry.<br><br>It was composed in the early 1960s while Berry was in federal prison for violating the Mann Act. Released in 1964 on the album St. Louis to Liverpool and the follow-up single to Berry\'s final Top Ten hit of the 1960s: "No Particular Place to Go", "You Never Can Tell" reached number 14, becoming Berry\'s final Top 40 hit until "My Ding-a-Ling", a number 1 in October 1972.<br><br>The song became popular again after the 1994 release of the film Pulp Fiction, directed and co-written by Quentin Tarantino. The music was played for a "Twist contest" in which Vincent Vega (John Travolta) and Mia Wallace (Uma Thurman) competed (and were the only contestants shown in the film). The music added an evocative element of sound to the narrative and Tarantino said that the song\'s lyrics of "Pierre" and "Mademoiselle" gave the scene a "uniquely \'50s French New Wave dance sequence feel".',
      descriptionRu: '«You Never Can Tell» — песня американского рок-музыканта Чака Берри, вышедшая на сингле в 1964 году.<br><br>Песня была написана в начале шестидесятых, в то время, когда Чак Берри находился в тюрьме. You Never Can Tell вошла в альбом Берри St. Louis to Liverpool 1964 года, изданный на лейбле Chess Records, как сингл она дошла до 14 места в рейтинге журнала Billboard.<br><br>Вторая волна популярности You Never Can Tell началась после выхода на экраны фильма культового американского режиссёра Квентина Тарантино «Криминальное чтиво» (1994), в саундтрек которого вошла песня. В одном из эпизодов фильма гангстер Винсент Вега (Джон Траволта) и жена его босса Миа Уоллес (Ума Турман) танцуют твист под песню Чака Берри. По словам Тарантино, лирика песни придаёт этой сцене особую атмосферу Французской новой волны.',
      image: 'url(../../assets/img/pulp-fiction.webp',
      audio: '../../assets/sound/pulp-fiction.mp3',
      duration: '00:26',
      wikiEn: 'https://en.wikipedia.org/wiki/You_Never_Can_Tell_(song)',
      wikiRu: 'https://ru.wikipedia.org/wiki/You_Never_Can_Tell',
      youtube: 'https://youtu.be/WSLMN6g_Od4'
    },{
      id: 5,
      nameEn: 'The Bodyguard',
      nameRu: 'Телохранитель',
      trackEn: 'I Will Always Love You',
      trackRu: 'Я всегда буду любить тебя',
      authorEn: 'Whitney Houston',
      authorRu: 'Уитни Хьюстон',
      descriptionEn: '"I Will Always Love You" is a song written and originally recorded in 1973 by American singer-songwriter Dolly Parton.<br><br>Whitney Houston recorded a soul-ballad arrangement of the song for the 1992 film The Bodyguard. Houston\'s version peaked at number one on the Billboard Hot 100 for a then-record-breaking 14 weeks. The single was certified Diamond by the RIAA, making Houston\'s first Diamond single, the third female artist who had both a Diamond single and a Diamond album, and becoming the best-selling single by a woman in the U.S.<br><br>The song was a global success, topping the charts in almost all countries. With 20 million copies sold it became the best-selling single of all time by a female solo artist.<br><br>Houston won the Grammy Award for Record of the Year in 1994 for "I Will Always Love You". The song has been recorded by many other artists including Linda Ronstadt, John Doe, Amber Riley, LeAnn Rimes and Sarah Washington, whose dance version reached number 12 on the UK Singles Chart.',
      descriptionRu: '«Я всегда буду любить тебя» — сингл американской кантри-певицы Долли Партон, выпущенный в 1974 году на лейбле RCA Records.<br><br>Однако с наибольшим успехом исполнила этот хит другая певица — Уитни Хьюстон. Её соул-версия, включённая в саундтрек к фильму «Телохранитель» 1992 года, была удостоена множества наград, в том числе «Грэмми» за лучшую запись года и лучший женский поп-вокал.<br><br>Критики были впечатлены тем, как грустная любовная песня благодаря мощному вокалу и влиянию госпела превратилась в неистовое воплощение драмы покинутой женщины.',
      image: 'url(../../assets/img/bodyguard.webp',
      audio: '../../assets/sound/bodyguard.mp3',
      duration: '00:47',
      wikiEn: 'https://en.wikipedia.org/wiki/I_Will_Always_Love_You',
      wikiRu: 'https://ru.wikipedia.org/wiki/I_Will_Always_Love_You',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 6,
      nameEn: 'Requiem for a Dream',
      nameRu: 'Реквием по мечте',
      trackEn: 'Lux Aeterna',
      trackRu: 'Вечный свет',
      authorEn: 'Clint Mansell',
      authorRu: 'Клинт Мэнселл',
      descriptionEn: '"Lux Aeterna" is an orchestral composition by Clint Mansell. It forms a leitmotif in the 2000 film Requiem for a Dream, and is the penultimate piece in the movie\'s soundtrack.<br><br>The popularity of the piece led to its use in popular culture outside the film, in film and teaser trailers, such as Sunshine and Waking Madison, and multiple remixes and remakes by other producers.<br><br>It was also used in the 2010 season 2 premiere episode of NCIS: LA and a version of the track was re-orchestrated with a choir and full orchestra for The Lord of the Rings: The Two Towers trailer.<br><br>It was arranged by Simone Benyacar, Daniel Nielsen, and Veigar Margeirsson.<br><br>The orchestrated version was used in various trailers and video games. Clint Mansell commented that the piece had "gone on to have a life of its own".',
      descriptionRu: '«Вечный свет» — саундтрек к фильму Даррена Аронофски «Реквием по мечте» (экранизация романа Хьюберта Селби). Выпущен в 2000 году. Композитором является Клинт Мэнселл.<br><br>Эта музыка стала культовым хитом, так как саундтрек был оценён по достоинству многими музыкантами и получил широкое признание, а композиция «Lux Aeterna» и её реаранжированная версия «Requiem for a Tower» впоследствии были использованы в различных формах массовой информации (трейлеры и тизеры фильмов и сериалов, видеоигры, телепередачи, рекламные ролики и другие медиа).<br><br>Саундтрек Requiem for a Dream закрепил свою популярность после издания альбома Requiem for a Dream: Remixed, содержавшего новые ремиксы, созданные Полом Окенфолдом, Джошем Уинком, Джэгзом Кунером, Delerium и многими другими.',
      image: 'url(../../assets/img/requiem.webp',
      audio: '../../assets/sound/requiem.mp3',
      duration: '00:30',
      wikiEn: 'https://en.wikipedia.org/wiki/Lux_Aeterna_(Mansell)',
      wikiRu: 'https://ru.wikipedia.org/wiki/Requiem_for_a_Dream_(%D1%81%D0%B0%D1%83%D0%BD%D0%B4%D1%82%D1%80%D0%B5%D0%BA)',
      youtube: 'https://youtu.be/oc3Cq89P97Y'
    }
  ],
  [
    {
      id: 1,
      nameEn: 'Friends',
      nameRu: 'Друзья',
      trackEn: 'I\'ll Be There for You',
      trackRu: 'Я буду рядом с тобой',
      authorEn: 'The Rembrandts',
      authorRu: 'Рембрандты',
      descriptionEn: '"I\'ll Be There for You" is a song by American pop rock duo the Rembrandts. The song was written by David Crane, Marta Kauffman, Michael Skloff, and Allee Willis as the main theme song to the NBC sitcom Friends, which was broadcast from 1994 to 2004.<br><br>American rock band R.E.M. was originally asked to allow one of their songs to be used for the Friends theme, but they turned the opportunity down.<br><br>"I\'ll Be There for You" was subsequently written and Warner Bros. Television selected the only available band on Warner Bros. Records to record it: the Rembrandts. In 1995, after a Nashville radio station brought the song to mainstream popularity, Rembrandts members Danny Wilde and Phil Sōlem expanded the theme song with two new verses and included this version on their third studio album, L.P. (1995).<br><br>The extended version of the song was released to US radio on May 23, 1995, and was issued in the United Kingdom on August 7, 1995, as the first single from L.P. Following the song\'s release, it reached the top 10 in Australia, New Zealand and Norway, as well as in Ireland and the United Kingdom in both 1995 and 1997.<br><br>In Canada, the song reached number one for five weeks and was the most successful single of 1995, while in the United States, the song reached number 17 on the Billboard Hot 100 and topped the Billboard Hot 100 Airplay chart for eight weeks.',
      descriptionRu: '«Я буду рядом с тобой» — песня американского дуэта The Rembrandts, наиболее известная как музыкальная тема вступительной заставки к ситкому «Друзья».<br><br>Она также была выпущена как первый сингл с третьего студийного альбома коллектива «L.P.», достигнув топ-10 чартов Австралии, Новой Зеландии, Норвегии, Ирландии и Великобритании. Песня заняла первое место в чарте Канады, удерживая позицию в течение пяти недель, где также стала самым продаваемым синглом 1995 года.<br><br>Сингл также достиг семнадцатого места в американском хит-параде Billboard Hot 100 и на протяжении восьми недель возглавлял чарт Hot 100 Airplay.',
      image: 'url(../../assets/img/friends.webp',
      audio: '../../assets/sound/friends.mp3',
      duration: '00:18',
      wikiEn: 'https://en.wikipedia.org/wiki/I%27ll_Be_There_for_You_(The_Rembrandts_song)',
      wikiRu: 'https://ru.wikipedia.org/wiki/I%E2%80%99ll_Be_There_for_You_(%D0%BF%D0%B5%D1%81%D0%BD%D1%8F_The_Rembrandts)',
      youtube: 'https://youtu.be/RIjTq_OdFvo'
    },
    {
      id: 2,
      nameEn: 'Game of Thrones',
      nameRu: 'Игра престолов',
      trackEn: 'Game of Thrones Main Title',
      trackRu: 'Игра престолов главная тема',
      authorEn: 'Ramin Djawadi',
      authorRu: 'Рамин Джавади',
      descriptionEn: 'The music for the fantasy TV series Game of Thrones is composed by Ramin Djawadi. The music is primarily non-diegetic and instrumental with occasional vocal performances, and is created to support musically the characters and plots of the show.<br><br>It features various themes, the most prominent being the "main title theme" that accompanies the series\' title sequence. In every season, a soundtrack album was released.<br><br>The music for the show has won a number of awards, including a Primetime Emmy Award for Outstanding Music Composition for a Series in 2018 and 2019.<br><br>A series of concerts which featured Game of Thrones music, Game of Thrones Live Concert Experience with composer Ramin Djawadi, took place in 2017–2018. First to be performed in Saint Paul, Minnesota, it then went on to tour across the United States, Canada and Europe. This is followed by a world tour starting May 2018 in Madrid.',
      descriptionRu: 'Game of Thrones — саундтрек к американскому сериалу канала HBO Игра престолов. Над ним работал немецкий композитор Рамин Джавади, пластинка к первому сезону была выпущена лейблом Varèse Sarabande в июне 2011 года.<br><br>Музыка альбома инструментальная, кроме этого есть заглавная тема сериала — Main Title.<br><br>Сперва над саундтреком Игры престолов должен был работать Стивен Варбек, но 2 февраля 2011 года он покинул проект. Его заменил Рамин Джавади.<br><br>Альбом вместе с цифровым буклетом появился в iTunes 14 июня 2011 года. Релиз компакт диска состоялся 28 июня.',
      image: 'url(../../assets/img/game-of-thrones.webp',
      audio: '../../assets/sound/game-of-thrones.mp3',
      duration: '00:15',
      wikiEn: 'https://en.wikipedia.org/wiki/Music_of_Game_of_Thrones',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%98%D0%B3%D1%80%D0%B0_%D0%BF%D1%80%D0%B5%D1%81%D1%82%D0%BE%D0%BB%D0%BE%D0%B2_(%D1%81%D0%B0%D1%83%D0%BD%D0%B4%D1%82%D1%80%D0%B5%D0%BA)',
      youtube: 'https://youtu.be/TZE9gVF1QbA'
    },
    {
      id: 3,
      nameEn: 'Santa Barbara',
      nameRu: 'Санта-Барбара',
      trackEn: 'Santa-Barbara Main Title Theme',
      trackRu: 'Главная тема Санта-Барбара',
      authorEn: 'Joe Harnell',
      authorRu: 'Джо Харнелл',
      descriptionEn: 'Santa Barbara is an American television soap opera that aired on NBC from July 30, 1984, to January 15, 1993. The show revolves around the eventful lives of the wealthy Capwell family of Santa Barbara, California.<br><br>The music for "Santa Barbara" was composed by Joe Harnell (1924-2005), who by that time already had vast experience as an arranger and composer.<br><br>Other prominent families featured on the soap were the rival Lockridge family, and the more modest Andrade and Perkins families.<br><br>The serial was produced by Dobson Productions and New World Television, which also served as distributor for the show in international markets. Santa Barbara was the first series for New World Television.<br><br>Santa Barbara aired in the United States at 3:00 PM Eastern (2:00 PM Central) on NBC in the same time slot as General Hospital on ABC and Guiding Light on CBS and right after Another World. Santa Barbara aired in over 40 countries around the world. It became the longest-running television series in Russia, airing there from 1992 to 2002.',
      descriptionRu: '«Санта-Барбара» — американская дневная мыльная опера, транслировавшаяся в США с 1984 по 1993 год на телеканале NBC. Первый сериал, показанный на территории СНГ после распада СССР, один из самых популярных и самый длинный из когда-либо транслировавшихся в России.<br><br>Всего было снято 2137 серий. Действие происходит в городе Санта-Барбара (Калифорния). Сериал рассказывает о жизни богатой семьи Кэпвеллов из города Санта-Барбара.<br><br>Музыкальную заставку к «Санта-Барбаре» сочинил Джо Харнелл (1924-2005), к тому времени уже имевший огромный опыт аранжировщика и композитора.',
      image: 'url(../../assets/img/santa-barbara.webp',
      audio: '../../assets/sound/santa-barbara.mp3',
      duration: '00:34',
      wikiEn: 'https://en.wikipedia.org/wiki/Santa_Barbara_(TV_series)',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%A1%D0%B0%D0%BD%D1%82%D0%B0-%D0%91%D0%B0%D1%80%D0%B1%D0%B0%D1%80%D0%B0_(%D1%82%D0%B5%D0%BB%D0%B5%D1%81%D0%B5%D1%80%D0%B8%D0%B0%D0%BB)',
      youtube: 'https://youtu.be/HTjjNozVy5w'
    },
    {
      id: 4,
      nameEn: 'Narcos',
      nameRu: 'Нарко',
      trackEn: 'Tuyo',
      trackRu: 'Твой',
      authorEn: 'Rodrigo Amarante',
      authorRu: 'Родриго Амаранте',
      descriptionEn: 'Tuyo is a bolero written and composed by Brazilian singer-songwriter Rodrigo Amarante for Narcos\' opening theme.<br><br>Amarante wrote and vocalized the Spanish-language song, "Tuyo" ("Yours"), as the opening theme for the Netflix Original series Narcos.<br><br>He was inspired by the thought of what kind of music Pablo Escobar\'s mother would have listened to when raising her son.<br><br>The song debuted at No. 6 on the Latin Pop Digital Songs around the 2015 series premiere and was nominated for a Primetime Emmy Award for Outstanding Main Title Theme Music.',
      descriptionRu: '«Твой» — это болеро, написанное бразильским певцом и автором песен Родриго Амаранте для вступительной темы Narcos.<br><br>Амаранте написал и озвучил испаноязычную песню "Tuyo" в качестве вступительной темы для сериала Netflix Original Narcos.<br><br>Его вдохновила мысль о том, какую музыку слушала бы мать Пабло Эскобара, воспитывая сына.<br><br>Песня дебютировала на 6 месте в Latin Pop Digital Songs во время премьеры сериала 2015 года и была номинирована на премию Primetime Emmy Award за выдающуюся музыкальную тему для главной заставки сериала.',
      image: 'url(../../assets/img/narcos.webp',
      audio: '../../assets/sound/narcos.mp3',
      duration: '00:26',
      wikiEn: 'https://en.wikipedia.org/wiki/Tuyo',
      wikiRu: '',
      youtube: 'https://youtu.be/PtJ6yAGjsIs'
    },{
      id: 5,
      nameEn: 'The X-Files',
      nameRu: 'Секретные материалы',
      trackEn: 'Materia Primoris',
      trackRu: 'Первичная материя',
      authorEn: 'Mark Snow',
      authorRu: 'Марк Сноу',
      descriptionEn: '"The X-Files" is an instrumental written and produced by American film and television composer Mark Snow. On its parent album, The Truth and the Light: Music from the X-Files, the track is titled "Materia Primoris".<br><br>It is a remixed version of the original theme Snow composed for the science fiction television series The X-Files in 1993.<br><br>The composition was released as a single in 1996 and achieved chart success, particularly in France, where it reached number one on the singles chart. The composition has since been covered by many artists, including DJ Dado and Triple X; DJ Dado\'s version was a major hit in Europe while Triple X\'s version reached number two in Australia.',
      descriptionRu: 'Автором музыки к «Секретным материалам» стал композитор Марк Сноу. Он начал работу над проектом в 1993 году после того, как к нему обратился исполнительный продюсер телесериала Крис Картер.<br><br>Сноу стал одним из дюжины кандидатов, которых порекомендовали на эту позицию. Через несколько недель после первой встречи Картер сообщил Сноу, что ему доверено написание музыки к пилотной серии «Секретных материалов».<br><br>Успех сериала привёл к тому, что Сноу и Картер продолжили работу. Первый компакт-диск с музыкой к сериалу The Truth and The Light вышел через два после начала работы. Помимо музыкальных композиций он содержал фрагменты диалогов из фильма.<br><br>Основной темой сериала стала композиция «Materia Primoris». Композиция получила всемирную известность и занимала первое место в хит-парадах Франции и Англии.',
      image: 'url(../../assets/img/x-files.webp',
      audio: '../../assets/sound/x-files.mp3',
      duration: '00:19',
      wikiEn: 'https://en.wikipedia.org/wiki/The_X-Files_(composition)',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%A1%D0%B5%D0%BA%D1%80%D0%B5%D1%82%D0%BD%D1%8B%D0%B5_%D0%BC%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%B0%D0%BB%D1%8B_(%D1%81%D0%B0%D1%83%D0%BD%D0%B4%D1%82%D1%80%D0%B5%D0%BA%D0%B8)',
      youtube: 'https://youtu.be/Qz2wnSVeITg'
    },
    {
      id: 6,
      nameEn: 'Sex And The City',
      nameRu: 'Секс в большом городе',
      trackEn: 'Sex And The City Main Theme',
      trackRu: 'Секс в большом городе',
      authorEn: 'Douglas J. Cuomo',
      authorRu: 'Дуглас Дж. Куомо',
      descriptionEn: '"Sex and the City" is an American romantic comedy-drama television series created by Darren Star for HBO. An adaptation of Candace Bushnell\'s newspaper column and 1996 book anthology of the same name, the series premiered in the United States on June 6, 1998, and concluded on February 22, 2004, with 94 episodes broadcast over six seasons.<br><br>American television composer Douglas J. Cuomo composed the theme to Sex and the City (HBO), praised by The New Yorker magazine for its "unusual, edgy salsa flavor" and the saxophone quartet music that opens and closes Now with Bill Moyers (PBS).',
      descriptionRu: '«Секс в большом городе» — американский романтический комедийно-драматический телесериал, созданный Дарреном Старом для канала HBO. Адаптация газетной колонки Кэндис Бушнелл и одноименной книжной антологии 1996 года. Премьера сериала состоялась 6 июня 1998 года в США и завершилась 22 февраля 2004 года, когда в течение шести сезонов транслировались 94 эпизода.<br ><br>Американский телевизионный композитор Дуглас Дж. Куомо сочинил тему для сериала «Секс в большом городе», получившего высокую оценку журнала The New Yorker за «необычный, резкий привкус сальсы» и музыку квартета саксофонов, которая начинается и завершается сейчас с Биллом Мойерсом (PBS).',
      image: 'url(../../assets/img/sex-and-the-city.webp',
      audio: '../../assets/sound/sex-and-the-city.mp3',
      duration: '00:30',
      wikiEn: 'https://en.wikipedia.org/wiki/Sex_and_the_City_(soundtracks)',
      wikiRu: '',
      youtube: 'https://youtu.be/ntr62qu1kd0'
    }
  ],
  [
    {
      id: 1,
      nameEn: 'The Simpsons',
      nameRu: 'Симпсоны',
      trackEn: 'The Simpsons Theme',
      trackRu: 'Саундтрек Симпсоны',
      authorEn: 'Daniel Elfman',
      authorRu: 'Дэниел Эльфман',
      descriptionEn: '"The Simpsons Theme", also referred to as "The Simpsons Main Title Theme" in album releases, is the theme music of the animated television series The Simpsons.<br><br>It plays during the opening sequence and was composed by Danny Elfman in 1989, after series creator Matt Groening approached him requesting a theme.<br><br>The piece has been noted by Elfman as the most popular of his career.<br><br>The theme won the National Music Award for "Favorite TV Theme" in 2002, and has won the BMI TV Music Award in 1996, 1998, and 2003. In 1990, the theme was nominated for the Emmy for "Outstanding Achievement in Main Title Theme Music".',
      descriptionRu: 'Музыкальная тема к американскому мультсериалу «Симпсоны». Она играет в начале каждого эпизода.<br><br>Музыка была написана Дэниелем Эльфманом в 1989 году специально для «Симпсонов» после того, как Мэтт Гроунинг, создатель сериала, обратился к нему за помощью в создании стильной, в стиле ретро, музыкальной темы.<br><br>Эта тема, создание которой заняло всего три дня, стала самой популярной в карьере Эльфмана. Слегка различаясь аранжировками, тема порой играет и в конце эпизодов. Первоначально были две главные версии заключительной темы, с более длинной версией, заканчивающейся в низшем ключе. Обе версии были использованы в эпизодах 3 сезона, короткая версия была использована только для 4 сезона, затем снова использовалась более длинная тема и только в 7 сезоне была использована тема, которая звучит в эпизодах и сейчас.',
      image: 'url(../../assets/img/simpsons.webp',
      audio: '../../assets/sound/simpsons.mp3',
      duration: '00:16',
      wikiEn: 'https://en.wikipedia.org/wiki/The_Simpsons_Theme',
      wikiRu: 'https://ru.wikipedia.org/wiki/The_Simpsons_Theme',
      youtube: 'https://youtu.be/OQ4aPXNChMM'
    },
    {
      id: 2,
      nameEn: 'Chip \'n Dale',
      nameRu: 'Чип и Дейл',
      trackEn: 'Chip \'n Dale Theme Song',
      trackRu: 'Саундтрек Чип и Дейл',
      authorEn: 'Марк Мюллер',
      authorRu: 'Джон Уильямс',
      descriptionEn: 'Chip \'n Dale: Rescue Rangers is an American animated adventure comedy television series produced by Walt Disney Television Animation<br><br>The show\'s opening theme was written by Mark Mueller, an ASCAP Award-winning pop music songwriter who also wrote the popular DuckTales theme song, and produced by Alf Clausen.<br><br>The song performed over the title credits is sung by Jeff Pescetto (who also performed the DuckTales theme song).<br><br>A full-length theme song was recorded by The Jets, a Minnesota pop group, and released on The Disney Afternoon soundtrack.',
      descriptionRu: '«Чип и Дейл спешат на помощь» — американский анимационный приключенческий комедийный телесериал, созданный компанией Walt Disney Television Animation<br><br>Вступительная тема шоу была написана Марком Мюллером, автором песен в жанре поп-музыки, лауреатом премии ASCAP. который также написал популярную заглавную песню для «Утиных историй», спродюсированную Альфом Клаузеном.<br><br>Песню, исполняемую поверх титров, поет Джефф Пескетто (который также исполнил заглавную песню из «Утиных историй»).<br><br>A полнометражная музыкальная тема была записана поп-группой The Jets из Миннесоты и выпущена в качестве саундтрека к фильму «Дисней после полудня».',
      image: 'url(../../assets/img/chip-n-dale.webp',
      audio: '../../assets/sound/chip-n-dale.mp3',
      duration: '00:23',
      wikiEn: 'https://en.wikipedia.org/wiki/Chip_%27n_Dale:_Rescue_Rangers_(TV_series)',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%A7%D0%B8%D0%BF_%D0%B8_%D0%94%D0%B5%D0%B9%D0%BB_%D1%81%D0%BF%D0%B5%D1%88%D0%B0%D1%82_%D0%BD%D0%B0_%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C',
      youtube: 'https://youtu.be/vsMWVW4xtwI'
    },
    {
      id: 3,
      nameEn: 'The Lion King',
      nameRu: 'Король Лев',
      trackEn: 'Hakuna Matata',
      trackRu: 'Акуна Матата',
      authorEn: 'Elton John',
      authorRu: 'Элтон Джон',
      descriptionEn: '"Hakuna Matata" is a song from Disney\'s 32nd animated feature The Lion King. The music was written by Elton John with lyrics by Tim Rice.<br><br> The song is based on Timon and Pumbaa\'s catchphrase in the movie, Hakuna matata, a Swahili phrase meaning "No worry(s)". It is characterized by its simple 4/4 time, upbeat message and catchy lyrics.<br><br>Timon and Pumbaa, the two main comedy characters in the film, talking to Simba about moving forward from their troubled pasts and forgetting their worries, and Simba grows from cub to adult as the song progresses. The song also provides a backstory for Pumbaa, explaining that he was ostracized from animal society for his excessive flatulence.<br><br>It makes use of a large proportion of the orchestra as well as many other more unusual instruments including an elaborate drum kit.',
      descriptionRu: '"Акуна Матата" или "Хакуна Матата" в переводе с языка суахили буквально значит "никаких забот" — песня из мультфильма "Король Лев" (1994), которая была номинирована на "Оскар" в категории "Лучшая песня". Музыка — Элтона Джона, слова — Тима Райса.<br><br>Она заняла 99-ю позицию (из 100) в рейтинге лучших песен в истории кинематографа, составленном "American Film Institute".<br><br>В мультфильме песню поют Тимон, Пумба и Симба. Действие происходит после смерти Муфасы, Тимон и Пумба разговаривают с Симбой о том, что им нужно уйти от своего тревожного прошлого и забыть о своих заботах, а Симба по мере развития песни превращается из детеныша во взрослого.<br><br>В песне задействована большая часть оркестра, а также много других более необычных инструментов, включая сложную ударную установку.',
      image: 'url(../../assets/img/lion-king.webp',
      audio: '../../assets/sound/lion-king.mp3',
      duration: '00:26',
      wikiEn: 'https://en.wikipedia.org/wiki/Hakuna_Matata_(song)',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%90%D0%BA%D1%83%D0%BD%D0%B0_%D0%BC%D0%B0%D1%82%D0%B0%D1%82%D0%B0',
      youtube: 'https://youtu.be/kaOIxll4LCA'
    },
    {
      id: 4,
      nameEn: 'Frozen',
      nameRu: 'Холодное сердце',
      trackEn: 'Let It Go',
      trackRu: 'Отпусти и забудь',
      authorEn: 'Kristen Anderson-Lopez',
      authorRu: 'Кристен Андерсон-Лопес',
      descriptionEn: '"Let It Go" is a song from Disney\'s 2013 computer-animated feature film Frozen, whose music and lyrics were composed by husband-and-wife songwriting team Kristen Anderson-Lopez and Robert Lopez.<br><br>The song was performed in its original show-tune version in the film by American actress and singer Idina Menzel in her vocal role as Queen Elsa. It was later released as a single, being promoted to adult contemporary radio by Walt Disney Records in January 2014.<br><br>Anderson-Lopez and Lopez also composed a simplified pop version (with shorter lyrics and background chorus) which was performed by actress and singer Demi Lovato over the start of the film\'s closing credits. Disney\'s music division planned to release Lovato\'s version of the song before Menzel\'s, as they did not consider Menzel\'s version a traditional pop song.<br><br>A music video was released separately for Lovato\'s version.',
      descriptionRu: '«Отпусти и забудь» — песня из диснеевского анимационного фильма 2013 года «Холодное сердце». Слова и музыка были написаны мужем и женой Робертом Лопесом и Кристен Андерсон-Лопес. В мультфильме песня исполнялась Эльзой.<br><br>Также Лопес и Андерсон-Лопес написали поп-версию этой песни (с укороченным текстом), которую записала Деми Ловато и на которую был снят видеоклип. Кроме того, для релизов фильма в различных странах были записаны версии этой песни ещё на как минимум 24 языках.<br><br>Песня достигла 5 места в американском чарте Billboard Hot 100 (в исполнении Идины Мензел) и завоевала как премию «Оскар» за лучшую песню к фильму (в 2014 году), так и премию «Грэмми» за лучшую песню, написанную для кино, телевидения или другого визуального представления (в 2015 году).',
      image: 'url(../../assets/img/frozen.webp',
      audio: '../../assets/sound/frozen.mp3',
      duration: '00:26',
      wikiEn: 'https://en.wikipedia.org/wiki/Let_It_Go',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%9E%D1%82%D0%BF%D1%83%D1%81%D1%82%D0%B8_%D0%B8_%D0%B7%D0%B0%D0%B1%D1%83%D0%B4%D1%8C',
      youtube: 'https://youtu.be/moSFlvxnbgk'
    },{
      id: 5,
      nameEn: 'Masha and the Bear',
      nameRu: 'Маша и Медведь',
      trackEn: 'Masha and the Bear Theme',
      trackRu: 'Саундтрек Маша и Медведь',
      authorEn: 'Vasily Bogatyrev',
      authorRu: 'Василий Богатырёв',
      descriptionEn: '"Masha and the Bear" is a Russian animated television series created by Oleg Kuzovkov and produced by Animaccord Animation Studio, loosely based on the oral children\'s folk story of the same name. The show focuses on the adventures of a little girl named Masha and her caring friend, the bear (mishka) that always keeps her safe from disasters.<br><br>The soundtrack for each episode is written by Russian composer Vasily Bogatyrev. Many compositions are stylized for famous works: Moonlight Sonata, Beethoven\'s Symphony No. 5, a circus theme from the movie Soviet Circus, and in the episode “One-Hit Wonder” the rockstar Masha performs a song in the style of the group AC/DC. Most of the songs used in the cartoon, such as the soundtracks of “Laundry Day” and “The Grand Piano Lesson” episodes, became popular in Russia and abroad.',
      descriptionRu: '«Маша и Медведь» — российский мультсериал, созданный Олегом Кузовковым и выпущенный анимационной студией «Анимаккорд» по мотивам одноименной устной детской народной сказки. Шоу посвящено приключениям маленькой девочки по имени Маша и ее заботливого друга медведя, который всегда оберегает ее от бедствий.<br><br>Саундтрек к каждой серии написан композитором Василием Богатырёвым. Многие композиции стилизованы под известные произведения: «Лунная соната», «Симфония № 5» Бетховена, цирковая тема из фильма «Советский цирк», а в эпизоде «One-Hit Wonder» рок-звезда Маша исполняет песню в стиле группы AC/DC. Большинство песен, использованных в мультфильме, например, саундтреки к эпизодам «День стирки» и «Урок игры на фортепиано», стали популярными в России и за рубежом.',
      image: 'url(../../assets/img/masha-and-bear.webp',
      audio: '../../assets/sound/masha-and-bear.mp3',
      duration: '00:21',
      wikiEn: 'https://en.wikipedia.org/wiki/Masha_and_the_Bear',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%88%D0%B0_%D0%B8_%D0%9C%D0%B5%D0%B4%D0%B2%D0%B5%D0%B4%D1%8C',
      youtube: 'https://youtu.be/nhZkOGbxqZc'
    },
    {
      id: 6,
      nameEn: 'Winnie The Pooh',
      nameRu: 'Винни-Пух',
      trackEn: 'Winnie the Pooh Main Theme',
      trackRu: 'Саундтрек Винни Пух',
      authorEn: 'Steve Nelson',
      authorRu: 'Стив Нельсон',
      descriptionEn: 'The theme song that opens each episode of The New Adventures of Winnie the Pooh<br><br>The show\'s theme song, entitled "Pooh Bear", was written by Steve Nelson and sung by Steve Wood. A version with Nelson doing the vocals later appeared on his Listen What the Katmandu album. Another version of the song with Jim Cummings doing the vocals (who also voiced Pooh and Tigger) appeared in reruns of the series on Disney Channel in 1994.<br><br>Nelson also composed several additional songs that were shown on the early episodes. The music was particularly praised by critics. An orchestra was used to record the music, using instruments such as trumpets, woodwinds, and a full string section. The composers were given the unique opportunity to examine the animator\'s exposure sheets, enabling them to write music while an episode was being scripted.',
      descriptionRu: 'Музыкальная тема, открывающая каждую серию «Новых приключений Винни-Пуха». Песня была написана Стивом Нельсоном и исполнена Стивом Вудом.<br><br>Версия с вокалом Нельсона позже появилась на его альбоме Listen What the Katmandu. Другая версия песни с вокалом Джима Каммингса (который также озвучивал Пуха и Тигра) появилась в повторах сериала на канале Disney в 1994 году.<br><br>Нельсон также сочинил несколько дополнительных песен, которые были показаны в первых эпизодах.<br><br>Музыка была особенно высоко оценена критиками. Для записи использовался оркестр с использованием таких инструментов, как трубы, деревянные духовые инструменты и полная струнная секция. Композиторам была предоставлена уникальная возможность изучить экспозиционные листы аниматора, что позволило им писать музыку во время написания сценария эпизода.',
      image: 'url(../../assets/img/winnie-the-pooh.webp',
      audio: '../../assets/sound/winnie-the-pooh.mp3',
      duration: '00:14',
      wikiEn: 'https://en.wikipedia.org/wiki/Lux_Aeterna_(Mansell)',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%9D%D0%BE%D0%B2%D1%8B%D0%B5_%D0%BF%D1%80%D0%B8%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F_%D0%92%D0%B8%D0%BD%D0%BD%D0%B8-%D0%9F%D1%83%D1%85%D0%B0',
      youtube: 'https://youtu.be/oc3Cq89P97Y'
    }
  ],
  [
    {
      id: 1,
      nameEn: 'Millionaire',
      nameRu: 'О, счастливчик!',
      trackEn: 'Who Wants to Be a Millionaire',
      trackRu: 'Кто хочет стать миллионером',
      authorEn: 'Matthew Strachan',
      authorRu: 'Мэтью Стрэкан',
      descriptionEn: 'Matthew Strachan was an English composer and singer-songwriter. His best known work is the music for British television game show Who Wants to Be a Millionaire? (often informally called Millionaire) written with his father Keith, which would become a global franchise, and the BBC Radio 4 World War I drama series Home Front.<br><br>He also wrote music to film and television productions such as Extract, The Detectives, Question Time, Winning Lines, jingles for several television commercials, and scores for stage musicals.',
      descriptionRu: 'Мэттью Стрэкан — английский композитор и певец-поэт-песенник. Его самая известная работа — музыка для телевизионного игрового шоу «Кто хочет стать миллионером?» (также известная, как «О, счастливчик!»), которую он написал вместе со своим отцом Китом.<br><br>Он также создал музыку к фильмам и телевизионным постановкам, таким как Extract, The Detectives, Question Time, Winning Lines, а также джинглы для нескольких рекламных роликов и сценических мюзиклов.',
      image: 'url(../../assets/img/millionaire.webp',
      audio: '../../assets/sound/millionaire.mp3',
      duration: '00:19',
      wikiEn: '',
      wikiRu: '',
      youtube: ''
    },
    {
      id: 2,
      nameEn: 'Fort Boyard',
      nameRu: 'Форт Боярд',
      trackEn: 'Fort Boyard Intro',
      trackRu: 'Саундтрек Форт Боярд',
      authorEn: 'Paul Koulak',
      authorRu: 'Поль Кулак',
      descriptionEn: 'Fort Boyard is a French game show created by Jacques Antoine that was first broadcast on July 1990 (originally as Les Clés de Fort Boyard, however shortened to Fort Boyard from the second series in 1991). Foreign versions of the show, with varying success, have aired around the world since 1990.<br><br>Paul Koulak was a French composer of Armenian origin. He studied music at the École Normale de Musique de Paris and the Conservatoire de Paris. He has composed many pieces of music for television: broadcasts of game shows and in particular the most famous, those of the credits of Fort Boyard (a program for which he composed nearly 200 pieces) in its first version from 1990 and credits for cartoons.',
      descriptionRu: '«Форт Боярд» — приключенческое телешоу, действие которого разворачивается в Бискайском заливе у берегов Приморской Шаранты в форте Бойяр. Первый выпуск вышел в эфир французского телеканала Antenne 2 в июле 1990 года.<br><br>Поль Кулак — французский композитор армянского происхождения, автор более 200 музыкальных композиций для телеигры «Форт Боярд».<br><br>Наибольшую известность получил как автор музыки для телевизионных программ и мультфильмов.',
      image: 'url(../../assets/img/fort-boyard.webp',
      audio: '../../assets/sound/fort-boyard.mp3',
      duration: '00:13',
      wikiEn: '',
      wikiRu: '',
      youtube: ''
    },
    {
      id: 3,
      nameEn: 'In The Animal World',
      nameRu: 'В мире животных',
      trackEn: 'Alouette',
      trackRu: 'Жаворонок',
      authorEn: 'Paul Mauriat',
      authorRu: 'Поль Мария',
      descriptionEn: 'The program "In the Animal World" first appeared on the screen in 1968. The first releases were held without screensavers and titles: they simply showed frames from documentaries about wildlife on the air.<br><br>In 1974, the program had a new screensaver - cranes were circling in the frame and ostriches were jumping and an orchestral work by Paul Mauriat. This screen saver opened the program for 46 years, and the music became one of the most recognizable melodies in the USSR and the CIS.<br><br>Paul Mauriat is a French composer, arranger, creator and leader of a variety symphony orchestra.',
      descriptionRu: 'Передача «В мире животных» впервые вышла на экран в 1968 году. Первые выпуски проходили без заставок и названия: в эфире просто показывали кадры из документальных фильмов о дикой природе.<br><br>В 1974 году у программы появилась новая заставка - в кадре кружились журавли и прыгали страусы и звучало оркестровое произведение Поля Мориа — «Жаворонок». Этой заставкой передача открывалась 46 лет, а музыка стала одной из самых узнаваемых мелодий в СССР и СНГ.<br><br>Поль Мориа — французский композитор, аранжировщик, создатель и руководитель эстрадно-симфонического оркестра.',
      image: 'url(../../assets/img/animal-world.webp',
      audio: '../../assets/sound/animal-world.mp3',
      duration: '00:11',
      wikiEn: '',
      wikiRu: '',
      youtube: 'https://youtu.be/_P1O0pcVM04'
    },
    {
      id: 4,
      nameEn: 'KVN',
      nameRu: 'КВН',
      trackEn: 'Anthem of KVN',
      trackRu: 'Мы начинаем КВН',
      authorEn: 'Vladimir Shainsky',
      authorRu: 'Владимир Шаинский',
      descriptionEn: 'KVN (an abbreviation of Клуб весёлых и находчивых, Klub Vesyólykh i Nakhódchivykh or Ka-Ve-En, "Club of the Funny and Inventive") is a Russian humour TV show and an international competition where teams compete by giving funny answers to questions and showing prepared sketches.<br><br>The famous Russian composer Vladimir Shainsky became the author of the music for the song “We start KVN”, which was first performed in November 1986 at the game of the Club of the cheerful and resourceful and became the anthem of KVN.',
      descriptionRu: 'КВН («Клуб весёлых и нахо́дчивых») — телевизионные юмористические игры, в которых команды различных коллективов соревнуются в юмористических ответах на заданные вопросы, импровизациях на заданные темы, разыгрывании заранее заготовленных сцен и тому подобного.<br><br>Известный российский композитор Владимир Шаинский стал автором музыки песни «Мы начинаем КВН», которая впервые прозвучала в ноябре 1986 года на игре Клуба веселых и находчивых и стала гимном КВН.',
      image: 'url(../../assets/img/kvn.webp',
      audio: '../../assets/sound/kvn.mp3',
      duration: '00:30',
      wikiEn: '',
      wikiRu: '',
      youtube: ''
    },{
      id: 5,
      nameEn: 'Comedy Club',
      nameRu: 'Камеди Клаб',
      trackEn: 'Comedy Club Main Theme',
      trackRu: 'Заставка Comedy Club',
      authorEn: 'Yuri Prialkin',
      authorRu: 'Юрий Прялкин',
      descriptionEn: 'Comedy Club is a Russian comedy television show that has been airing on TNT since April 23, 2005.<br><br>Yuri Pryalkin is a Russian pianist, violinist, composer and producer who has worked in film and television. The author of musical accompaniment to many films and television films, cartoons (one of the landmark works is Dunno on the Moon) and the TV show Comedy Club.',
      descriptionRu: 'Comedy Club — российское юмористическое телевизионное шоу, выходящее на телеканале ТНТ с 23 апреля 2005 года.<br><br>Юрий Прялкин — российский пианист, скрипач, композитор и продюсер работал в кино и на телевидении. Автор музыкального сопровождения ко многим кино- и телефильмам, мультфильмам (одна из знаковых работ — «Незнайка на Луне») и телепередаче «Comedy Club».',
      image: 'url(../../assets/img/comedy-club.webp',
      audio: '../../assets/sound/comedy-club.mp3',
      duration: '00:19',
      wikiEn: '',
      wikiRu: '',
      youtube: ''
    },
    {
      id: 6,
      nameEn: 'The Voice',
      nameRu: 'Голос',
      trackEn: 'The Voice Main Theme',
      trackRu: 'Заставка шоу Голос',
      authorEn: 'Martijn Schimmer',
      authorRu: 'Мартин Шиммер',
      descriptionEn: 'The Voice is an American singing reality competition television series broadcast on NBC. It premiered during the spring television cycle on April 26, 2011. Based on the original The Voice of Holland and part of The Voice franchise, it has aired twenty-one seasons and aims to find unsigned singing talent (solo or duets, professional and amateur) contested by aspiring singers, age 13 or over, drawn from public auditions.<br><br>Martijn Schimmer is a Dutch composer and producer of television theme songs and film scores. He also composed the theme music for international versions of Celebrity Splash!, Adam Looking For Eve and The Winner Is. But his biggest international success came with his theme music for The Voice, The Voice Kids and The Voice Senior. The hit show is seen in more than 150 countries and all versions, including the American, use Schimmer\'s theme music.',
      descriptionRu: '«Голос» — формат телевизионных вокальных конкурсов. Первым телешоу в данном формате был The Voice of Holland («Голос Голландии»), придуманный голландским продюсером Джоном де Молем и запущенный в 2010 году на нидерландском телевидении. Позже шоу по такому же формату появились по лицензии во многих странах мира, таких как США, Украина, Германия, Великобритания, Китай, Россия, Франция, Канада, Бельгия, Турция, Австралия, Португалия, Бразилия, Таиланд, Польша, Испания, Румыния, Южная Африка и других.<br><br>Мартин Шиммер - голландский композитор и продюсер телевизионных тематических песен и музыки к фильмам. Его самый большой международный успех пришел с его музыкальной темой для The Voice, The Voice Kids и The Voice Senior. Шоу можно увидеть более чем в 150 странах, и во всех версиях, включая американскую, используется музыкальная тема Шиммера.',
      image: 'url(../../assets/img/voice.webp',
      audio: '../../assets/sound/voice.mp3',
      duration: '00:22',
      wikiEn: '',
      wikiRu: '',
      youtube: ''
    }
  ],
  [
    {
      id: 1,
      nameEn: 'Moulin Rouge',
      nameRu: 'Мулен Руж',
      trackEn: 'Lady Marmalade',
      trackRu: 'Леди Мармелад',
      authorEn: 'Bob Crewe, Kenny Nolan',
      authorRu: 'Боб Кру и Кенни Нолан',
      descriptionEn: '"Lady Marmalade" is a song written by Bob Crewe and Kenny Nolan, originally for Nolan\'s disco group. The song is famous for the repeated refrain of "Voulez-vous coucher avec moi?" in French as part of the chorus, a sexually suggestive line that translates into English as: "Do you want to sleep with me?"<br><br>The 2001 version by singers Christina Aguilera, Mýa, Pink and rapper Lil\' Kim, recorded for the Moulin Rouge! soundtrack, was a number-one hit on the Billboard Hot 100 for five weeks, and also a number-one hit in the UK. "Lady Marmalade" was the ninth song to reach number one by two different musical acts in America.',
      descriptionRu: '«Леди Мармелад» — песня 1974 года, впервые записанная известной девичьей группой Labelle. «Lady Marmalade» написана Бобом Кру (соавтором многих хитов The Four Seasons) и Кенни Нолан.<br><br>Версия песни 2001 года певиц Кристины Агилеры, Лил Ким, Майя и Пинк, записанная в качестве одного из саундтреков к фильму Moulin Rouge.<br><br>Данная версия была хитом номер один в Billboard Hot 100 в США 5 недель: с 27 мая по 30 июня 2001 года. Версия Moulin Rouge! песни «Lady Marmalade» была также хитом номер один в Австралии, представив песню новому поколению американских музыкальных слушателей.<br><br>Агилера, Лил Ким, Майя и Пинк получили за песню престижную музыкальную премию Грэмми в номинации «Лучшее совместное вокальное поп-исполнение».',
      image: 'url(../../assets/img/moulin-rouge.webp',
      audio: '../../assets/sound/moulin-rouge.mp3',
      duration: '00:08',
      wikiEn: '',
      wikiRu: '',
      youtube: ''
    },
    {
      id: 2,
      nameEn: 'Notre-Dame de Paris',
      nameRu: 'Нотр-Дам де Пари',
      trackEn: 'Belle',
      trackRu: 'Красавица',
      authorEn: 'Luc Plamondon',
      authorRu: 'Люк Пламондон',
      descriptionEn: 'Notre-Dame de Paris is a sung-through French musical which debuted on 16 September 1998 in Paris. It is based upon the novel Notre-Dame de Paris (known in English as The Hunchback of Notre-Dame) by the French novelist Victor Hugo. The music was composed by Riccardo Cocciante (also known as Richard Cocciante) and the lyrics are by Luc Plamondon.<br><br>Since its debut, it has been professionally played in Belgium, Canada, China, France, Italy, Japan, Lebanon, Luxembourg, Poland, Russia, Singapore, South Korea, Spain, Switzerland, Taiwan, Turkey, United Kingdom and United States, and has been translated into eight languages (English, Spanish, Italian, Russian, Korean, Flemish, Polish, and Kazakh). A shorter version in English was performed in 2000 in Las Vegas, Nevada (United States) and a full-length London production, also in English, ran for seventeen months.<br><br>Notre-Dame de Paris, according to the Guinness Book of Records, had the most successful first year of any musical ever. The score has been recorded at least seven times to date (2007): the original French concept album, which featured Israeli singer Achinoam Nini (aka Noa) as Esmeralda was followed by a live, complete recording of the original Paris cast.<br><br>The original London cast album featured several of the original Paris stars, but only preserved a fraction of the score in English.',
      descriptionRu: 'Нотр-Дам де Пари (Notre-Dame de Paris — «Собор Парижской Богоматери») — французско-канадский мюзикл по роману Виктора Гюго «Собор Парижской Богоматери». Композитор — Риккардо Коччанте, автор либретто — Люк Пламондон. Мюзикл дебютировал в Париже 16 сентября 1998 года и попал в Книгу Рекордов Гиннесса как имеющий самый большой успех в первый год работы.<br><br>В оригинальной версии мюзикл гастролировал по Бельгии, Франции, Канаде и Швейцарии. Во французском театре «Могадор» в 2000 году дебютировал тот же мюзикл, но с некоторыми изменениями. Этих изменений придерживались итальянская, русская, испанская и некоторые другие версии мюзикла.<br><br>В том же году стартовала укороченная американская версия мюзикла в Лас-Вегасе и английская версия в Лондоне. В мае 2001 г. мюзикл презентовали на Бродвее, премьера в Москве - 26 февраля 2002 года.',
      image: 'url(../../assets/img/notre-dame-de-paris.webp',
      audio: '../../assets/sound/notre-dame-de-paris.mp3',
      duration: '00:24',
      wikiEn: '',
      wikiRu: '',
      youtube: ''
    },
    {
      id: 3,
      nameEn: 'Mamma Mia',
      nameRu: 'Мамма мия',
      trackEn: 'Mamma Mia',
      trackRu: 'Мамма мия',
      authorEn: 'ABBA',
      authorRu: 'АББА',
      descriptionEn: 'Mamma Mia! (promoted as Benny Andersson & Björn Ulvaeus\' Mamma Mia!) is a jukebox musical written by British playwright Catherine Johnson, based on songs recorded by Swedish group ABBA and composed by Benny Andersson and Björn Ulvaeus, members of the band.<br><br>The title of the musical is taken from the group\'s 1975 chart-topper "Mamma Mia". Ulvaeus and Andersson, who composed the original music for ABBA, were involved in the development of the show from the beginning.<br><br>Singer Anni-Frid Lyngstad was involved financially in the production and she was also present at many of the premieres around the world.<br><br>The musical includes such hits as "Super Trouper", "Lay All Your Love on Me", "Dancing Queen", "Knowing Me, Knowing You", "Take a Chance on Me", "Thank You for the Music", "Money, Money, Money", "The Winner Takes It All", "Voulez-Vous", "SOS" and "Mamma Mia".<br><br>Over 65 million people have seen the show, which has grossed $4 billion worldwide since its 1999 debut.<br><br>A film adaptation starring Meryl Streep, Colin Firth, Pierce Brosnan, Amanda Seyfried, Christine Baranski, Stellan Skarsgård and Julie Walters was released in 2008.',
      descriptionRu: 'Mamma Mia! (Мамма Мия!) — мюзикл с либретто на основе 22 песен группы ABBA. Мировая премьера состоялась в 1999 году в Лондоне.<br><br>Существуют девять постановок шоу (Гамбург, Лас-Вегас, Лондон, Мадрид, Нью-Йорк, Осака, Стокгольм, Штутгарт, Будапешт). Российская премьера мюзикла состоялась 14 октября 2006 года на сцене Московского Дворца Молодежи (МДМ). Шёл в режиме 8 раз в неделю два сезона. За 20 месяцев было сыграно более 700 спектаклей, которые посетили более 600 000 зрителей.<br><br>Мюзикл стал самым успешным за всю историю российского шоу-бизнеса, поставив рекорд по сборам и по популярности.',
      image: 'url(../../assets/img/mamma-mia.webp',
      audio: '../../assets/sound/mamma-mia.mp3',
      duration: '00:15',
      wikiEn: '',
      wikiRu: '',
      youtube: ''
    },
    {
      id: 4,
      nameEn: 'Chicago',
      nameRu: 'Чикаго',
      trackEn: 'All That Jazz',
      trackRu: 'Весь этот джаз',
      authorEn: 'John Kander',
      authorRu: 'Джон Кандер',
      descriptionEn: 'Chicago is a 1975 American musical with music by John Kander, lyrics by Fred Ebb, and book by Ebb and Bob Fosse. Set in Chicago in the jazz age, the musical is based on a 1926 play of the same title by reporter Maurine Dallas Watkins, about actual criminals and the crimes on which she reported.<br><br>The story is a satire on corruption in the administration of criminal justice and the concept of the "celebrity criminal".<br><br>The original Broadway production opened in 1975 at the 46th Street Theatre and ran for 936 performances, until 1977.<br><br>Chicago was revived on Broadway in 1996, and a year later in the West End. The 1996 Broadway production holds the record as the longest-running musical revival and the longest-running American musical in Broadway history. It is the second longest-running show ever to run on Broadway, behind only The Phantom of the Opera.<br><br>The 2002 film adaptation of the musical won the Academy Award for Best Picture.',
      descriptionRu: '«Чикаго» — мюзикл Джона Кандера на либретто Фреда Эбба и Боба Фосса. Мюзикл написан по мотивам одноимённой театральной пьесы 1926 года журналистки Морин Даллас Уоткинс.<br><br>Оригинальная бродвейская постановка 1975 года была номинирована на несколько премий «Тони», в том числе и за лучший мюзикл, но не получила ни одной. В 1996 году работа была возрождена на Бродвее с обновлённой хореографией, и в этот раз была отмечена «Тони» за лучший возобновлённый мюзикл, лучшую режиссуру, лучшую хореографию и ещё несколькими.<br><br>По мюзиклу был снят фильм «Чикаго». Картина вышла на экраны в 2002 году и была отмечена шестью премиями «Оскар», в том числе как «Лучший фильм».',
      image: 'url(../../assets/img/chicago.webp',
      audio: '../../assets/sound/chicago.mp3',
      duration: '00:30',
      wikiEn: '',
      wikiRu: '',
      youtube: ''
    },{
      id: 5,
      nameEn: 'Cats',
      nameRu: 'Кошки',
      trackEn: 'Memory',
      trackRu: 'Память',
      authorEn: 'Andrew Lloyd Webber',
      authorRu: 'Эндрю Ллойд Уэббер',
      descriptionEn: 'Cats is a sung-through musical composed by Andrew Lloyd Webber, based upon the 1939 poetry collection Old Possum\'s Book of Practical Cats.<br><br>It tells the story of a tribe of cats called the Jellicles and the night they make the "Jellicle choice" by deciding which cat will ascend to the Heaviside layer and come back to a new life.<br><br>Cats opened to positive reviews at the New London Theatre in the West End in 1981 and then to mixed reviews at the Winter Garden Theatre on Broadway in 1982.<br><br>The London production ran for 21 years and 8,949 performances, while the Broadway production ran for 18 years and 7,485 performances, making Cats the longest-running musical in both theatre districts for a number of years (surpassing A Chorus Line which ran for 6,137 performances).<br><br>Cats has since been revived in the West End twice and on Broadway once. It has also been translated into multiple languages and performed around the world many times.',
      descriptionRu: '«Кошки» — мюзикл английского композитора Эндрю Ллойда Уэббера по мотивам сборника детских стихов «Популярная наука о кошках, написанная старым опоссумом».<br><br>Премьера мюзикла состоялась 11 мая 1981 года на сцене Нового лондонского театра, а 7 октября 1982 года — состоялась премьера на Бродвее.<br><br>Мюзикл был самым продолжительным бродвейским шоу, которое шло с 1997 по 2006 год, пока его не опередил «Призрак Оперы». На 2018 год это четвёртое по продолжительности бродвейское шоу.<br><br>Мюзикл переведён на 15 языков и поставлен более, чем в 30 странах. Его посмотрело более 73 миллионов человек по всему миру.<br><br>Премьера российской версии «Кошек» состоялась 18 марта 2005 года, мюзикл с успехом шёл целый год и был закрыт 31 марта 2006 года.',
      image: 'url(../../assets/img/cats.webp',
      audio: '../../assets/sound/cats.mp3',
      duration: '00:37',
      wikiEn: '',
      wikiRu: '',
      youtube: ''
    },
    {
      id: 6,
      nameEn: 'Cabaret',
      nameRu: 'Кабаре',
      trackEn: 'Money, Money, Money',
      trackRu: 'Деньги, Деньги, Деньги',
      authorEn: 'John Kander',
      authorRu: 'Джон Кандер',
      descriptionEn: 'Cabaret is a 1966 musical with music by John Kander, lyrics by Fred Ebb, and book by Joe Masteroff. The musical was based on John Van Druten\'s 1951 play I Am a Camera which was adapted from Goodbye to Berlin (1939), a semi-autobiographical novel by Anglo-American writer Christopher Isherwood which drew upon his experiences in the poverty-stricken Weimar Republic and his intimate friendship with nineteen-year-old cabaret singer Jean Ross.<br><br>Set in 1929–1930 Berlin during the twilight of the Jazz Age as the Nazis are ascending to power, the musical focuses on the hedonistic nightlife at the seedy Kit Kat Klub and revolves around American writer Clifford Bradshaw\'s relations with English cabaret performer Sally Bowles.<br><br>A subplot involves the doomed romance between German boarding house owner Fräulein Schneider and her elderly suitor Herr Schultz, a Jewish fruit vendor.',
      descriptionRu: '«Кабаре» — мюзикл Джона Кандера на стихи Фреда Эбба, либретто Джо Мастероффа. Сюжет основан на пьесе Джона Ван Друтена «Я — камера»(1951), которая, в свою очередь, является сценической адаптацией романа «Прощай, Берлин» Кристофера Ишервуда.<br><br>Бродвейская премьера — 20 ноября 1966 года, Бродхерст-театр.<br><br>На основе музыкального спектакля снят фильм, записанный в разряд кинематографических шедевров, режиссёр и хореограф фильма — Боб Фосс.',
      image: 'url(../../assets/img/cabaret.webp',
      audio: '../../assets/sound/cabaret.mp3',
      duration: '00:18',
      wikiEn: '',
      wikiRu: '',
      youtube: ''
    }
  ],
  [
    {
      id: 1,
      nameEn: 'Super Mario Bros.',
      nameRu: 'Супер Марио',
      trackEn: 'Super Mario Bros. Soundtrack',
      trackRu: 'Саундтрек Супер Марио',
      authorEn: 'Koji Kondo',
      authorRu: 'Кодзи Кондо',
      descriptionEn: 'The Super Mario Bros. Theme, officially known as the "Ground Theme" or "Overworld Theme", is a musical theme originally heard in the first stage of the 1985 Nintendo Entertainment System video game Super Mario Bros.<br><br>It was one of six themes composed for the game by Nintendo sound designer Koji Kondo, who found it to be the most difficult track to compose for it.<br><br>The theme is set in the key of C major and features a swung rhythm with prominent use of syncopation.<br><br>In later installments with more powerful sound hardware, it is often scored as a calypso song led by steel drums.<br><br>After Super Mario Bros., it went on to become the theme of the series, and has been a fixture in most of its titles. It has been reused and remixed in other Nintendo-published games, including Tetris DS, Nintendogs: Chihuahua and Friends, WarioWare, Inc.: Mega Microgames!, and every entry in the Super Smash Bros. series.',
      descriptionRu: 'Super Mario Bros. Theme, официально известная также как «Ground Theme», является основной музыкальной темой видеоигры «Super Mario Bros.», выпущенной в 1985 году компанией Nintendo.<br><br>Это одна из шести тем, сочинённая японским композитором Кодзи Кондо для игр о Марио. Тема написана в ритмах джазового калипсо в тональности до мажор.<br><br>После включения в игру тема стала неотъемлемой частью серии и неоднократно использовалась в более поздних играх о знаменитом водопроводчике.<br><br>Ремиксы темы использовались также и в других играх, например, в «Tetris DS» и «Nintendogs».',
      image: 'url(../../assets/img/super-mario.webp',
      audio: '../../assets/sound/super-mario.mp3',
      duration: '00:07',
      wikiEn: '',
      wikiRu: '',
      youtube: ''
    },
    {
      id: 2,
      nameEn: 'Far Cry 3',
      nameRu: 'Фар Край 3',
      trackEn: 'Paper Planes',
      trackRu: 'Бумажные самолетики',
      authorEn: 'M.I.A.',
      authorRu: 'M.И.A.',
      descriptionEn: '"Paper Planes" is a song written and recorded by British hip hop artist M.I.A. for her second studio album, Kala (2007). The video game Far Cry 3 (2012) begins with "Paper Planes" used in the opening cinematic sequence.<br><br>"Paper Planes" was a sleeper hit and M.I.A.\'s breakthrough commercial success. The song debuted at number 89 on the Canadian Hot 100 chart dated 1 March 2008. The single entered the UK Singles Chart at number 69 on 7 September 2008.<br><br>The unexpected success of "Paper Planes" paralleled M.I.A.\'s condemnations of the Sri Lankan government\'s war crimes against the Tamils.',
      descriptionRu: '«Paper Planes» — песня британской певицы M.I.A. (Эм-ай-эй) с её второго студийного альбома Kala (2007). Была использована в компьютерной игре Far Cry 3 от Ubisoft, а также в фильме Миллионер из трущоб.<br><br>Песня достигла 4 места в США (в «Горячей сотне» журнала «Билборд») и 19 места в Великобритании (в национальном чарте синглов).<br><br>В 2011 году журнал Rolling Stone поместил песню «Paper Planes» в исполнении M.I.A. на 236 место своего списка «500 величайших песен всех времён».',
      image: 'url(../../assets/img/far-cry.webp',
      audio: '../../assets/sound/far-cry.mp3',
      duration: '00:19',
      wikiEn: '',
      wikiRu: '',
      youtube: ''
    },
    {
      id: 3,
      nameEn: 'Mortal Kombat',
      nameRu: 'Мортал комбат',
      trackEn: 'Techno Syndrome',
      trackRu: 'Техноcиндром',
      authorEn: 'The Immortals',
      authorRu: 'Имморталс',
      descriptionEn: 'Techno Syndrome is a soundtrack by The Immortals (Maurice "Praga Khan" Engelen and Olivier Adams), released in 1994 to accompany the home versions of the video game Mortal Kombat. Television commercials for the home versions included a brief plug for the album at the end.<br><br>"Techno Syndrome" is also a hidden song featured in the Sega CD version of Mortal Kombat when one chooses to enter the "soundtrack" mode at the Sega CD intro screen. It can also be accessed by putting the CD in a CD player and selecting track 17. The album peaked at #16 on the Billboard Heatseekers in the United States.',
      descriptionRu: 'Техноcиндром — саундтрек группы The Immortals (Морис «Прага Хан» Энгелен и Оливье Адамс), выпущенный в 1994 году для сопровождения домашних версий видеоигры Mortal Kombat.<br><br> Энгелен и Адамс были приглашены компанией Midway Games для создания трека, им была предоставлена ​​копия игры, подробная информация о различных персонажах и библиотека звуковых эффектов для семплирования.<br><br>В альбом также вошли песни в стиле техно для каждого из 7 игровых персонажей, а также босса Горо, а также два дополнительных трека. «Techno Syndrome» был единственной сольной работой с характерным криком «Смертельная битва!» впоследствии стал известен как «главная песня Mortal Kombat» из-за её использования в фильме 1995 года, а ремикс-версии песни продолжают ассоциироваться с франшизой Мортал Комбат.<br><br>Саундтрек достиг 10 места в чартах Billboard 200.',
      image: 'url(../../assets/img/mortal-combat.webp',
      audio: '../../assets/sound/mortal-combat.mp3',
      duration: '00:32',
      wikiEn: '',
      wikiRu: '',
      youtube: ''
    },
    {
      id: 4,
      nameEn: 'Tetris',
      nameRu: 'Тетрис',
      trackEn: 'Korobeiniki',
      trackRu: 'Коробейники',
      authorEn: 'Russian folk song',
      authorRu: 'Русская народная песня',
      descriptionEn: '"Korobeiniki" (Russian: Коробейники, tr. Korobéyniki) is a nineteenth-century Russian folk song that tells the story of a meeting between a peddler and a girl, describing their haggling over goods in a metaphor courtship.<br><br>Outside Russia, "Korobeiniki" is widely known as the Tetris theme tune (titled "A-Type" in the game), from its appearance in Nintendo\'s Game Boy version of the game as arranged by the Japanese composer Hirokazu Tanaka in 1989.<br><br>The song "Korobeiniki" is based on a poem of the same name Nikolay Nekrasov, which was first printed in the Sovremennik magazine in 1861. Its increasing tempo and the associated dance style led to it quickly becoming a popular Russian folk song.',
      descriptionRu: '«Коробушка» (также известна под названиями «Коробейники», «Ой, полным полна коробушка…», «Катеринушка и коробейник», «Катеринушка») — известная русская песня.<br><br>Текст песни представляет собой фрагмент поэмы Николая Некрасова.<br><br>«Коробушка» использовалась в качестве фоновой мелодии, а также как фоновая мелодия на титульном экране компьютерной игры «Тетрис» на Game Boy, NES, Brick Game, некоторых PC-версий.<br><br>Игра стала самой популярной на консоли «Game Boy», благодаря чему мелодия широко известна как «Tetris theme»',
      image: 'url(../../assets/img/tetris.webp',
      audio: '../../assets/sound/tetris.mp3',
      duration: '00:29',
      wikiEn: '',
      wikiRu: '',
      youtube: ''
    },{
      id: 5,
      nameEn: 'GTA San Andreas',
      nameRu: 'ГТА Сан Андреас',
      trackEn: 'GTA San Andreas Theme Song',
      trackRu: 'Саундтрек ГТА Сан Андреас',
      authorEn: 'Michael Hunter',
      authorRu: 'Майкл Хантер',
      descriptionEn: 'Michael Hunter is a Scottish composer and musician from Glasgow, Scotland, who composed the theme songs for both Grand Theft Auto: San Andreas and Grand Theft Auto IV.<br><br>He has also released music under the aliases of Pablo and Butch Cassidy Sound System. On 22 August 2011, he released his debut album, State of Flux. The second album, Circuit Brain, was released on 29 August 2018.',
      descriptionRu: 'Майкл Хантер - композитор, создавший удивительные саундтреки к играм Grand Theft Auto. Родился он в Глазго, Шотландия.<br><br>Его лучшие работы это темы для игр GTA: San Andreas и Grand Theft Auto IV. Кроме этого он создал саундтреки и к другим играм.',
      image: 'url(../../assets/img/gta.webp',
      audio: '../../assets/sound/gta.mp3',
      duration: '00:47',
      wikiEn: '',
      wikiRu: '',
      youtube: ''
    },
    {
      id: 6,
      nameEn: 'Angry Birds',
      nameRu: 'Злые птички',
      trackEn: 'Angry Birds Main Theme',
      trackRu: 'Саундтрек Злые птички',
      authorEn: 'Ari Pulkkinen',
      authorRu: 'Ари Пулккинен',
      descriptionEn: 'Ari Pulkkinen (born 15 January 1982) is a Finnish video game composer, musician and sound designer.<br><br>His Angry Birds theme is perhaps his most famous work.<br><br>Pulkkinen was born in Helsinki. At the age of 6 he started studying piano and composed his first song at the age of 12. He was interested in the computer music demoscene and started making music with tracker software under the name "ArtZ".<br><br>He won many music competitions and made his first big public album to accompany a freeware game named "Starfight VI: Gatekeepers" in 1999. Ari has never studied music composition academically.',
      descriptionRu: 'Ари Пулккинен (фин. Ari Pulkkinen; род. 1982, Хельсинки) — финский композитор и музыкант, автор музыки для игр Angry Birds и Trine.<br><br>Он начал играть на пианино в 6 лет, а в 12 сочинил свою первую песню.<br><br>Свою музыку он написал с помощью трекера. В 1999 году вышел его первый альбом в дополнение к бесплатной игре Starfight VI: Gatekeepers.<br><br>В 2003 году Ари стал удалённо сотрудничать с Frozenbyte. За годы работы в компании он написал музыку к таким играм, как Shadowgrounds и Trine.<br><br>После ухода из Frozenbyte, Ари основал собственную звукозаписывающую компанию — AriTunes. В течение последних лет он создал музыку к более чем 20 играм, в том числе Angry Birds, Dead Nation, Outland и Super Stardust HD.',
      image: 'url(../../assets/img/angry-birds.webp',
      audio: '../../assets/sound/angry-birds.mp3',
      duration: '00:20',
      wikiEn: '',
      wikiRu: '',
      youtube: ''
    }
  ]
];

export default soundtracksData;