const soundtracksData = [
  [
    {
      id: 1,
      nameEn: 'Titanic',
      nameRu: 'Титаник',
      trackEn: 'My Heart Will Go On',
      trackRu: 'Моё сердце будет биться',
      authorEn: 'Céline Dion',
      authorRu: 'Селин Дион',
      descriptionEn: '"My Heart Will Go On" is a 1997 song recorded by Canadian singer Celine Dion.<br><br>The song serves as the main soundtrack to James Cameron\'s blockbuster film Titanic, based on an account of the transatlantic ocean liner of the same name which sank in 1912 after colliding with an iceberg in the North Atlantic Ocean.<br><br>The song\'s music was composed by James Horner, its lyrics were written by Will Jennings, while the production was handled by Walter Afanasieff, Horner and Simon Franglen.',
      descriptionRu: '"Моё сердце будет биться дальше" — песня канадской певицы Селин Дион, главная тема к фильму Джеймса Кэмерона "Титаник".<br><br>Автор музыки — Джеймс Хорнер, слова написал Уилл Дженнингс, продюсером стал Уолтер Афанасьефф. Композиция была выпущена на альбоме Дион Let\'s Talk About Love в 1997 году, она возглавила чарты по всему миру, включая США, Великобританию и Австралию.<br><br>Релиз сингла состоялся в Австралии и Германии 8 декабря 1997 года и в январе и феврале 1998 года в остальном мире, композиция стала одной из самых популярных за всю историю музыки и самой продаваемой в мире песней 1998 года.емыми в более чем 18 миллионов копий, это второй самый продаваемый сингл на физическом носителе в истории музыки и один из самых продаваемых синглов всех времен.<br><br>Он также был самым продаваемым синглом в мире за 1998 год. Песня также была включена в список "Песни века" Американской ассоциацией звукозаписывающей индустрии и Национальным фондом искусств.<br><br>Дион исполнила песню в честь 20-летия фильма "Титаник" на церемонии вручения премии Billboard Music Awards 21 мая 2017 года.',
      image: 'url(../../assets/img/titanic.webp',
      audio: '../../assets/sound/titanic.mp3',
      duration: '00:17',
      wikiEn: 'https://en.wikipedia.org/wiki/My_Heart_Will_Go_On',
      wikiRu: 'https://ru.wikipedia.org/wiki/My_Heart_Will_Go_On',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 2,
      nameEn: 'Star Wars',
      nameRu: 'Звёздные войны',
      trackEn: 'The Imperial March',
      trackRu: 'Имперский марш',
      authorEn: 'John Williams',
      authorRu: 'Джон Уильямс',
      descriptionEn: '"The Imperial March (Darth Vader\'s Theme)" is a musical theme present in the Star Wars franchise. It was composed by John Williams for the film The Empire Strikes Back.<br><br>Together with "Yoda\'s Theme", "The Imperial March" was premiered on April 29, 1980, three weeks before the opening of the film, on the occasion of John Williams first concert as official conductor-in-residence of the Boston Pops Orchestra.<br><br>One of the best known symphonic movie themes, it is used as a leitmotif throughout the Star Wars franchise.',
      descriptionRu: '«Имперский марш (Тема Дарта Вейдера)» — музыкальная тема, представленная во франшизе «Звёздные войны». Она была написана Джоном Уильямсом для фильма «Звёздные войны. Эпизод V: Империя наносит ответный удар».<br><br>Вместе с «темой Йоды» премьера «Имперского марша» состоялась 29 апреля 1980 года, за три недели до открытия фильма, по случаю первого концерта Джона Уильямса в качестве официального дирижёра Boston Pops Orchestra.<br><br>Одна из самых известных тем симфонического кино, это пример лейтмотива, повторяющейся темы, связанной с персонажами или событиями в драме.',
      image: 'url(../../assets/img/star-wars.webp',
      audio: '../../assets/sound/star-wars.mp3',
      duration: '00:21',
      wikiEn: 'https://en.wikipedia.org/wiki/The_Imperial_March',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%98%D0%BC%D0%BF%D0%B5%D1%80%D1%81%D0%BA%D0%B8%D0%B9_%D0%BC%D0%B0%D1%80%D1%88',
      youtube: 'https://youtu.be/vsMWVW4xtwI'
    },
    {
      id: 3,
      nameEn: 'The Godfather',
      nameRu: 'Крёстный отец',
      trackEn: 'Speak Softly Love',
      trackRu: 'Говори тихо, любовь моя',
      authorEn: 'Nino Rota',
      authorRu: 'Нино Рота',
      descriptionEn: '"Love Theme from The Godfather" is an instrumental theme from the 1972 film The Godfather, composed by Nino Rota.<br><br>The piece was lyricized in English by Larry Kusik into "Speak Softly, Love", a popular song released in 1972.<br><br>The highest-charting rendition of either version was by vocalist Andy Williams, who took "Speak Softly Love" to number 34 on Billboard magazine\'s Hot 100 and number seven on its Easy Listening chart.',
      descriptionRu: '«Говори тихо, любовь моя» — песня композитора Нино Рота на слова Ларри Кьюзика, впервые прозвучавшая в инструментальном исполнении в фильме «Крёстный отец» (1972).<br><br>Наибольшей популярности песня достигла в исполнении Энди Уильямса, поднявшись до 43-й позиции в Billboard Hot 100 и седьмого места в хит-параде Easy Listening.<br><br>Позднее эту песню исполняли также Эл Мартино, София Ротару («Скажи, що любиш», 1975), Бобби Винтон, Муслим Магомаев, Олег Погудин и другие певцы.',
      image: 'url(../../assets/img/godfather.webp',
      audio: '../../assets/sound/godfather.mp3',
      duration: '00:15',
      wikiEn: 'https://en.wikipedia.org/wiki/Love_Theme_from_The_Godfather',
      wikiRu: 'https://ru.wikipedia.org/wiki/Speak_Softly_Love',
      youtube: 'https://youtu.be/zbSMCyJkUmI'
    },
    {
      id: 4,
      nameEn: 'Pulp Fiction',
      nameRu: 'Криминальное чтиво',
      trackEn: 'You Never Can Tell',
      trackRu: 'Никак не угадать',
      authorEn: 'Chuck Berry',
      authorRu: 'Чак Берри',
      descriptionEn: '"You Never Can Tell", also known as "C\'est La Vie" or "Teenage Wedding", is a song written by Chuck Berry.<br><br>It was composed in the early 1960s while Berry was in federal prison for violating the Mann Act. Released in 1964 on the album St. Louis to Liverpool and the follow-up single to Berry\'s final Top Ten hit of the 1960s: "No Particular Place to Go", "You Never Can Tell" reached number 14, becoming Berry\'s final Top 40 hit until "My Ding-a-Ling", a number 1 in October 1972.<br><br>The song became popular again after the 1994 release of the film Pulp Fiction, directed and co-written by Quentin Tarantino. The music was played for a "Twist contest" in which Vincent Vega (John Travolta) and Mia Wallace (Uma Thurman) competed (and were the only contestants shown in the film). The music added an evocative element of sound to the narrative and Tarantino said that the song\'s lyrics of "Pierre" and "Mademoiselle" gave the scene a "uniquely \'50s French New Wave dance sequence feel".',
      descriptionRu: '«You Never Can Tell» — песня американского рок-музыканта Чака Берри, вышедшая на сингле в 1964 году.<br><br>Песня была написана в начале шестидесятых, в то время, когда Чак Берри находился в тюрьме. You Never Can Tell вошла в альбом Берри St. Louis to Liverpool 1964 года, изданный на лейбле Chess Records, как сингл она дошла до 14 места в рейтинге журнала Billboard.<br><br>Вторая волна популярности You Never Can Tell началась после выхода на экраны фильма культового американского режиссёра Квентина Тарантино «Криминальное чтиво» (1994), в саундтрек которого вошла песня. В одном из эпизодов фильма гангстер Винсент Вега (Джон Траволта) и жена его босса Миа Уоллес (Ума Турман) танцуют твист под песню Чака Берри. По словам Тарантино, лирика песни придаёт этой сцене особую атмосферу Французской новой волны.',
      image: 'url(../../assets/img/pulp-fiction.webp',
      audio: '../../assets/sound/pulp-fiction.mp3',
      duration: '00:26',
      wikiEn: 'https://en.wikipedia.org/wiki/You_Never_Can_Tell_(song)',
      wikiRu: 'https://ru.wikipedia.org/wiki/You_Never_Can_Tell',
      youtube: 'https://youtu.be/WSLMN6g_Od4'
    },{
      id: 5,
      nameEn: 'The Bodyguard',
      nameRu: 'Телохранитель',
      trackEn: 'I Will Always Love You',
      trackRu: 'Я всегда буду любить тебя',
      authorEn: 'Whitney Houston',
      authorRu: 'Уитни Хьюстон',
      descriptionEn: '"I Will Always Love You" is a song written and originally recorded in 1973 by American singer-songwriter Dolly Parton.<br><br>Whitney Houston recorded a soul-ballad arrangement of the song for the 1992 film The Bodyguard. Houston\'s version peaked at number one on the Billboard Hot 100 for a then-record-breaking 14 weeks. The single was certified Diamond by the RIAA, making Houston\'s first Diamond single, the third female artist who had both a Diamond single and a Diamond album, and becoming the best-selling single by a woman in the U.S.<br><br>The song was a global success, topping the charts in almost all countries. With 20 million copies sold it became the best-selling single of all time by a female solo artist.<br><br>Houston won the Grammy Award for Record of the Year in 1994 for "I Will Always Love You". The song has been recorded by many other artists including Linda Ronstadt, John Doe, Amber Riley, LeAnn Rimes and Sarah Washington, whose dance version reached number 12 on the UK Singles Chart.',
      descriptionRu: '«Я всегда буду любить тебя» — сингл американской кантри-певицы Долли Партон, выпущенный в 1974 году на лейбле RCA Records.<br><br>Однако с наибольшим успехом исполнила этот хит другая певица — Уитни Хьюстон. Её соул-версия, включённая в саундтрек к фильму «Телохранитель» 1992 года, была удостоена множества наград, в том числе «Грэмми» за лучшую запись года и лучший женский поп-вокал.<br><br>Критики были впечатлены тем, как грустная любовная песня благодаря мощному вокалу и влиянию госпела превратилась в неистовое воплощение драмы покинутой женщины.',
      image: 'url(../../assets/img/bodyguard.webp',
      audio: '../../assets/sound/bodyguard.mp3',
      duration: '00:47',
      wikiEn: 'https://en.wikipedia.org/wiki/I_Will_Always_Love_You',
      wikiRu: 'https://ru.wikipedia.org/wiki/I_Will_Always_Love_You',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 6,
      nameEn: 'Requiem for a Dream',
      nameRu: 'Реквием по мечте',
      trackEn: 'Lux Aeterna',
      trackRu: 'Вечный свет',
      authorEn: 'Clint Mansell',
      authorRu: 'Клинт Мэнселл',
      descriptionEn: '"Lux Aeterna" is an orchestral composition by Clint Mansell. It forms a leitmotif in the 2000 film Requiem for a Dream, and is the penultimate piece in the movie\'s soundtrack.<br><br>The popularity of the piece led to its use in popular culture outside the film, in film and teaser trailers, such as Sunshine and Waking Madison, and multiple remixes and remakes by other producers.<br><br>It was also used in the 2010 season 2 premiere episode of NCIS: LA and a version of the track was re-orchestrated with a choir and full orchestra for The Lord of the Rings: The Two Towers trailer.<br><br>It was arranged by Simone Benyacar, Daniel Nielsen, and Veigar Margeirsson.<br><br>The orchestrated version was used in various trailers and video games. Clint Mansell commented that the piece had "gone on to have a life of its own".',
      descriptionRu: '«Вечный свет» — саундтрек к фильму Даррена Аронофски «Реквием по мечте» (экранизация романа Хьюберта Селби). Выпущен в 2000 году. Композитором является Клинт Мэнселл.<br><br>Эта музыка стала культовым хитом, так как саундтрек был оценён по достоинству многими музыкантами и получил широкое признание, а композиция «Lux Aeterna» и её реаранжированная версия «Requiem for a Tower» впоследствии были использованы в различных формах массовой информации (трейлеры и тизеры фильмов и сериалов, видеоигры, телепередачи, рекламные ролики и другие медиа).<br><br>Саундтрек Requiem for a Dream закрепил свою популярность после издания альбома Requiem for a Dream: Remixed, содержавшего новые ремиксы, созданные Полом Окенфолдом, Джошем Уинком, Джэгзом Кунером, Delerium и многими другими.',
      image: 'url(../../assets/img/requiem.webp',
      audio: '../../assets/sound/requiem.mp3',
      duration: '00:30',
      wikiEn: 'https://en.wikipedia.org/wiki/Lux_Aeterna_(Mansell)',
      wikiRu: 'https://ru.wikipedia.org/wiki/Requiem_for_a_Dream_(%D1%81%D0%B0%D1%83%D0%BD%D0%B4%D1%82%D1%80%D0%B5%D0%BA)',
      youtube: 'https://youtu.be/oc3Cq89P97Y'
    }
  ],
  [
    {
      id: 1,
      nameEn: 'Friends',
      nameRu: 'Друзья',
      trackEn: 'I\'ll Be There for You',
      trackRu: 'Я буду рядом с тобой',
      authorEn: 'The Rembrandts',
      authorRu: 'Рембрандты',
      descriptionEn: '"I\'ll Be There for You" is a song by American pop rock duo the Rembrandts. The song was written by David Crane, Marta Kauffman, Michael Skloff, and Allee Willis as the main theme song to the NBC sitcom Friends, which was broadcast from 1994 to 2004.<br><br>American rock band R.E.M. was originally asked to allow one of their songs to be used for the Friends theme, but they turned the opportunity down.<br><br>"I\'ll Be There for You" was subsequently written and Warner Bros. Television selected the only available band on Warner Bros. Records to record it: the Rembrandts. In 1995, after a Nashville radio station brought the song to mainstream popularity, Rembrandts members Danny Wilde and Phil Sōlem expanded the theme song with two new verses and included this version on their third studio album, L.P. (1995).<br><br>The extended version of the song was released to US radio on May 23, 1995, and was issued in the United Kingdom on August 7, 1995, as the first single from L.P. Following the song\'s release, it reached the top 10 in Australia, New Zealand and Norway, as well as in Ireland and the United Kingdom in both 1995 and 1997.<br><br>In Canada, the song reached number one for five weeks and was the most successful single of 1995, while in the United States, the song reached number 17 on the Billboard Hot 100 and topped the Billboard Hot 100 Airplay chart for eight weeks.',
      descriptionRu: '«Я буду рядом с тобой» — песня американского дуэта The Rembrandts, наиболее известная как музыкальная тема вступительной заставки к ситкому «Друзья».<br><br>Она также была выпущена как первый сингл с третьего студийного альбома коллектива «L.P.», достигнув топ-10 чартов Австралии, Новой Зеландии, Норвегии, Ирландии и Великобритании. Песня заняла первое место в чарте Канады, удерживая позицию в течение пяти недель, где также стала самым продаваемым синглом 1995 года.<br><br>Сингл также достиг семнадцатого места в американском хит-параде Billboard Hot 100 и на протяжении восьми недель возглавлял чарт Hot 100 Airplay.',
      image: 'url(../../assets/img/friends.webp',
      audio: '../../assets/sound/friends.mp3',
      duration: '00:18',
      wikiEn: 'https://en.wikipedia.org/wiki/I%27ll_Be_There_for_You_(The_Rembrandts_song)',
      wikiRu: 'https://ru.wikipedia.org/wiki/I%E2%80%99ll_Be_There_for_You_(%D0%BF%D0%B5%D1%81%D0%BD%D1%8F_The_Rembrandts)',
      youtube: 'https://youtu.be/RIjTq_OdFvo'
    },
    {
      id: 2,
      nameEn: 'Game of Thrones',
      nameRu: 'Игра престолов',
      trackEn: 'Game of Thrones Main Title',
      trackRu: 'Игра престолов главная тема',
      authorEn: 'Ramin Djawadi',
      authorRu: 'Рамин Джавади',
      descriptionEn: 'The music for the fantasy TV series Game of Thrones is composed by Ramin Djawadi. The music is primarily non-diegetic and instrumental with occasional vocal performances, and is created to support musically the characters and plots of the show.<br><br>It features various themes, the most prominent being the "main title theme" that accompanies the series\' title sequence. In every season, a soundtrack album was released.<br><br>The music for the show has won a number of awards, including a Primetime Emmy Award for Outstanding Music Composition for a Series in 2018 and 2019.<br><br>A series of concerts which featured Game of Thrones music, Game of Thrones Live Concert Experience with composer Ramin Djawadi, took place in 2017–2018. First to be performed in Saint Paul, Minnesota, it then went on to tour across the United States, Canada and Europe. This is followed by a world tour starting May 2018 in Madrid.',
      descriptionRu: 'Game of Thrones — саундтрек к американскому сериалу канала HBO Игра престолов. Над ним работал немецкий композитор Рамин Джавади, пластинка к первому сезону была выпущена лейблом Varèse Sarabande в июне 2011 года.<br><br>Музыка альбома инструментальная, кроме этого есть заглавная тема сериала — Main Title.<br><br>Сперва над саундтреком Игры престолов должен был работать Стивен Варбек, но 2 февраля 2011 года он покинул проект. Его заменил Рамин Джавади.<br><br>Альбом вместе с цифровым буклетом появился в iTunes 14 июня 2011 года. Релиз компакт диска состоялся 28 июня.',
      image: 'url(../../assets/img/game-of-thrones.webp',
      audio: '../../assets/sound/game-of-thrones.mp3',
      duration: '00:15',
      wikiEn: 'https://en.wikipedia.org/wiki/Music_of_Game_of_Thrones',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%98%D0%B3%D1%80%D0%B0_%D0%BF%D1%80%D0%B5%D1%81%D1%82%D0%BE%D0%BB%D0%BE%D0%B2_(%D1%81%D0%B0%D1%83%D0%BD%D0%B4%D1%82%D1%80%D0%B5%D0%BA)',
      youtube: 'https://youtu.be/TZE9gVF1QbA'
    },
    {
      id: 3,
      nameEn: 'Santa-Barbara',
      nameRu: 'Санта-Барбара',
      trackEn: 'Santa-Barbara Main Title Theme',
      trackRu: 'Главная тема Санта-Барбара',
      authorEn: 'Joe Harnell',
      authorRu: 'Джо Харнелл',
      descriptionEn: 'Santa Barbara is an American television soap opera that aired on NBC from July 30, 1984, to January 15, 1993. The show revolves around the eventful lives of the wealthy Capwell family of Santa Barbara, California.<br><br>The music for "Santa Barbara" was composed by Joe Harnell (1924-2005), who by that time already had vast experience as an arranger and composer.<br><br>Other prominent families featured on the soap were the rival Lockridge family, and the more modest Andrade and Perkins families.<br><br>The serial was produced by Dobson Productions and New World Television, which also served as distributor for the show in international markets. Santa Barbara was the first series for New World Television.<br><br>Santa Barbara aired in the United States at 3:00 PM Eastern (2:00 PM Central) on NBC in the same time slot as General Hospital on ABC and Guiding Light on CBS and right after Another World. Santa Barbara aired in over 40 countries around the world. It became the longest-running television series in Russia, airing there from 1992 to 2002.',
      descriptionRu: '«Санта-Барбара» — американская дневная мыльная опера, транслировавшаяся в США с 1984 по 1993 год на телеканале NBC. Первый сериал, показанный на территории СНГ после распада СССР, один из самых популярных и самый длинный из когда-либо транслировавшихся в России.<br><br>Всего было снято 2137 серий. Действие происходит в городе Санта-Барбара (Калифорния). Сериал рассказывает о жизни богатой семьи Кэпвеллов из города Санта-Барбара.<br><br>Музыкальную заставку к «Санта-Барбаре» сочинил Джо Харнелл (1924-2005), к тому времени уже имевший огромный опыт аранжировщика и композитора.',
      image: 'url(../../assets/img/santa-barbara.webp',
      audio: '../../assets/sound/santa-barbara.mp3',
      duration: '00:34',
      wikiEn: 'https://en.wikipedia.org/wiki/Santa_Barbara_(TV_series)',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%A1%D0%B0%D0%BD%D1%82%D0%B0-%D0%91%D0%B0%D1%80%D0%B1%D0%B0%D1%80%D0%B0_(%D1%82%D0%B5%D0%BB%D0%B5%D1%81%D0%B5%D1%80%D0%B8%D0%B0%D0%BB)',
      youtube: 'https://youtu.be/HTjjNozVy5w'
    },
    {
      id: 4,
      nameEn: 'Pulp Fiction',
      nameRu: 'Криминальное чтиво',
      trackEn: 'You Never Can Tell',
      trackRu: 'Никак не угадать',
      authorEn: 'Chuck Berry',
      authorRu: 'Чак Берри',
      descriptionEn: '"You Never Can Tell", also known as "C\'est La Vie" or "Teenage Wedding", is a song written by Chuck Berry.<br><br>It was composed in the early 1960s while Berry was in federal prison for violating the Mann Act. Released in 1964 on the album St. Louis to Liverpool and the follow-up single to Berry\'s final Top Ten hit of the 1960s: "No Particular Place to Go", "You Never Can Tell" reached number 14, becoming Berry\'s final Top 40 hit until "My Ding-a-Ling", a number 1 in October 1972.<br><br>The song became popular again after the 1994 release of the film Pulp Fiction, directed and co-written by Quentin Tarantino. The music was played for a "Twist contest" in which Vincent Vega (John Travolta) and Mia Wallace (Uma Thurman) competed (and were the only contestants shown in the film). The music added an evocative element of sound to the narrative and Tarantino said that the song\'s lyrics of "Pierre" and "Mademoiselle" gave the scene a "uniquely \'50s French New Wave dance sequence feel".',
      descriptionRu: '«You Never Can Tell» — песня американского рок-музыканта Чака Берри, вышедшая на сингле в 1964 году.<br><br>Песня была написана в начале шестидесятых, в то время, когда Чак Берри находился в тюрьме. You Never Can Tell вошла в альбом Берри St. Louis to Liverpool 1964 года, изданный на лейбле Chess Records, как сингл она дошла до 14 места в рейтинге журнала Billboard.<br><br>Вторая волна популярности You Never Can Tell началась после выхода на экраны фильма культового американского режиссёра Квентина Тарантино «Криминальное чтиво» (1994), в саундтрек которого вошла песня. В одном из эпизодов фильма гангстер Винсент Вега (Джон Траволта) и жена его босса Миа Уоллес (Ума Турман) танцуют твист под песню Чака Берри. По словам Тарантино, лирика песни придаёт этой сцене особую атмосферу Французской новой волны.',
      image: 'url(../../assets/img/pulp-fiction.webp',
      audio: '../../assets/sound/pulp-fiction.mp3',
      duration: '00:26',
      wikiEn: 'https://en.wikipedia.org/wiki/You_Never_Can_Tell_(song)',
      wikiRu: 'https://ru.wikipedia.org/wiki/You_Never_Can_Tell',
      youtube: 'https://youtu.be/WSLMN6g_Od4'
    },{
      id: 5,
      nameEn: 'The Bodyguard',
      nameRu: 'Телохранитель',
      trackEn: 'I Will Always Love You',
      trackRu: 'Я всегда буду любить тебя',
      authorEn: 'Whitney Houston',
      authorRu: 'Уитни Хьюстон',
      descriptionEn: '"I Will Always Love You" is a song written and originally recorded in 1973 by American singer-songwriter Dolly Parton.<br><br>Whitney Houston recorded a soul-ballad arrangement of the song for the 1992 film The Bodyguard. Houston\'s version peaked at number one on the Billboard Hot 100 for a then-record-breaking 14 weeks. The single was certified Diamond by the RIAA, making Houston\'s first Diamond single, the third female artist who had both a Diamond single and a Diamond album, and becoming the best-selling single by a woman in the U.S.<br><br>The song was a global success, topping the charts in almost all countries. With 20 million copies sold it became the best-selling single of all time by a female solo artist.<br><br>Houston won the Grammy Award for Record of the Year in 1994 for "I Will Always Love You". The song has been recorded by many other artists including Linda Ronstadt, John Doe, Amber Riley, LeAnn Rimes and Sarah Washington, whose dance version reached number 12 on the UK Singles Chart.',
      descriptionRu: '«Я всегда буду любить тебя» — сингл американской кантри-певицы Долли Партон, выпущенный в 1974 году на лейбле RCA Records.<br><br>Однако с наибольшим успехом исполнила этот хит другая певица — Уитни Хьюстон. Её соул-версия, включённая в саундтрек к фильму «Телохранитель» 1992 года, была удостоена множества наград, в том числе «Грэмми» за лучшую запись года и лучший женский поп-вокал.<br><br>Критики были впечатлены тем, как грустная любовная песня благодаря мощному вокалу и влиянию госпела превратилась в неистовое воплощение драмы покинутой женщины.',
      image: 'url(../../assets/img/bodyguard.webp',
      audio: '../../assets/sound/bodyguard.mp3',
      duration: '00:47',
      wikiEn: 'https://en.wikipedia.org/wiki/I_Will_Always_Love_You',
      wikiRu: 'https://ru.wikipedia.org/wiki/I_Will_Always_Love_You',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 6,
      nameEn: 'Requiem for a Dream',
      nameRu: 'Реквием по мечте',
      trackEn: 'Lux Aeterna',
      trackRu: 'Вечный свет',
      authorEn: 'Clint Mansell',
      authorRu: 'Клинт Мэнселл',
      descriptionEn: '"Lux Aeterna" is an orchestral composition by Clint Mansell. It forms a leitmotif in the 2000 film Requiem for a Dream, and is the penultimate piece in the movie\'s soundtrack.<br><br>The popularity of the piece led to its use in popular culture outside the film, in film and teaser trailers, such as Sunshine and Waking Madison, and multiple remixes and remakes by other producers.<br><br>It was also used in the 2010 season 2 premiere episode of NCIS: LA and a version of the track was re-orchestrated with a choir and full orchestra for The Lord of the Rings: The Two Towers trailer.<br><br>It was arranged by Simone Benyacar, Daniel Nielsen, and Veigar Margeirsson.<br><br>The orchestrated version was used in various trailers and video games. Clint Mansell commented that the piece had "gone on to have a life of its own".',
      descriptionRu: '«Вечный свет» — саундтрек к фильму Даррена Аронофски «Реквием по мечте» (экранизация романа Хьюберта Селби). Выпущен в 2000 году. Композитором является Клинт Мэнселл.<br><br>Эта музыка стала культовым хитом, так как саундтрек был оценён по достоинству многими музыкантами и получил широкое признание, а композиция «Lux Aeterna» и её реаранжированная версия «Requiem for a Tower» впоследствии были использованы в различных формах массовой информации (трейлеры и тизеры фильмов и сериалов, видеоигры, телепередачи, рекламные ролики и другие медиа).<br><br>Саундтрек Requiem for a Dream закрепил свою популярность после издания альбома Requiem for a Dream: Remixed, содержавшего новые ремиксы, созданные Полом Окенфолдом, Джошем Уинком, Джэгзом Кунером, Delerium и многими другими.',
      image: 'url(../../assets/img/requiem.webp',
      audio: '../../assets/sound/requiem.mp3',
      duration: '00:30',
      wikiEn: 'https://en.wikipedia.org/wiki/Lux_Aeterna_(Mansell)',
      wikiRu: 'https://ru.wikipedia.org/wiki/Requiem_for_a_Dream_(%D1%81%D0%B0%D1%83%D0%BD%D0%B4%D1%82%D1%80%D0%B5%D0%BA)',
      youtube: 'https://youtu.be/oc3Cq89P97Y'
    }
  ],
  [
    {
      id: 1,
      nameEn: 'Titanic',
      nameRu: 'Титаник',
      trackEn: 'My Heart Will Go On',
      trackRu: 'Моё сердце будет биться',
      authorEn: 'Céline Dion',
      authorRu: 'Селин Дион',
      descriptionEn: '"My Heart Will Go On" is a 1997 song recorded by Canadian singer Celine Dion.<br><br>The song serves as the main soundtrack to James Cameron\'s blockbuster film Titanic, based on an account of the transatlantic ocean liner of the same name which sank in 1912 after colliding with an iceberg in the North Atlantic Ocean.<br><br>The song\'s music was composed by James Horner, its lyrics were written by Will Jennings, while the production was handled by Walter Afanasieff, Horner and Simon Franglen.',
      descriptionRu: '"Моё сердце будет биться дальше" — песня канадской певицы Селин Дион, главная тема к фильму Джеймса Кэмерона "Титаник".<br><br>Автор музыки — Джеймс Хорнер, слова написал Уилл Дженнингс, продюсером стал Уолтер Афанасьефф. Композиция была выпущена на альбоме Дион Let\'s Talk About Love в 1997 году, она возглавила чарты по всему миру, включая США, Великобританию и Австралию.<br><br>Релиз сингла состоялся в Австралии и Германии 8 декабря 1997 года и в январе и феврале 1998 года в остальном мире, композиция стала одной из самых популярных за всю историю музыки и самой продаваемой в мире песней 1998 года.емыми в более чем 18 миллионов копий, это второй самый продаваемый сингл на физическом носителе в истории музыки и один из самых продаваемых синглов всех времен.<br><br>Он также был самым продаваемым синглом в мире за 1998 год. Песня также была включена в список "Песни века" Американской ассоциацией звукозаписывающей индустрии и Национальным фондом искусств.<br><br>Дион исполнила песню в честь 20-летия фильма "Титаник" на церемонии вручения премии Billboard Music Awards 21 мая 2017 года.',
      image: 'url(../../assets/img/titanic.webp',
      audio: '../../assets/sound/titanic.mp3',
      duration: '00:17',
      wikiEn: 'https://en.wikipedia.org/wiki/My_Heart_Will_Go_On',
      wikiRu: 'https://ru.wikipedia.org/wiki/My_Heart_Will_Go_On',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 2,
      nameEn: 'Star Wars',
      nameRu: 'Звёздные войны',
      trackEn: 'The Imperial March',
      trackRu: 'Имперский марш',
      authorEn: 'John Williams',
      authorRu: 'Джон Уильямс',
      descriptionEn: '"The Imperial March (Darth Vader\'s Theme)" is a musical theme present in the Star Wars franchise. It was composed by John Williams for the film The Empire Strikes Back.<br><br>Together with "Yoda\'s Theme", "The Imperial March" was premiered on April 29, 1980, three weeks before the opening of the film, on the occasion of John Williams first concert as official conductor-in-residence of the Boston Pops Orchestra.<br><br>One of the best known symphonic movie themes, it is used as a leitmotif throughout the Star Wars franchise.',
      descriptionRu: '«Имперский марш (Тема Дарта Вейдера)» — музыкальная тема, представленная во франшизе «Звёздные войны». Она была написана Джоном Уильямсом для фильма «Звёздные войны. Эпизод V: Империя наносит ответный удар».<br><br>Вместе с «темой Йоды» премьера «Имперского марша» состоялась 29 апреля 1980 года, за три недели до открытия фильма, по случаю первого концерта Джона Уильямса в качестве официального дирижёра Boston Pops Orchestra.<br><br>Одна из самых известных тем симфонического кино, это пример лейтмотива, повторяющейся темы, связанной с персонажами или событиями в драме.',
      image: 'url(../../assets/img/star-wars.webp',
      audio: '../../assets/sound/star-wars.mp3',
      duration: '00:21',
      wikiEn: 'https://en.wikipedia.org/wiki/The_Imperial_March',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%98%D0%BC%D0%BF%D0%B5%D1%80%D1%81%D0%BA%D0%B8%D0%B9_%D0%BC%D0%B0%D1%80%D1%88',
      youtube: 'https://youtu.be/vsMWVW4xtwI'
    },
    {
      id: 3,
      nameEn: 'The Godfather',
      nameRu: 'Крёстный отец',
      trackEn: 'Speak Softly Love',
      trackRu: 'Говори тихо, любовь моя',
      authorEn: 'Nino Rota',
      authorRu: 'Нино Рота',
      descriptionEn: '"Love Theme from The Godfather" is an instrumental theme from the 1972 film The Godfather, composed by Nino Rota.<br><br>The piece was lyricized in English by Larry Kusik into "Speak Softly, Love", a popular song released in 1972.<br><br>The highest-charting rendition of either version was by vocalist Andy Williams, who took "Speak Softly Love" to number 34 on Billboard magazine\'s Hot 100 and number seven on its Easy Listening chart.',
      descriptionRu: '«Говори тихо, любовь моя» — песня композитора Нино Рота на слова Ларри Кьюзика, впервые прозвучавшая в инструментальном исполнении в фильме «Крёстный отец» (1972).<br><br>Наибольшей популярности песня достигла в исполнении Энди Уильямса, поднявшись до 43-й позиции в Billboard Hot 100 и седьмого места в хит-параде Easy Listening.<br><br>Позднее эту песню исполняли также Эл Мартино, София Ротару («Скажи, що любиш», 1975), Бобби Винтон, Муслим Магомаев, Олег Погудин и другие певцы.',
      image: 'url(../../assets/img/godfather.webp',
      audio: '../../assets/sound/godfather.mp3',
      duration: '00:15',
      wikiEn: 'https://en.wikipedia.org/wiki/Love_Theme_from_The_Godfather',
      wikiRu: 'https://ru.wikipedia.org/wiki/Speak_Softly_Love',
      youtube: 'https://youtu.be/zbSMCyJkUmI'
    },
    {
      id: 4,
      nameEn: 'Pulp Fiction',
      nameRu: 'Криминальное чтиво',
      trackEn: 'You Never Can Tell',
      trackRu: 'Никак не угадать',
      authorEn: 'Chuck Berry',
      authorRu: 'Чак Берри',
      descriptionEn: '"You Never Can Tell", also known as "C\'est La Vie" or "Teenage Wedding", is a song written by Chuck Berry.<br><br>It was composed in the early 1960s while Berry was in federal prison for violating the Mann Act. Released in 1964 on the album St. Louis to Liverpool and the follow-up single to Berry\'s final Top Ten hit of the 1960s: "No Particular Place to Go", "You Never Can Tell" reached number 14, becoming Berry\'s final Top 40 hit until "My Ding-a-Ling", a number 1 in October 1972.<br><br>The song became popular again after the 1994 release of the film Pulp Fiction, directed and co-written by Quentin Tarantino. The music was played for a "Twist contest" in which Vincent Vega (John Travolta) and Mia Wallace (Uma Thurman) competed (and were the only contestants shown in the film). The music added an evocative element of sound to the narrative and Tarantino said that the song\'s lyrics of "Pierre" and "Mademoiselle" gave the scene a "uniquely \'50s French New Wave dance sequence feel".',
      descriptionRu: '«You Never Can Tell» — песня американского рок-музыканта Чака Берри, вышедшая на сингле в 1964 году.<br><br>Песня была написана в начале шестидесятых, в то время, когда Чак Берри находился в тюрьме. You Never Can Tell вошла в альбом Берри St. Louis to Liverpool 1964 года, изданный на лейбле Chess Records, как сингл она дошла до 14 места в рейтинге журнала Billboard.<br><br>Вторая волна популярности You Never Can Tell началась после выхода на экраны фильма культового американского режиссёра Квентина Тарантино «Криминальное чтиво» (1994), в саундтрек которого вошла песня. В одном из эпизодов фильма гангстер Винсент Вега (Джон Траволта) и жена его босса Миа Уоллес (Ума Турман) танцуют твист под песню Чака Берри. По словам Тарантино, лирика песни придаёт этой сцене особую атмосферу Французской новой волны.',
      image: 'url(../../assets/img/pulp-fiction.webp',
      audio: '../../assets/sound/pulp-fiction.mp3',
      duration: '00:26',
      wikiEn: 'https://en.wikipedia.org/wiki/You_Never_Can_Tell_(song)',
      wikiRu: 'https://ru.wikipedia.org/wiki/You_Never_Can_Tell',
      youtube: 'https://youtu.be/WSLMN6g_Od4'
    },{
      id: 5,
      nameEn: 'The Bodyguard',
      nameRu: 'Телохранитель',
      trackEn: 'I Will Always Love You',
      trackRu: 'Я всегда буду любить тебя',
      authorEn: 'Whitney Houston',
      authorRu: 'Уитни Хьюстон',
      descriptionEn: '"I Will Always Love You" is a song written and originally recorded in 1973 by American singer-songwriter Dolly Parton.<br><br>Whitney Houston recorded a soul-ballad arrangement of the song for the 1992 film The Bodyguard. Houston\'s version peaked at number one on the Billboard Hot 100 for a then-record-breaking 14 weeks. The single was certified Diamond by the RIAA, making Houston\'s first Diamond single, the third female artist who had both a Diamond single and a Diamond album, and becoming the best-selling single by a woman in the U.S.<br><br>The song was a global success, topping the charts in almost all countries. With 20 million copies sold it became the best-selling single of all time by a female solo artist.<br><br>Houston won the Grammy Award for Record of the Year in 1994 for "I Will Always Love You". The song has been recorded by many other artists including Linda Ronstadt, John Doe, Amber Riley, LeAnn Rimes and Sarah Washington, whose dance version reached number 12 on the UK Singles Chart.',
      descriptionRu: '«Я всегда буду любить тебя» — сингл американской кантри-певицы Долли Партон, выпущенный в 1974 году на лейбле RCA Records.<br><br>Однако с наибольшим успехом исполнила этот хит другая певица — Уитни Хьюстон. Её соул-версия, включённая в саундтрек к фильму «Телохранитель» 1992 года, была удостоена множества наград, в том числе «Грэмми» за лучшую запись года и лучший женский поп-вокал.<br><br>Критики были впечатлены тем, как грустная любовная песня благодаря мощному вокалу и влиянию госпела превратилась в неистовое воплощение драмы покинутой женщины.',
      image: 'url(../../assets/img/bodyguard.webp',
      audio: '../../assets/sound/bodyguard.mp3',
      duration: '00:47',
      wikiEn: 'https://en.wikipedia.org/wiki/I_Will_Always_Love_You',
      wikiRu: 'https://ru.wikipedia.org/wiki/I_Will_Always_Love_You',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 6,
      nameEn: 'Requiem for a Dream',
      nameRu: 'Реквием по мечте',
      trackEn: 'Lux Aeterna',
      trackRu: 'Вечный свет',
      authorEn: 'Clint Mansell',
      authorRu: 'Клинт Мэнселл',
      descriptionEn: '"Lux Aeterna" is an orchestral composition by Clint Mansell. It forms a leitmotif in the 2000 film Requiem for a Dream, and is the penultimate piece in the movie\'s soundtrack.<br><br>The popularity of the piece led to its use in popular culture outside the film, in film and teaser trailers, such as Sunshine and Waking Madison, and multiple remixes and remakes by other producers.<br><br>It was also used in the 2010 season 2 premiere episode of NCIS: LA and a version of the track was re-orchestrated with a choir and full orchestra for The Lord of the Rings: The Two Towers trailer.<br><br>It was arranged by Simone Benyacar, Daniel Nielsen, and Veigar Margeirsson.<br><br>The orchestrated version was used in various trailers and video games. Clint Mansell commented that the piece had "gone on to have a life of its own".',
      descriptionRu: '«Вечный свет» — саундтрек к фильму Даррена Аронофски «Реквием по мечте» (экранизация романа Хьюберта Селби). Выпущен в 2000 году. Композитором является Клинт Мэнселл.<br><br>Эта музыка стала культовым хитом, так как саундтрек был оценён по достоинству многими музыкантами и получил широкое признание, а композиция «Lux Aeterna» и её реаранжированная версия «Requiem for a Tower» впоследствии были использованы в различных формах массовой информации (трейлеры и тизеры фильмов и сериалов, видеоигры, телепередачи, рекламные ролики и другие медиа).<br><br>Саундтрек Requiem for a Dream закрепил свою популярность после издания альбома Requiem for a Dream: Remixed, содержавшего новые ремиксы, созданные Полом Окенфолдом, Джошем Уинком, Джэгзом Кунером, Delerium и многими другими.',
      image: 'url(../../assets/img/requiem.webp',
      audio: '../../assets/sound/requiem.mp3',
      duration: '00:30',
      wikiEn: 'https://en.wikipedia.org/wiki/Lux_Aeterna_(Mansell)',
      wikiRu: 'https://ru.wikipedia.org/wiki/Requiem_for_a_Dream_(%D1%81%D0%B0%D1%83%D0%BD%D0%B4%D1%82%D1%80%D0%B5%D0%BA)',
      youtube: 'https://youtu.be/oc3Cq89P97Y'
    }
  ],
  [
    {
      id: 1,
      nameEn: 'Titanic',
      nameRu: 'Титаник',
      trackEn: 'My Heart Will Go On',
      trackRu: 'Моё сердце будет биться',
      authorEn: 'Céline Dion',
      authorRu: 'Селин Дион',
      descriptionEn: '"My Heart Will Go On" is a 1997 song recorded by Canadian singer Celine Dion.<br><br>The song serves as the main soundtrack to James Cameron\'s blockbuster film Titanic, based on an account of the transatlantic ocean liner of the same name which sank in 1912 after colliding with an iceberg in the North Atlantic Ocean.<br><br>The song\'s music was composed by James Horner, its lyrics were written by Will Jennings, while the production was handled by Walter Afanasieff, Horner and Simon Franglen.',
      descriptionRu: '"Моё сердце будет биться дальше" — песня канадской певицы Селин Дион, главная тема к фильму Джеймса Кэмерона "Титаник".<br><br>Автор музыки — Джеймс Хорнер, слова написал Уилл Дженнингс, продюсером стал Уолтер Афанасьефф. Композиция была выпущена на альбоме Дион Let\'s Talk About Love в 1997 году, она возглавила чарты по всему миру, включая США, Великобританию и Австралию.<br><br>Релиз сингла состоялся в Австралии и Германии 8 декабря 1997 года и в январе и феврале 1998 года в остальном мире, композиция стала одной из самых популярных за всю историю музыки и самой продаваемой в мире песней 1998 года.емыми в более чем 18 миллионов копий, это второй самый продаваемый сингл на физическом носителе в истории музыки и один из самых продаваемых синглов всех времен.<br><br>Он также был самым продаваемым синглом в мире за 1998 год. Песня также была включена в список "Песни века" Американской ассоциацией звукозаписывающей индустрии и Национальным фондом искусств.<br><br>Дион исполнила песню в честь 20-летия фильма "Титаник" на церемонии вручения премии Billboard Music Awards 21 мая 2017 года.',
      image: 'url(../../assets/img/titanic.webp',
      audio: '../../assets/sound/titanic.mp3',
      duration: '00:17',
      wikiEn: 'https://en.wikipedia.org/wiki/My_Heart_Will_Go_On',
      wikiRu: 'https://ru.wikipedia.org/wiki/My_Heart_Will_Go_On',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 2,
      nameEn: 'Star Wars',
      nameRu: 'Звёздные войны',
      trackEn: 'The Imperial March',
      trackRu: 'Имперский марш',
      authorEn: 'John Williams',
      authorRu: 'Джон Уильямс',
      descriptionEn: '"The Imperial March (Darth Vader\'s Theme)" is a musical theme present in the Star Wars franchise. It was composed by John Williams for the film The Empire Strikes Back.<br><br>Together with "Yoda\'s Theme", "The Imperial March" was premiered on April 29, 1980, three weeks before the opening of the film, on the occasion of John Williams first concert as official conductor-in-residence of the Boston Pops Orchestra.<br><br>One of the best known symphonic movie themes, it is used as a leitmotif throughout the Star Wars franchise.',
      descriptionRu: '«Имперский марш (Тема Дарта Вейдера)» — музыкальная тема, представленная во франшизе «Звёздные войны». Она была написана Джоном Уильямсом для фильма «Звёздные войны. Эпизод V: Империя наносит ответный удар».<br><br>Вместе с «темой Йоды» премьера «Имперского марша» состоялась 29 апреля 1980 года, за три недели до открытия фильма, по случаю первого концерта Джона Уильямса в качестве официального дирижёра Boston Pops Orchestra.<br><br>Одна из самых известных тем симфонического кино, это пример лейтмотива, повторяющейся темы, связанной с персонажами или событиями в драме.',
      image: 'url(../../assets/img/star-wars.webp',
      audio: '../../assets/sound/star-wars.mp3',
      duration: '00:21',
      wikiEn: 'https://en.wikipedia.org/wiki/The_Imperial_March',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%98%D0%BC%D0%BF%D0%B5%D1%80%D1%81%D0%BA%D0%B8%D0%B9_%D0%BC%D0%B0%D1%80%D1%88',
      youtube: 'https://youtu.be/vsMWVW4xtwI'
    },
    {
      id: 3,
      nameEn: 'The Godfather',
      nameRu: 'Крёстный отец',
      trackEn: 'Speak Softly Love',
      trackRu: 'Говори тихо, любовь моя',
      authorEn: 'Nino Rota',
      authorRu: 'Нино Рота',
      descriptionEn: '"Love Theme from The Godfather" is an instrumental theme from the 1972 film The Godfather, composed by Nino Rota.<br><br>The piece was lyricized in English by Larry Kusik into "Speak Softly, Love", a popular song released in 1972.<br><br>The highest-charting rendition of either version was by vocalist Andy Williams, who took "Speak Softly Love" to number 34 on Billboard magazine\'s Hot 100 and number seven on its Easy Listening chart.',
      descriptionRu: '«Говори тихо, любовь моя» — песня композитора Нино Рота на слова Ларри Кьюзика, впервые прозвучавшая в инструментальном исполнении в фильме «Крёстный отец» (1972).<br><br>Наибольшей популярности песня достигла в исполнении Энди Уильямса, поднявшись до 43-й позиции в Billboard Hot 100 и седьмого места в хит-параде Easy Listening.<br><br>Позднее эту песню исполняли также Эл Мартино, София Ротару («Скажи, що любиш», 1975), Бобби Винтон, Муслим Магомаев, Олег Погудин и другие певцы.',
      image: 'url(../../assets/img/godfather.webp',
      audio: '../../assets/sound/godfather.mp3',
      duration: '00:15',
      wikiEn: 'https://en.wikipedia.org/wiki/Love_Theme_from_The_Godfather',
      wikiRu: 'https://ru.wikipedia.org/wiki/Speak_Softly_Love',
      youtube: 'https://youtu.be/zbSMCyJkUmI'
    },
    {
      id: 4,
      nameEn: 'Pulp Fiction',
      nameRu: 'Криминальное чтиво',
      trackEn: 'You Never Can Tell',
      trackRu: 'Никак не угадать',
      authorEn: 'Chuck Berry',
      authorRu: 'Чак Берри',
      descriptionEn: '"You Never Can Tell", also known as "C\'est La Vie" or "Teenage Wedding", is a song written by Chuck Berry.<br><br>It was composed in the early 1960s while Berry was in federal prison for violating the Mann Act. Released in 1964 on the album St. Louis to Liverpool and the follow-up single to Berry\'s final Top Ten hit of the 1960s: "No Particular Place to Go", "You Never Can Tell" reached number 14, becoming Berry\'s final Top 40 hit until "My Ding-a-Ling", a number 1 in October 1972.<br><br>The song became popular again after the 1994 release of the film Pulp Fiction, directed and co-written by Quentin Tarantino. The music was played for a "Twist contest" in which Vincent Vega (John Travolta) and Mia Wallace (Uma Thurman) competed (and were the only contestants shown in the film). The music added an evocative element of sound to the narrative and Tarantino said that the song\'s lyrics of "Pierre" and "Mademoiselle" gave the scene a "uniquely \'50s French New Wave dance sequence feel".',
      descriptionRu: '«You Never Can Tell» — песня американского рок-музыканта Чака Берри, вышедшая на сингле в 1964 году.<br><br>Песня была написана в начале шестидесятых, в то время, когда Чак Берри находился в тюрьме. You Never Can Tell вошла в альбом Берри St. Louis to Liverpool 1964 года, изданный на лейбле Chess Records, как сингл она дошла до 14 места в рейтинге журнала Billboard.<br><br>Вторая волна популярности You Never Can Tell началась после выхода на экраны фильма культового американского режиссёра Квентина Тарантино «Криминальное чтиво» (1994), в саундтрек которого вошла песня. В одном из эпизодов фильма гангстер Винсент Вега (Джон Траволта) и жена его босса Миа Уоллес (Ума Турман) танцуют твист под песню Чака Берри. По словам Тарантино, лирика песни придаёт этой сцене особую атмосферу Французской новой волны.',
      image: 'url(../../assets/img/pulp-fiction.webp',
      audio: '../../assets/sound/pulp-fiction.mp3',
      duration: '00:26',
      wikiEn: 'https://en.wikipedia.org/wiki/You_Never_Can_Tell_(song)',
      wikiRu: 'https://ru.wikipedia.org/wiki/You_Never_Can_Tell',
      youtube: 'https://youtu.be/WSLMN6g_Od4'
    },{
      id: 5,
      nameEn: 'The Bodyguard',
      nameRu: 'Телохранитель',
      trackEn: 'I Will Always Love You',
      trackRu: 'Я всегда буду любить тебя',
      authorEn: 'Whitney Houston',
      authorRu: 'Уитни Хьюстон',
      descriptionEn: '"I Will Always Love You" is a song written and originally recorded in 1973 by American singer-songwriter Dolly Parton.<br><br>Whitney Houston recorded a soul-ballad arrangement of the song for the 1992 film The Bodyguard. Houston\'s version peaked at number one on the Billboard Hot 100 for a then-record-breaking 14 weeks. The single was certified Diamond by the RIAA, making Houston\'s first Diamond single, the third female artist who had both a Diamond single and a Diamond album, and becoming the best-selling single by a woman in the U.S.<br><br>The song was a global success, topping the charts in almost all countries. With 20 million copies sold it became the best-selling single of all time by a female solo artist.<br><br>Houston won the Grammy Award for Record of the Year in 1994 for "I Will Always Love You". The song has been recorded by many other artists including Linda Ronstadt, John Doe, Amber Riley, LeAnn Rimes and Sarah Washington, whose dance version reached number 12 on the UK Singles Chart.',
      descriptionRu: '«Я всегда буду любить тебя» — сингл американской кантри-певицы Долли Партон, выпущенный в 1974 году на лейбле RCA Records.<br><br>Однако с наибольшим успехом исполнила этот хит другая певица — Уитни Хьюстон. Её соул-версия, включённая в саундтрек к фильму «Телохранитель» 1992 года, была удостоена множества наград, в том числе «Грэмми» за лучшую запись года и лучший женский поп-вокал.<br><br>Критики были впечатлены тем, как грустная любовная песня благодаря мощному вокалу и влиянию госпела превратилась в неистовое воплощение драмы покинутой женщины.',
      image: 'url(../../assets/img/bodyguard.webp',
      audio: '../../assets/sound/bodyguard.mp3',
      duration: '00:47',
      wikiEn: 'https://en.wikipedia.org/wiki/I_Will_Always_Love_You',
      wikiRu: 'https://ru.wikipedia.org/wiki/I_Will_Always_Love_You',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 6,
      nameEn: 'Requiem for a Dream',
      nameRu: 'Реквием по мечте',
      trackEn: 'Lux Aeterna',
      trackRu: 'Вечный свет',
      authorEn: 'Clint Mansell',
      authorRu: 'Клинт Мэнселл',
      descriptionEn: '"Lux Aeterna" is an orchestral composition by Clint Mansell. It forms a leitmotif in the 2000 film Requiem for a Dream, and is the penultimate piece in the movie\'s soundtrack.<br><br>The popularity of the piece led to its use in popular culture outside the film, in film and teaser trailers, such as Sunshine and Waking Madison, and multiple remixes and remakes by other producers.<br><br>It was also used in the 2010 season 2 premiere episode of NCIS: LA and a version of the track was re-orchestrated with a choir and full orchestra for The Lord of the Rings: The Two Towers trailer.<br><br>It was arranged by Simone Benyacar, Daniel Nielsen, and Veigar Margeirsson.<br><br>The orchestrated version was used in various trailers and video games. Clint Mansell commented that the piece had "gone on to have a life of its own".',
      descriptionRu: '«Вечный свет» — саундтрек к фильму Даррена Аронофски «Реквием по мечте» (экранизация романа Хьюберта Селби). Выпущен в 2000 году. Композитором является Клинт Мэнселл.<br><br>Эта музыка стала культовым хитом, так как саундтрек был оценён по достоинству многими музыкантами и получил широкое признание, а композиция «Lux Aeterna» и её реаранжированная версия «Requiem for a Tower» впоследствии были использованы в различных формах массовой информации (трейлеры и тизеры фильмов и сериалов, видеоигры, телепередачи, рекламные ролики и другие медиа).<br><br>Саундтрек Requiem for a Dream закрепил свою популярность после издания альбома Requiem for a Dream: Remixed, содержавшего новые ремиксы, созданные Полом Окенфолдом, Джошем Уинком, Джэгзом Кунером, Delerium и многими другими.',
      image: 'url(../../assets/img/requiem.webp',
      audio: '../../assets/sound/requiem.mp3',
      duration: '00:30',
      wikiEn: 'https://en.wikipedia.org/wiki/Lux_Aeterna_(Mansell)',
      wikiRu: 'https://ru.wikipedia.org/wiki/Requiem_for_a_Dream_(%D1%81%D0%B0%D1%83%D0%BD%D0%B4%D1%82%D1%80%D0%B5%D0%BA)',
      youtube: 'https://youtu.be/oc3Cq89P97Y'
    }
  ],
  [
    {
      id: 1,
      nameEn: 'Titanic',
      nameRu: 'Титаник',
      trackEn: 'My Heart Will Go On',
      trackRu: 'Моё сердце будет биться',
      authorEn: 'Céline Dion',
      authorRu: 'Селин Дион',
      descriptionEn: '"My Heart Will Go On" is a 1997 song recorded by Canadian singer Celine Dion.<br><br>The song serves as the main soundtrack to James Cameron\'s blockbuster film Titanic, based on an account of the transatlantic ocean liner of the same name which sank in 1912 after colliding with an iceberg in the North Atlantic Ocean.<br><br>The song\'s music was composed by James Horner, its lyrics were written by Will Jennings, while the production was handled by Walter Afanasieff, Horner and Simon Franglen.',
      descriptionRu: '"Моё сердце будет биться дальше" — песня канадской певицы Селин Дион, главная тема к фильму Джеймса Кэмерона "Титаник".<br><br>Автор музыки — Джеймс Хорнер, слова написал Уилл Дженнингс, продюсером стал Уолтер Афанасьефф. Композиция была выпущена на альбоме Дион Let\'s Talk About Love в 1997 году, она возглавила чарты по всему миру, включая США, Великобританию и Австралию.<br><br>Релиз сингла состоялся в Австралии и Германии 8 декабря 1997 года и в январе и феврале 1998 года в остальном мире, композиция стала одной из самых популярных за всю историю музыки и самой продаваемой в мире песней 1998 года.емыми в более чем 18 миллионов копий, это второй самый продаваемый сингл на физическом носителе в истории музыки и один из самых продаваемых синглов всех времен.<br><br>Он также был самым продаваемым синглом в мире за 1998 год. Песня также была включена в список "Песни века" Американской ассоциацией звукозаписывающей индустрии и Национальным фондом искусств.<br><br>Дион исполнила песню в честь 20-летия фильма "Титаник" на церемонии вручения премии Billboard Music Awards 21 мая 2017 года.',
      image: 'url(../../assets/img/titanic.webp',
      audio: '../../assets/sound/titanic.mp3',
      duration: '00:17',
      wikiEn: 'https://en.wikipedia.org/wiki/My_Heart_Will_Go_On',
      wikiRu: 'https://ru.wikipedia.org/wiki/My_Heart_Will_Go_On',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 2,
      nameEn: 'Star Wars',
      nameRu: 'Звёздные войны',
      trackEn: 'The Imperial March',
      trackRu: 'Имперский марш',
      authorEn: 'John Williams',
      authorRu: 'Джон Уильямс',
      descriptionEn: '"The Imperial March (Darth Vader\'s Theme)" is a musical theme present in the Star Wars franchise. It was composed by John Williams for the film The Empire Strikes Back.<br><br>Together with "Yoda\'s Theme", "The Imperial March" was premiered on April 29, 1980, three weeks before the opening of the film, on the occasion of John Williams first concert as official conductor-in-residence of the Boston Pops Orchestra.<br><br>One of the best known symphonic movie themes, it is used as a leitmotif throughout the Star Wars franchise.',
      descriptionRu: '«Имперский марш (Тема Дарта Вейдера)» — музыкальная тема, представленная во франшизе «Звёздные войны». Она была написана Джоном Уильямсом для фильма «Звёздные войны. Эпизод V: Империя наносит ответный удар».<br><br>Вместе с «темой Йоды» премьера «Имперского марша» состоялась 29 апреля 1980 года, за три недели до открытия фильма, по случаю первого концерта Джона Уильямса в качестве официального дирижёра Boston Pops Orchestra.<br><br>Одна из самых известных тем симфонического кино, это пример лейтмотива, повторяющейся темы, связанной с персонажами или событиями в драме.',
      image: 'url(../../assets/img/star-wars.webp',
      audio: '../../assets/sound/star-wars.mp3',
      duration: '00:21',
      wikiEn: 'https://en.wikipedia.org/wiki/The_Imperial_March',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%98%D0%BC%D0%BF%D0%B5%D1%80%D1%81%D0%BA%D0%B8%D0%B9_%D0%BC%D0%B0%D1%80%D1%88',
      youtube: 'https://youtu.be/vsMWVW4xtwI'
    },
    {
      id: 3,
      nameEn: 'The Godfather',
      nameRu: 'Крёстный отец',
      trackEn: 'Speak Softly Love',
      trackRu: 'Говори тихо, любовь моя',
      authorEn: 'Nino Rota',
      authorRu: 'Нино Рота',
      descriptionEn: '"Love Theme from The Godfather" is an instrumental theme from the 1972 film The Godfather, composed by Nino Rota.<br><br>The piece was lyricized in English by Larry Kusik into "Speak Softly, Love", a popular song released in 1972.<br><br>The highest-charting rendition of either version was by vocalist Andy Williams, who took "Speak Softly Love" to number 34 on Billboard magazine\'s Hot 100 and number seven on its Easy Listening chart.',
      descriptionRu: '«Говори тихо, любовь моя» — песня композитора Нино Рота на слова Ларри Кьюзика, впервые прозвучавшая в инструментальном исполнении в фильме «Крёстный отец» (1972).<br><br>Наибольшей популярности песня достигла в исполнении Энди Уильямса, поднявшись до 43-й позиции в Billboard Hot 100 и седьмого места в хит-параде Easy Listening.<br><br>Позднее эту песню исполняли также Эл Мартино, София Ротару («Скажи, що любиш», 1975), Бобби Винтон, Муслим Магомаев, Олег Погудин и другие певцы.',
      image: 'url(../../assets/img/godfather.webp',
      audio: '../../assets/sound/godfather.mp3',
      duration: '00:15',
      wikiEn: 'https://en.wikipedia.org/wiki/Love_Theme_from_The_Godfather',
      wikiRu: 'https://ru.wikipedia.org/wiki/Speak_Softly_Love',
      youtube: 'https://youtu.be/zbSMCyJkUmI'
    },
    {
      id: 4,
      nameEn: 'Pulp Fiction',
      nameRu: 'Криминальное чтиво',
      trackEn: 'You Never Can Tell',
      trackRu: 'Никак не угадать',
      authorEn: 'Chuck Berry',
      authorRu: 'Чак Берри',
      descriptionEn: '"You Never Can Tell", also known as "C\'est La Vie" or "Teenage Wedding", is a song written by Chuck Berry.<br><br>It was composed in the early 1960s while Berry was in federal prison for violating the Mann Act. Released in 1964 on the album St. Louis to Liverpool and the follow-up single to Berry\'s final Top Ten hit of the 1960s: "No Particular Place to Go", "You Never Can Tell" reached number 14, becoming Berry\'s final Top 40 hit until "My Ding-a-Ling", a number 1 in October 1972.<br><br>The song became popular again after the 1994 release of the film Pulp Fiction, directed and co-written by Quentin Tarantino. The music was played for a "Twist contest" in which Vincent Vega (John Travolta) and Mia Wallace (Uma Thurman) competed (and were the only contestants shown in the film). The music added an evocative element of sound to the narrative and Tarantino said that the song\'s lyrics of "Pierre" and "Mademoiselle" gave the scene a "uniquely \'50s French New Wave dance sequence feel".',
      descriptionRu: '«You Never Can Tell» — песня американского рок-музыканта Чака Берри, вышедшая на сингле в 1964 году.<br><br>Песня была написана в начале шестидесятых, в то время, когда Чак Берри находился в тюрьме. You Never Can Tell вошла в альбом Берри St. Louis to Liverpool 1964 года, изданный на лейбле Chess Records, как сингл она дошла до 14 места в рейтинге журнала Billboard.<br><br>Вторая волна популярности You Never Can Tell началась после выхода на экраны фильма культового американского режиссёра Квентина Тарантино «Криминальное чтиво» (1994), в саундтрек которого вошла песня. В одном из эпизодов фильма гангстер Винсент Вега (Джон Траволта) и жена его босса Миа Уоллес (Ума Турман) танцуют твист под песню Чака Берри. По словам Тарантино, лирика песни придаёт этой сцене особую атмосферу Французской новой волны.',
      image: 'url(../../assets/img/pulp-fiction.webp',
      audio: '../../assets/sound/pulp-fiction.mp3',
      duration: '00:26',
      wikiEn: 'https://en.wikipedia.org/wiki/You_Never_Can_Tell_(song)',
      wikiRu: 'https://ru.wikipedia.org/wiki/You_Never_Can_Tell',
      youtube: 'https://youtu.be/WSLMN6g_Od4'
    },{
      id: 5,
      nameEn: 'The Bodyguard',
      nameRu: 'Телохранитель',
      trackEn: 'I Will Always Love You',
      trackRu: 'Я всегда буду любить тебя',
      authorEn: 'Whitney Houston',
      authorRu: 'Уитни Хьюстон',
      descriptionEn: '"I Will Always Love You" is a song written and originally recorded in 1973 by American singer-songwriter Dolly Parton.<br><br>Whitney Houston recorded a soul-ballad arrangement of the song for the 1992 film The Bodyguard. Houston\'s version peaked at number one on the Billboard Hot 100 for a then-record-breaking 14 weeks. The single was certified Diamond by the RIAA, making Houston\'s first Diamond single, the third female artist who had both a Diamond single and a Diamond album, and becoming the best-selling single by a woman in the U.S.<br><br>The song was a global success, topping the charts in almost all countries. With 20 million copies sold it became the best-selling single of all time by a female solo artist.<br><br>Houston won the Grammy Award for Record of the Year in 1994 for "I Will Always Love You". The song has been recorded by many other artists including Linda Ronstadt, John Doe, Amber Riley, LeAnn Rimes and Sarah Washington, whose dance version reached number 12 on the UK Singles Chart.',
      descriptionRu: '«Я всегда буду любить тебя» — сингл американской кантри-певицы Долли Партон, выпущенный в 1974 году на лейбле RCA Records.<br><br>Однако с наибольшим успехом исполнила этот хит другая певица — Уитни Хьюстон. Её соул-версия, включённая в саундтрек к фильму «Телохранитель» 1992 года, была удостоена множества наград, в том числе «Грэмми» за лучшую запись года и лучший женский поп-вокал.<br><br>Критики были впечатлены тем, как грустная любовная песня благодаря мощному вокалу и влиянию госпела превратилась в неистовое воплощение драмы покинутой женщины.',
      image: 'url(../../assets/img/bodyguard.webp',
      audio: '../../assets/sound/bodyguard.mp3',
      duration: '00:47',
      wikiEn: 'https://en.wikipedia.org/wiki/I_Will_Always_Love_You',
      wikiRu: 'https://ru.wikipedia.org/wiki/I_Will_Always_Love_You',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 6,
      nameEn: 'Requiem for a Dream',
      nameRu: 'Реквием по мечте',
      trackEn: 'Lux Aeterna',
      trackRu: 'Вечный свет',
      authorEn: 'Clint Mansell',
      authorRu: 'Клинт Мэнселл',
      descriptionEn: '"Lux Aeterna" is an orchestral composition by Clint Mansell. It forms a leitmotif in the 2000 film Requiem for a Dream, and is the penultimate piece in the movie\'s soundtrack.<br><br>The popularity of the piece led to its use in popular culture outside the film, in film and teaser trailers, such as Sunshine and Waking Madison, and multiple remixes and remakes by other producers.<br><br>It was also used in the 2010 season 2 premiere episode of NCIS: LA and a version of the track was re-orchestrated with a choir and full orchestra for The Lord of the Rings: The Two Towers trailer.<br><br>It was arranged by Simone Benyacar, Daniel Nielsen, and Veigar Margeirsson.<br><br>The orchestrated version was used in various trailers and video games. Clint Mansell commented that the piece had "gone on to have a life of its own".',
      descriptionRu: '«Вечный свет» — саундтрек к фильму Даррена Аронофски «Реквием по мечте» (экранизация романа Хьюберта Селби). Выпущен в 2000 году. Композитором является Клинт Мэнселл.<br><br>Эта музыка стала культовым хитом, так как саундтрек был оценён по достоинству многими музыкантами и получил широкое признание, а композиция «Lux Aeterna» и её реаранжированная версия «Requiem for a Tower» впоследствии были использованы в различных формах массовой информации (трейлеры и тизеры фильмов и сериалов, видеоигры, телепередачи, рекламные ролики и другие медиа).<br><br>Саундтрек Requiem for a Dream закрепил свою популярность после издания альбома Requiem for a Dream: Remixed, содержавшего новые ремиксы, созданные Полом Окенфолдом, Джошем Уинком, Джэгзом Кунером, Delerium и многими другими.',
      image: 'url(../../assets/img/requiem.webp',
      audio: '../../assets/sound/requiem.mp3',
      duration: '00:30',
      wikiEn: 'https://en.wikipedia.org/wiki/Lux_Aeterna_(Mansell)',
      wikiRu: 'https://ru.wikipedia.org/wiki/Requiem_for_a_Dream_(%D1%81%D0%B0%D1%83%D0%BD%D0%B4%D1%82%D1%80%D0%B5%D0%BA)',
      youtube: 'https://youtu.be/oc3Cq89P97Y'
    }
  ],
  [
    {
      id: 1,
      nameEn: 'Titanic',
      nameRu: 'Титаник',
      trackEn: 'My Heart Will Go On',
      trackRu: 'Моё сердце будет биться',
      authorEn: 'Céline Dion',
      authorRu: 'Селин Дион',
      descriptionEn: '"My Heart Will Go On" is a 1997 song recorded by Canadian singer Celine Dion.<br><br>The song serves as the main soundtrack to James Cameron\'s blockbuster film Titanic, based on an account of the transatlantic ocean liner of the same name which sank in 1912 after colliding with an iceberg in the North Atlantic Ocean.<br><br>The song\'s music was composed by James Horner, its lyrics were written by Will Jennings, while the production was handled by Walter Afanasieff, Horner and Simon Franglen.',
      descriptionRu: '"Моё сердце будет биться дальше" — песня канадской певицы Селин Дион, главная тема к фильму Джеймса Кэмерона "Титаник".<br><br>Автор музыки — Джеймс Хорнер, слова написал Уилл Дженнингс, продюсером стал Уолтер Афанасьефф. Композиция была выпущена на альбоме Дион Let\'s Talk About Love в 1997 году, она возглавила чарты по всему миру, включая США, Великобританию и Австралию.<br><br>Релиз сингла состоялся в Австралии и Германии 8 декабря 1997 года и в январе и феврале 1998 года в остальном мире, композиция стала одной из самых популярных за всю историю музыки и самой продаваемой в мире песней 1998 года.емыми в более чем 18 миллионов копий, это второй самый продаваемый сингл на физическом носителе в истории музыки и один из самых продаваемых синглов всех времен.<br><br>Он также был самым продаваемым синглом в мире за 1998 год. Песня также была включена в список "Песни века" Американской ассоциацией звукозаписывающей индустрии и Национальным фондом искусств.<br><br>Дион исполнила песню в честь 20-летия фильма "Титаник" на церемонии вручения премии Billboard Music Awards 21 мая 2017 года.',
      image: 'url(../../assets/img/titanic.webp',
      audio: '../../assets/sound/titanic.mp3',
      duration: '00:17',
      wikiEn: 'https://en.wikipedia.org/wiki/My_Heart_Will_Go_On',
      wikiRu: 'https://ru.wikipedia.org/wiki/My_Heart_Will_Go_On',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 2,
      nameEn: 'Star Wars',
      nameRu: 'Звёздные войны',
      trackEn: 'The Imperial March',
      trackRu: 'Имперский марш',
      authorEn: 'John Williams',
      authorRu: 'Джон Уильямс',
      descriptionEn: '"The Imperial March (Darth Vader\'s Theme)" is a musical theme present in the Star Wars franchise. It was composed by John Williams for the film The Empire Strikes Back.<br><br>Together with "Yoda\'s Theme", "The Imperial March" was premiered on April 29, 1980, three weeks before the opening of the film, on the occasion of John Williams first concert as official conductor-in-residence of the Boston Pops Orchestra.<br><br>One of the best known symphonic movie themes, it is used as a leitmotif throughout the Star Wars franchise.',
      descriptionRu: '«Имперский марш (Тема Дарта Вейдера)» — музыкальная тема, представленная во франшизе «Звёздные войны». Она была написана Джоном Уильямсом для фильма «Звёздные войны. Эпизод V: Империя наносит ответный удар».<br><br>Вместе с «темой Йоды» премьера «Имперского марша» состоялась 29 апреля 1980 года, за три недели до открытия фильма, по случаю первого концерта Джона Уильямса в качестве официального дирижёра Boston Pops Orchestra.<br><br>Одна из самых известных тем симфонического кино, это пример лейтмотива, повторяющейся темы, связанной с персонажами или событиями в драме.',
      image: 'url(../../assets/img/star-wars.webp',
      audio: '../../assets/sound/star-wars.mp3',
      duration: '00:21',
      wikiEn: 'https://en.wikipedia.org/wiki/The_Imperial_March',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%98%D0%BC%D0%BF%D0%B5%D1%80%D1%81%D0%BA%D0%B8%D0%B9_%D0%BC%D0%B0%D1%80%D1%88',
      youtube: 'https://youtu.be/vsMWVW4xtwI'
    },
    {
      id: 3,
      nameEn: 'The Godfather',
      nameRu: 'Крёстный отец',
      trackEn: 'Speak Softly Love',
      trackRu: 'Говори тихо, любовь моя',
      authorEn: 'Nino Rota',
      authorRu: 'Нино Рота',
      descriptionEn: '"Love Theme from The Godfather" is an instrumental theme from the 1972 film The Godfather, composed by Nino Rota.<br><br>The piece was lyricized in English by Larry Kusik into "Speak Softly, Love", a popular song released in 1972.<br><br>The highest-charting rendition of either version was by vocalist Andy Williams, who took "Speak Softly Love" to number 34 on Billboard magazine\'s Hot 100 and number seven on its Easy Listening chart.',
      descriptionRu: '«Говори тихо, любовь моя» — песня композитора Нино Рота на слова Ларри Кьюзика, впервые прозвучавшая в инструментальном исполнении в фильме «Крёстный отец» (1972).<br><br>Наибольшей популярности песня достигла в исполнении Энди Уильямса, поднявшись до 43-й позиции в Billboard Hot 100 и седьмого места в хит-параде Easy Listening.<br><br>Позднее эту песню исполняли также Эл Мартино, София Ротару («Скажи, що любиш», 1975), Бобби Винтон, Муслим Магомаев, Олег Погудин и другие певцы.',
      image: 'url(../../assets/img/godfather.webp',
      audio: '../../assets/sound/godfather.mp3',
      duration: '00:15',
      wikiEn: 'https://en.wikipedia.org/wiki/Love_Theme_from_The_Godfather',
      wikiRu: 'https://ru.wikipedia.org/wiki/Speak_Softly_Love',
      youtube: 'https://youtu.be/zbSMCyJkUmI'
    },
    {
      id: 4,
      nameEn: 'Pulp Fiction',
      nameRu: 'Криминальное чтиво',
      trackEn: 'You Never Can Tell',
      trackRu: 'Никак не угадать',
      authorEn: 'Chuck Berry',
      authorRu: 'Чак Берри',
      descriptionEn: '"You Never Can Tell", also known as "C\'est La Vie" or "Teenage Wedding", is a song written by Chuck Berry.<br><br>It was composed in the early 1960s while Berry was in federal prison for violating the Mann Act. Released in 1964 on the album St. Louis to Liverpool and the follow-up single to Berry\'s final Top Ten hit of the 1960s: "No Particular Place to Go", "You Never Can Tell" reached number 14, becoming Berry\'s final Top 40 hit until "My Ding-a-Ling", a number 1 in October 1972.<br><br>The song became popular again after the 1994 release of the film Pulp Fiction, directed and co-written by Quentin Tarantino. The music was played for a "Twist contest" in which Vincent Vega (John Travolta) and Mia Wallace (Uma Thurman) competed (and were the only contestants shown in the film). The music added an evocative element of sound to the narrative and Tarantino said that the song\'s lyrics of "Pierre" and "Mademoiselle" gave the scene a "uniquely \'50s French New Wave dance sequence feel".',
      descriptionRu: '«You Never Can Tell» — песня американского рок-музыканта Чака Берри, вышедшая на сингле в 1964 году.<br><br>Песня была написана в начале шестидесятых, в то время, когда Чак Берри находился в тюрьме. You Never Can Tell вошла в альбом Берри St. Louis to Liverpool 1964 года, изданный на лейбле Chess Records, как сингл она дошла до 14 места в рейтинге журнала Billboard.<br><br>Вторая волна популярности You Never Can Tell началась после выхода на экраны фильма культового американского режиссёра Квентина Тарантино «Криминальное чтиво» (1994), в саундтрек которого вошла песня. В одном из эпизодов фильма гангстер Винсент Вега (Джон Траволта) и жена его босса Миа Уоллес (Ума Турман) танцуют твист под песню Чака Берри. По словам Тарантино, лирика песни придаёт этой сцене особую атмосферу Французской новой волны.',
      image: 'url(../../assets/img/pulp-fiction.webp',
      audio: '../../assets/sound/pulp-fiction.mp3',
      duration: '00:26',
      wikiEn: 'https://en.wikipedia.org/wiki/You_Never_Can_Tell_(song)',
      wikiRu: 'https://ru.wikipedia.org/wiki/You_Never_Can_Tell',
      youtube: 'https://youtu.be/WSLMN6g_Od4'
    },{
      id: 5,
      nameEn: 'The Bodyguard',
      nameRu: 'Телохранитель',
      trackEn: 'I Will Always Love You',
      trackRu: 'Я всегда буду любить тебя',
      authorEn: 'Whitney Houston',
      authorRu: 'Уитни Хьюстон',
      descriptionEn: '"I Will Always Love You" is a song written and originally recorded in 1973 by American singer-songwriter Dolly Parton.<br><br>Whitney Houston recorded a soul-ballad arrangement of the song for the 1992 film The Bodyguard. Houston\'s version peaked at number one on the Billboard Hot 100 for a then-record-breaking 14 weeks. The single was certified Diamond by the RIAA, making Houston\'s first Diamond single, the third female artist who had both a Diamond single and a Diamond album, and becoming the best-selling single by a woman in the U.S.<br><br>The song was a global success, topping the charts in almost all countries. With 20 million copies sold it became the best-selling single of all time by a female solo artist.<br><br>Houston won the Grammy Award for Record of the Year in 1994 for "I Will Always Love You". The song has been recorded by many other artists including Linda Ronstadt, John Doe, Amber Riley, LeAnn Rimes and Sarah Washington, whose dance version reached number 12 on the UK Singles Chart.',
      descriptionRu: '«Я всегда буду любить тебя» — сингл американской кантри-певицы Долли Партон, выпущенный в 1974 году на лейбле RCA Records.<br><br>Однако с наибольшим успехом исполнила этот хит другая певица — Уитни Хьюстон. Её соул-версия, включённая в саундтрек к фильму «Телохранитель» 1992 года, была удостоена множества наград, в том числе «Грэмми» за лучшую запись года и лучший женский поп-вокал.<br><br>Критики были впечатлены тем, как грустная любовная песня благодаря мощному вокалу и влиянию госпела превратилась в неистовое воплощение драмы покинутой женщины.',
      image: 'url(../../assets/img/bodyguard.webp',
      audio: '../../assets/sound/bodyguard.mp3',
      duration: '00:47',
      wikiEn: 'https://en.wikipedia.org/wiki/I_Will_Always_Love_You',
      wikiRu: 'https://ru.wikipedia.org/wiki/I_Will_Always_Love_You',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 6,
      nameEn: 'Requiem for a Dream',
      nameRu: 'Реквием по мечте',
      trackEn: 'Lux Aeterna',
      trackRu: 'Вечный свет',
      authorEn: 'Clint Mansell',
      authorRu: 'Клинт Мэнселл',
      descriptionEn: '"Lux Aeterna" is an orchestral composition by Clint Mansell. It forms a leitmotif in the 2000 film Requiem for a Dream, and is the penultimate piece in the movie\'s soundtrack.<br><br>The popularity of the piece led to its use in popular culture outside the film, in film and teaser trailers, such as Sunshine and Waking Madison, and multiple remixes and remakes by other producers.<br><br>It was also used in the 2010 season 2 premiere episode of NCIS: LA and a version of the track was re-orchestrated with a choir and full orchestra for The Lord of the Rings: The Two Towers trailer.<br><br>It was arranged by Simone Benyacar, Daniel Nielsen, and Veigar Margeirsson.<br><br>The orchestrated version was used in various trailers and video games. Clint Mansell commented that the piece had "gone on to have a life of its own".',
      descriptionRu: '«Вечный свет» — саундтрек к фильму Даррена Аронофски «Реквием по мечте» (экранизация романа Хьюберта Селби). Выпущен в 2000 году. Композитором является Клинт Мэнселл.<br><br>Эта музыка стала культовым хитом, так как саундтрек был оценён по достоинству многими музыкантами и получил широкое признание, а композиция «Lux Aeterna» и её реаранжированная версия «Requiem for a Tower» впоследствии были использованы в различных формах массовой информации (трейлеры и тизеры фильмов и сериалов, видеоигры, телепередачи, рекламные ролики и другие медиа).<br><br>Саундтрек Requiem for a Dream закрепил свою популярность после издания альбома Requiem for a Dream: Remixed, содержавшего новые ремиксы, созданные Полом Окенфолдом, Джошем Уинком, Джэгзом Кунером, Delerium и многими другими.',
      image: 'url(../../assets/img/requiem.webp',
      audio: '../../assets/sound/requiem.mp3',
      duration: '00:30',
      wikiEn: 'https://en.wikipedia.org/wiki/Lux_Aeterna_(Mansell)',
      wikiRu: 'https://ru.wikipedia.org/wiki/Requiem_for_a_Dream_(%D1%81%D0%B0%D1%83%D0%BD%D0%B4%D1%82%D1%80%D0%B5%D0%BA)',
      youtube: 'https://youtu.be/oc3Cq89P97Y'
    }
  ]
];

export default soundtracksData;