const soundtracksData = [
  [
    {
      id: 1,
      nameEn: 'Titanic',
      nameRu: 'Титаник',
      trackEn: 'My Heart Will Go On',
      trackRu: 'Моё сердце будет биться',
      authorEn: 'Céline Dion',
      authorRu: 'Селин Дион',
      descriptionEn: '"My Heart Will Go On" is a 1997 song recorded by Canadian singer Celine Dion.<br><br>The song serves as the main soundtrack to James Cameron\'s blockbuster film Titanic, based on an account of the transatlantic ocean liner of the same name which sank in 1912 after colliding with an iceberg in the North Atlantic Ocean.<br><br>The song\'s music was composed by James Horner, its lyrics were written by Will Jennings, while the production was handled by Walter Afanasieff, Horner and Simon Franglen.',
      descriptionRu: '"Моё сердце будет биться дальше" — песня канадской певицы Селин Дион, главная тема к фильму Джеймса Кэмерона "Титаник".<br><br>Автор музыки — Джеймс Хорнер, слова написал Уилл Дженнингс, продюсером стал Уолтер Афанасьефф. Композиция была выпущена на альбоме Дион Let\'s Talk About Love в 1997 году, она возглавила чарты по всему миру, включая США, Великобританию и Австралию.<br><br>Релиз сингла состоялся в Австралии и Германии 8 декабря 1997 года и в январе и феврале 1998 года в остальном мире, композиция стала одной из самых популярных за всю историю музыки и самой продаваемой в мире песней 1998 года.емыми в более чем 18 миллионов копий, это второй самый продаваемый сингл на физическом носителе в истории музыки и один из самых продаваемых синглов всех времен.<br><br>Он также был самым продаваемым синглом в мире за 1998 год. Песня также была включена в список "Песни века" Американской ассоциацией звукозаписывающей индустрии и Национальным фондом искусств.<br><br>Дион исполнила песню в честь 20-летия фильма "Титаник" на церемонии вручения премии Billboard Music Awards 21 мая 2017 года.',
      image: 'url(../../assets/img/titanic.webp',
      audio: '../../assets/sound/titanic.mp3',
      duration: '00:17',
      wikiEn: 'https://en.wikipedia.org/wiki/My_Heart_Will_Go_On',
      wikiRu: 'https://ru.wikipedia.org/wiki/My_Heart_Will_Go_On',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 2,
      nameEn: 'Star Wars',
      nameRu: 'Звёздные войны',
      trackEn: 'The Imperial March',
      trackRu: 'Имперский марш',
      authorEn: 'John Williams',
      authorRu: 'Джон Уильямс',
      descriptionEn: '"The Imperial March (Darth Vader\'s Theme)" is a musical theme present in the Star Wars franchise. It was composed by John Williams for the film The Empire Strikes Back.<br><br>Together with "Yoda\'s Theme", "The Imperial March" was premiered on April 29, 1980, three weeks before the opening of the film, on the occasion of John Williams first concert as official conductor-in-residence of the Boston Pops Orchestra.<br><br>One of the best known symphonic movie themes, it is used as a leitmotif throughout the Star Wars franchise.',
      descriptionRu: '«Имперский марш (Тема Дарта Вейдера)» — музыкальная тема, представленная во франшизе «Звёздные войны». Она была написана Джоном Уильямсом для фильма «Звёздные войны. Эпизод V: Империя наносит ответный удар».<br><br>Вместе с «темой Йоды» премьера «Имперского марша» состоялась 29 апреля 1980 года, за три недели до открытия фильма, по случаю первого концерта Джона Уильямса в качестве официального дирижёра Boston Pops Orchestra.<br><br>Одна из самых известных тем симфонического кино, это пример лейтмотива, повторяющейся темы, связанной с персонажами или событиями в драме.',
      image: 'url(../../assets/img/star-wars.webp',
      audio: '../../assets/sound/star-wars.mp3',
      duration: '00:21',
      wikiEn: 'https://en.wikipedia.org/wiki/The_Imperial_March',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%98%D0%BC%D0%BF%D0%B5%D1%80%D1%81%D0%BA%D0%B8%D0%B9_%D0%BC%D0%B0%D1%80%D1%88',
      youtube: 'https://youtu.be/vsMWVW4xtwI'
    },
    {
      id: 3,
      nameEn: 'The Godfather',
      nameRu: 'Крёстный отец',
      trackEn: 'Speak Softly Love',
      trackRu: 'Говори тихо, любовь моя',
      authorEn: 'Nino Rota',
      authorRu: 'Нино Рота',
      descriptionEn: '"Love Theme from The Godfather" is an instrumental theme from the 1972 film The Godfather, composed by Nino Rota.<br><br>The piece was lyricized in English by Larry Kusik into "Speak Softly, Love", a popular song released in 1972.<br><br>The highest-charting rendition of either version was by vocalist Andy Williams, who took "Speak Softly Love" to number 34 on Billboard magazine\'s Hot 100 and number seven on its Easy Listening chart.',
      descriptionRu: '«Говори тихо, любовь моя» — песня композитора Нино Рота на слова Ларри Кьюзика, впервые прозвучавшая в инструментальном исполнении в фильме «Крёстный отец» (1972).<br><br>Наибольшей популярности песня достигла в исполнении Энди Уильямса, поднявшись до 43-й позиции в Billboard Hot 100 и седьмого места в хит-параде Easy Listening.<br><br>Позднее эту песню исполняли также Эл Мартино, София Ротару («Скажи, що любиш», 1975), Бобби Винтон, Муслим Магомаев, Олег Погудин и другие певцы.',
      image: 'url(../../assets/img/godfather.webp',
      audio: '../../assets/sound/godfather.mp3',
      duration: '00:15',
      wikiEn: 'https://en.wikipedia.org/wiki/Love_Theme_from_The_Godfather',
      wikiRu: 'https://ru.wikipedia.org/wiki/Speak_Softly_Love',
      youtube: 'https://youtu.be/zbSMCyJkUmI'
    },
    {
      id: 4,
      nameEn: 'Pulp Fiction',
      nameRu: 'Криминальное чтиво',
      trackEn: 'You Never Can Tell',
      trackRu: 'Никак не угадать',
      authorEn: 'Chuck Berry',
      authorRu: 'Чак Берри',
      descriptionEn: '"You Never Can Tell", also known as "C\'est La Vie" or "Teenage Wedding", is a song written by Chuck Berry.<br><br>It was composed in the early 1960s while Berry was in federal prison for violating the Mann Act. Released in 1964 on the album St. Louis to Liverpool and the follow-up single to Berry\'s final Top Ten hit of the 1960s: "No Particular Place to Go", "You Never Can Tell" reached number 14, becoming Berry\'s final Top 40 hit until "My Ding-a-Ling", a number 1 in October 1972.<br><br>The song became popular again after the 1994 release of the film Pulp Fiction, directed and co-written by Quentin Tarantino. The music was played for a "Twist contest" in which Vincent Vega (John Travolta) and Mia Wallace (Uma Thurman) competed (and were the only contestants shown in the film). The music added an evocative element of sound to the narrative and Tarantino said that the song\'s lyrics of "Pierre" and "Mademoiselle" gave the scene a "uniquely \'50s French New Wave dance sequence feel".',
      descriptionRu: '«You Never Can Tell» — песня американского рок-музыканта Чака Берри, вышедшая на сингле в 1964 году.<br><br>Песня была написана в начале шестидесятых, в то время, когда Чак Берри находился в тюрьме. You Never Can Tell вошла в альбом Берри St. Louis to Liverpool 1964 года, изданный на лейбле Chess Records, как сингл она дошла до 14 места в рейтинге журнала Billboard.<br><br>Вторая волна популярности You Never Can Tell началась после выхода на экраны фильма культового американского режиссёра Квентина Тарантино «Криминальное чтиво» (1994), в саундтрек которого вошла песня. В одном из эпизодов фильма гангстер Винсент Вега (Джон Траволта) и жена его босса Миа Уоллес (Ума Турман) танцуют твист под песню Чака Берри. По словам Тарантино, лирика песни придаёт этой сцене особую атмосферу Французской новой волны.',
      image: 'url(../../assets/img/pulp-fiction.webp',
      audio: '../../assets/sound/pulp-fiction.mp3',
      duration: '00:26',
      wikiEn: 'https://en.wikipedia.org/wiki/You_Never_Can_Tell_(song)',
      wikiRu: 'https://ru.wikipedia.org/wiki/You_Never_Can_Tell',
      youtube: 'https://youtu.be/WSLMN6g_Od4'
    },{
      id: 5,
      nameEn: 'The Bodyguard',
      nameRu: 'Телохранитель',
      trackEn: 'I Will Always Love You',
      trackRu: 'Я всегда буду любить тебя',
      authorEn: 'Whitney Houston',
      authorRu: 'Уитни Хьюстон',
      descriptionEn: '"I Will Always Love You" is a song written and originally recorded in 1973 by American singer-songwriter Dolly Parton.<br><br>Whitney Houston recorded a soul-ballad arrangement of the song for the 1992 film The Bodyguard. Houston\'s version peaked at number one on the Billboard Hot 100 for a then-record-breaking 14 weeks. The single was certified Diamond by the RIAA, making Houston\'s first Diamond single, the third female artist who had both a Diamond single and a Diamond album, and becoming the best-selling single by a woman in the U.S.<br><br>The song was a global success, topping the charts in almost all countries. With 20 million copies sold it became the best-selling single of all time by a female solo artist.<br><br>Houston won the Grammy Award for Record of the Year in 1994 for "I Will Always Love You". The song has been recorded by many other artists including Linda Ronstadt, John Doe, Amber Riley, LeAnn Rimes and Sarah Washington, whose dance version reached number 12 on the UK Singles Chart.',
      descriptionRu: '«Я всегда буду любить тебя» — сингл американской кантри-певицы Долли Партон, выпущенный в 1974 году на лейбле RCA Records.<br><br>Однако с наибольшим успехом исполнила этот хит другая певица — Уитни Хьюстон. Её соул-версия, включённая в саундтрек к фильму «Телохранитель» 1992 года, была удостоена множества наград, в том числе «Грэмми» за лучшую запись года и лучший женский поп-вокал.<br><br>Критики были впечатлены тем, как грустная любовная песня благодаря мощному вокалу и влиянию госпела превратилась в неистовое воплощение драмы покинутой женщины.',
      image: 'url(../../assets/img/bodyguard.webp',
      audio: '../../assets/sound/bodyguard.mp3',
      duration: '00:47',
      wikiEn: 'https://en.wikipedia.org/wiki/I_Will_Always_Love_You',
      wikiRu: 'https://ru.wikipedia.org/wiki/I_Will_Always_Love_You',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 6,
      nameEn: 'Requiem for a Dream',
      nameRu: 'Реквием по мечте',
      trackEn: 'Lux Aeterna',
      trackRu: 'Вечный свет',
      authorEn: 'Clint Mansell',
      authorRu: 'Клинт Мэнселл',
      descriptionEn: '"Lux Aeterna" is an orchestral composition by Clint Mansell. It forms a leitmotif in the 2000 film Requiem for a Dream, and is the penultimate piece in the movie\'s soundtrack.<br><br>The popularity of the piece led to its use in popular culture outside the film, in film and teaser trailers, such as Sunshine and Waking Madison, and multiple remixes and remakes by other producers.<br><br>It was also used in the 2010 season 2 premiere episode of NCIS: LA and a version of the track was re-orchestrated with a choir and full orchestra for The Lord of the Rings: The Two Towers trailer.<br><br>It was arranged by Simone Benyacar, Daniel Nielsen, and Veigar Margeirsson.<br><br>The orchestrated version was used in various trailers and video games. Clint Mansell commented that the piece had "gone on to have a life of its own".',
      descriptionRu: '«Вечный свет» — саундтрек к фильму Даррена Аронофски «Реквием по мечте» (экранизация романа Хьюберта Селби). Выпущен в 2000 году. Композитором является Клинт Мэнселл.<br><br>Эта музыка стала культовым хитом, так как саундтрек был оценён по достоинству многими музыкантами и получил широкое признание, а композиция «Lux Aeterna» и её реаранжированная версия «Requiem for a Tower» впоследствии были использованы в различных формах массовой информации (трейлеры и тизеры фильмов и сериалов, видеоигры, телепередачи, рекламные ролики и другие медиа).<br><br>Саундтрек Requiem for a Dream закрепил свою популярность после издания альбома Requiem for a Dream: Remixed, содержавшего новые ремиксы, созданные Полом Окенфолдом, Джошем Уинком, Джэгзом Кунером, Delerium и многими другими.',
      image: 'url(../../assets/img/requiem.webp',
      audio: '../../assets/sound/requiem.mp3',
      duration: '00:30',
      wikiEn: 'https://en.wikipedia.org/wiki/Lux_Aeterna_(Mansell)',
      wikiRu: 'https://ru.wikipedia.org/wiki/Requiem_for_a_Dream_(%D1%81%D0%B0%D1%83%D0%BD%D0%B4%D1%82%D1%80%D0%B5%D0%BA)',
      youtube: 'https://youtu.be/oc3Cq89P97Y'
    }
  ],
  [
    {
      id: 1,
      nameEn: 'Friends',
      nameRu: 'Друзья',
      trackEn: 'I\'ll Be There for You',
      trackRu: 'Я буду рядом с тобой',
      authorEn: 'The Rembrandts',
      authorRu: 'Рембрандты',
      descriptionEn: '"I\'ll Be There for You" is a song by American pop rock duo the Rembrandts. The song was written by David Crane, Marta Kauffman, Michael Skloff, and Allee Willis as the main theme song to the NBC sitcom Friends, which was broadcast from 1994 to 2004.<br><br>American rock band R.E.M. was originally asked to allow one of their songs to be used for the Friends theme, but they turned the opportunity down.<br><br>"I\'ll Be There for You" was subsequently written and Warner Bros. Television selected the only available band on Warner Bros. Records to record it: the Rembrandts. In 1995, after a Nashville radio station brought the song to mainstream popularity, Rembrandts members Danny Wilde and Phil Sōlem expanded the theme song with two new verses and included this version on their third studio album, L.P. (1995).<br><br>The extended version of the song was released to US radio on May 23, 1995, and was issued in the United Kingdom on August 7, 1995, as the first single from L.P. Following the song\'s release, it reached the top 10 in Australia, New Zealand and Norway, as well as in Ireland and the United Kingdom in both 1995 and 1997.<br><br>In Canada, the song reached number one for five weeks and was the most successful single of 1995, while in the United States, the song reached number 17 on the Billboard Hot 100 and topped the Billboard Hot 100 Airplay chart for eight weeks.',
      descriptionRu: '«Я буду рядом с тобой» — песня американского дуэта The Rembrandts, наиболее известная как музыкальная тема вступительной заставки к ситкому «Друзья».<br><br>Она также была выпущена как первый сингл с третьего студийного альбома коллектива «L.P.», достигнув топ-10 чартов Австралии, Новой Зеландии, Норвегии, Ирландии и Великобритании. Песня заняла первое место в чарте Канады, удерживая позицию в течение пяти недель, где также стала самым продаваемым синглом 1995 года.<br><br>Сингл также достиг семнадцатого места в американском хит-параде Billboard Hot 100 и на протяжении восьми недель возглавлял чарт Hot 100 Airplay.',
      image: 'url(../../assets/img/friends.webp',
      audio: '../../assets/sound/friends.mp3',
      duration: '00:18',
      wikiEn: 'https://en.wikipedia.org/wiki/I%27ll_Be_There_for_You_(The_Rembrandts_song)',
      wikiRu: 'https://ru.wikipedia.org/wiki/I%E2%80%99ll_Be_There_for_You_(%D0%BF%D0%B5%D1%81%D0%BD%D1%8F_The_Rembrandts)',
      youtube: 'https://youtu.be/RIjTq_OdFvo'
    },
    {
      id: 2,
      nameEn: 'Game of Thrones',
      nameRu: 'Игра престолов',
      trackEn: 'Game of Thrones Main Title',
      trackRu: 'Игра престолов главная тема',
      authorEn: 'Ramin Djawadi',
      authorRu: 'Рамин Джавади',
      descriptionEn: 'The music for the fantasy TV series Game of Thrones is composed by Ramin Djawadi. The music is primarily non-diegetic and instrumental with occasional vocal performances, and is created to support musically the characters and plots of the show.<br><br>It features various themes, the most prominent being the "main title theme" that accompanies the series\' title sequence. In every season, a soundtrack album was released.<br><br>The music for the show has won a number of awards, including a Primetime Emmy Award for Outstanding Music Composition for a Series in 2018 and 2019.<br><br>A series of concerts which featured Game of Thrones music, Game of Thrones Live Concert Experience with composer Ramin Djawadi, took place in 2017–2018. First to be performed in Saint Paul, Minnesota, it then went on to tour across the United States, Canada and Europe. This is followed by a world tour starting May 2018 in Madrid.',
      descriptionRu: 'Game of Thrones — саундтрек к американскому сериалу канала HBO Игра престолов. Над ним работал немецкий композитор Рамин Джавади, пластинка к первому сезону была выпущена лейблом Varèse Sarabande в июне 2011 года.<br><br>Музыка альбома инструментальная, кроме этого есть заглавная тема сериала — Main Title.<br><br>Сперва над саундтреком Игры престолов должен был работать Стивен Варбек, но 2 февраля 2011 года он покинул проект. Его заменил Рамин Джавади.<br><br>Альбом вместе с цифровым буклетом появился в iTunes 14 июня 2011 года. Релиз компакт диска состоялся 28 июня.',
      image: 'url(../../assets/img/game-of-thrones.webp',
      audio: '../../assets/sound/game-of-thrones.mp3',
      duration: '00:15',
      wikiEn: 'https://en.wikipedia.org/wiki/Music_of_Game_of_Thrones',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%98%D0%B3%D1%80%D0%B0_%D0%BF%D1%80%D0%B5%D1%81%D1%82%D0%BE%D0%BB%D0%BE%D0%B2_(%D1%81%D0%B0%D1%83%D0%BD%D0%B4%D1%82%D1%80%D0%B5%D0%BA)',
      youtube: 'https://youtu.be/TZE9gVF1QbA'
    },
    {
      id: 3,
      nameEn: 'Santa Barbara',
      nameRu: 'Санта-Барбара',
      trackEn: 'Santa-Barbara Main Title Theme',
      trackRu: 'Главная тема Санта-Барбара',
      authorEn: 'Joe Harnell',
      authorRu: 'Джо Харнелл',
      descriptionEn: 'Santa Barbara is an American television soap opera that aired on NBC from July 30, 1984, to January 15, 1993. The show revolves around the eventful lives of the wealthy Capwell family of Santa Barbara, California.<br><br>The music for "Santa Barbara" was composed by Joe Harnell (1924-2005), who by that time already had vast experience as an arranger and composer.<br><br>Other prominent families featured on the soap were the rival Lockridge family, and the more modest Andrade and Perkins families.<br><br>The serial was produced by Dobson Productions and New World Television, which also served as distributor for the show in international markets. Santa Barbara was the first series for New World Television.<br><br>Santa Barbara aired in the United States at 3:00 PM Eastern (2:00 PM Central) on NBC in the same time slot as General Hospital on ABC and Guiding Light on CBS and right after Another World. Santa Barbara aired in over 40 countries around the world. It became the longest-running television series in Russia, airing there from 1992 to 2002.',
      descriptionRu: '«Санта-Барбара» — американская дневная мыльная опера, транслировавшаяся в США с 1984 по 1993 год на телеканале NBC. Первый сериал, показанный на территории СНГ после распада СССР, один из самых популярных и самый длинный из когда-либо транслировавшихся в России.<br><br>Всего было снято 2137 серий. Действие происходит в городе Санта-Барбара (Калифорния). Сериал рассказывает о жизни богатой семьи Кэпвеллов из города Санта-Барбара.<br><br>Музыкальную заставку к «Санта-Барбаре» сочинил Джо Харнелл (1924-2005), к тому времени уже имевший огромный опыт аранжировщика и композитора.',
      image: 'url(../../assets/img/santa-barbara.webp',
      audio: '../../assets/sound/santa-barbara.mp3',
      duration: '00:34',
      wikiEn: 'https://en.wikipedia.org/wiki/Santa_Barbara_(TV_series)',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%A1%D0%B0%D0%BD%D1%82%D0%B0-%D0%91%D0%B0%D1%80%D0%B1%D0%B0%D1%80%D0%B0_(%D1%82%D0%B5%D0%BB%D0%B5%D1%81%D0%B5%D1%80%D0%B8%D0%B0%D0%BB)',
      youtube: 'https://youtu.be/HTjjNozVy5w'
    },
    {
      id: 4,
      nameEn: 'Narcos',
      nameRu: 'Нарко',
      trackEn: 'Tuyo',
      trackRu: 'Твой',
      authorEn: 'Rodrigo Amarante',
      authorRu: 'Родриго Амаранте',
      descriptionEn: 'Tuyo is a bolero written and composed by Brazilian singer-songwriter Rodrigo Amarante for Narcos\' opening theme.<br><br>Amarante wrote and vocalized the Spanish-language song, "Tuyo" ("Yours"), as the opening theme for the Netflix Original series Narcos.<br><br>He was inspired by the thought of what kind of music Pablo Escobar\'s mother would have listened to when raising her son.<br><br>The song debuted at No. 6 on the Latin Pop Digital Songs around the 2015 series premiere and was nominated for a Primetime Emmy Award for Outstanding Main Title Theme Music.',
      descriptionRu: '«Твой» — это болеро, написанное бразильским певцом и автором песен Родриго Амаранте для вступительной темы Narcos.<br><br>Амаранте написал и озвучил испаноязычную песню "Tuyo" в качестве вступительной темы для сериала Netflix Original Narcos.<br><br>Его вдохновила мысль о том, какую музыку слушала бы мать Пабло Эскобара, воспитывая сына.<br><br>Песня дебютировала на 6 месте в Latin Pop Digital Songs во время премьеры сериала 2015 года и была номинирована на премию Primetime Emmy Award за выдающуюся музыкальную тему для главной заставки сериала.',
      image: 'url(../../assets/img/narcos.webp',
      audio: '../../assets/sound/narcos.mp3',
      duration: '00:26',
      wikiEn: 'https://en.wikipedia.org/wiki/Tuyo',
      wikiRu: '',
      youtube: 'https://youtu.be/PtJ6yAGjsIs'
    },{
      id: 5,
      nameEn: 'The X-Files',
      nameRu: 'Секретные материалы',
      trackEn: 'Materia Primoris',
      trackRu: 'Первичная материя',
      authorEn: 'Mark Snow',
      authorRu: 'Марк Сноу',
      descriptionEn: '"The X-Files" is an instrumental written and produced by American film and television composer Mark Snow. On its parent album, The Truth and the Light: Music from the X-Files, the track is titled "Materia Primoris".<br><br>It is a remixed version of the original theme Snow composed for the science fiction television series The X-Files in 1993.<br><br>The composition was released as a single in 1996 and achieved chart success, particularly in France, where it reached number one on the singles chart. The composition has since been covered by many artists, including DJ Dado and Triple X; DJ Dado\'s version was a major hit in Europe while Triple X\'s version reached number two in Australia.',
      descriptionRu: 'Автором музыки к «Секретным материалам» стал композитор Марк Сноу. Он начал работу над проектом в 1993 году после того, как к нему обратился исполнительный продюсер телесериала Крис Картер.<br><br>Сноу стал одним из дюжины кандидатов, которых порекомендовали на эту позицию. Через несколько недель после первой встречи Картер сообщил Сноу, что ему доверено написание музыки к пилотной серии «Секретных материалов».<br><br>Успех сериала привёл к тому, что Сноу и Картер продолжили работу. Первый компакт-диск с музыкой к сериалу The Truth and The Light вышел через два после начала работы. Помимо музыкальных композиций он содержал фрагменты диалогов из фильма.<br><br>Основной темой сериала стала композиция «Materia Primoris». Композиция получила всемирную известность и занимала первое место в хит-парадах Франции и Англии.',
      image: 'url(../../assets/img/x-files.webp',
      audio: '../../assets/sound/x-files.mp3',
      duration: '00:47',
      wikiEn: 'https://en.wikipedia.org/wiki/The_X-Files_(composition)',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%A1%D0%B5%D0%BA%D1%80%D0%B5%D1%82%D0%BD%D1%8B%D0%B5_%D0%BC%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%B0%D0%BB%D1%8B_(%D1%81%D0%B0%D1%83%D0%BD%D0%B4%D1%82%D1%80%D0%B5%D0%BA%D0%B8)',
      youtube: 'https://youtu.be/Qz2wnSVeITg'
    },
    {
      id: 6,
      nameEn: 'Sex And The City',
      nameRu: 'Секс в большом городе',
      trackEn: 'Sex And The City Main Theme',
      trackRu: 'Секс в большом городе',
      authorEn: 'Douglas J. Cuomo',
      authorRu: 'Дуглас Дж. Куомо',
      descriptionEn: '"Sex and the City" is an American romantic comedy-drama television series created by Darren Star for HBO. An adaptation of Candace Bushnell\'s newspaper column and 1996 book anthology of the same name, the series premiered in the United States on June 6, 1998, and concluded on February 22, 2004, with 94 episodes broadcast over six seasons.<br><br>American television composer Douglas J. Cuomo composed the theme to Sex and the City (HBO), praised by The New Yorker magazine for its "unusual, edgy salsa flavor" and the saxophone quartet music that opens and closes Now with Bill Moyers (PBS).',
      descriptionRu: '«Секс в большом городе» — американский романтический комедийно-драматический телесериал, созданный Дарреном Старом для канала HBO. Адаптация газетной колонки Кэндис Бушнелл и одноименной книжной антологии 1996 года. Премьера сериала состоялась 6 июня 1998 года в США и завершилась 22 февраля 2004 года, когда в течение шести сезонов транслировались 94 эпизода.<br ><br>Американский телевизионный композитор Дуглас Дж. Куомо сочинил тему для сериала «Секс в большом городе», получившего высокую оценку журнала The New Yorker за «необычный, резкий привкус сальсы» и музыку квартета саксофонов, которая начинается и завершается сейчас с Биллом Мойерсом (PBS).',
      image: 'url(../../assets/img/sex-and-the-city.webp',
      audio: '../../assets/sound/sex-and-the-city.mp3',
      duration: '00:30',
      wikiEn: 'https://en.wikipedia.org/wiki/Sex_and_the_City_(soundtracks)',
      wikiRu: '',
      youtube: 'https://youtu.be/ntr62qu1kd0'
    }
  ],
  [
    {
      id: 1,
      nameEn: 'The Simpsons',
      nameRu: 'Симпсоны',
      trackEn: 'The Simpsons Theme',
      trackRu: 'Заставка Симпсоны',
      authorEn: 'Daniel Elfman',
      authorRu: 'Дэниел Эльфман',
      descriptionEn: '"The Simpsons Theme", also referred to as "The Simpsons Main Title Theme" in album releases, is the theme music of the animated television series The Simpsons.<br><br>It plays during the opening sequence and was composed by Danny Elfman in 1989, after series creator Matt Groening approached him requesting a theme.<br><br>The piece has been noted by Elfman as the most popular of his career.<br><br>The theme won the National Music Award for "Favorite TV Theme" in 2002, and has won the BMI TV Music Award in 1996, 1998, and 2003. In 1990, the theme was nominated for the Emmy for "Outstanding Achievement in Main Title Theme Music".',
      descriptionRu: 'Музыкальная тема к американскому мультсериалу «Симпсоны». Она играет в начале каждого эпизода.<br><br>Музыка была написана Дэниелем Эльфманом в 1989 году специально для «Симпсонов» после того, как Мэтт Гроунинг, создатель сериала, обратился к нему за помощью в создании стильной, в стиле ретро, музыкальной темы.<br><br>Эта тема, создание которой заняло всего три дня, стала самой популярной в карьере Эльфмана. Слегка различаясь аранжировками, тема порой играет и в конце эпизодов. Первоначально были две главные версии заключительной темы, с более длинной версией, заканчивающейся в низшем ключе. Обе версии были использованы в эпизодах 3 сезона, короткая версия была использована только для 4 сезона, затем снова использовалась более длинная тема и только в 7 сезоне была использована тема, которая звучит в эпизодах и сейчас.',
      image: 'url(../../assets/img/simpsons.webp',
      audio: '../../assets/sound/simpsons.mp3',
      duration: '00:16',
      wikiEn: 'https://en.wikipedia.org/wiki/The_Simpsons_Theme',
      wikiRu: 'https://ru.wikipedia.org/wiki/The_Simpsons_Theme',
      youtube: 'https://youtu.be/OQ4aPXNChMM'
    },
    {
      id: 2,
      nameEn: 'Chip \'n Dale',
      nameRu: 'Чип и Дейл',
      trackEn: 'Chip \'n Dale Theme Song',
      trackRu: 'Заставка Чип и Дейл',
      authorEn: 'Марк Мюллер',
      authorRu: 'Джон Уильямс',
      descriptionEn: 'Chip \'n Dale: Rescue Rangers is an American animated adventure comedy television series produced by Walt Disney Television Animation<br><br>The show\'s opening theme was written by Mark Mueller, an ASCAP Award-winning pop music songwriter who also wrote the popular DuckTales theme song, and produced by Alf Clausen.<br><br>The song performed over the title credits is sung by Jeff Pescetto (who also performed the DuckTales theme song).<br><br>A full-length theme song was recorded by The Jets, a Minnesota pop group, and released on The Disney Afternoon soundtrack.',
      descriptionRu: '«Чип и Дейл спешат на помощь» — американский анимационный приключенческий комедийный телесериал, созданный компанией Walt Disney Television Animation<br><br>Вступительная тема шоу была написана Марком Мюллером, автором песен в жанре поп-музыки, лауреатом премии ASCAP. который также написал популярную заглавную песню для «Утиных историй», спродюсированную Альфом Клаузеном.<br><br>Песню, исполняемую поверх титров, поет Джефф Пескетто (который также исполнил заглавную песню из «Утиных историй»).<br><br>A полнометражная музыкальная тема была записана поп-группой The Jets из Миннесоты и выпущена в качестве саундтрека к фильму «Дисней после полудня».',
      image: 'url(../../assets/img/chip-n-dale.webp',
      audio: '../../assets/sound/chip-n-dale.mp3',
      duration: '00:23',
      wikiEn: 'https://en.wikipedia.org/wiki/Chip_%27n_Dale:_Rescue_Rangers_(TV_series)',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%A7%D0%B8%D0%BF_%D0%B8_%D0%94%D0%B5%D0%B9%D0%BB_%D1%81%D0%BF%D0%B5%D1%88%D0%B0%D1%82_%D0%BD%D0%B0_%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C',
      youtube: 'https://youtu.be/vsMWVW4xtwI'
    },
    {
      id: 3,
      nameEn: 'The Lion King',
      nameRu: 'Король Лев',
      trackEn: 'Hakuna Matata',
      trackRu: 'Акуна Матата',
      authorEn: 'Elton John',
      authorRu: 'Элтон Джон',
      descriptionEn: '"Hakuna Matata" is a song from Disney\'s 32nd animated feature The Lion King. The music was written by Elton John with lyrics by Tim Rice.<br><br> The song is based on Timon and Pumbaa\'s catchphrase in the movie, Hakuna matata, a Swahili phrase meaning "No worry(s)". It is characterized by its simple 4/4 time, upbeat message and catchy lyrics.<br><br>Timon and Pumbaa, the two main comedy characters in the film, talking to Simba about moving forward from their troubled pasts and forgetting their worries, and Simba grows from cub to adult as the song progresses. The song also provides a backstory for Pumbaa, explaining that he was ostracized from animal society for his excessive flatulence.<br><br>It makes use of a large proportion of the orchestra as well as many other more unusual instruments including an elaborate drum kit.',
      descriptionRu: '"Акуна Матата" или "Хакуна Матата" в переводе с языка суахили буквально значит "никаких забот" — песня из мультфильма "Король Лев" (1994), которая была номинирована на "Оскар" в категории "Лучшая песня". Музыка — Элтона Джона, слова — Тима Райса.<br><br>Она заняла 99-ю позицию (из 100) в рейтинге лучших песен в истории кинематографа, составленном "American Film Institute".<br><br>В мультфильме песню поют Тимон, Пумба и Симба. Действие происходит после смерти Муфасы, Тимон и Пумба разговаривают с Симбой о том, что им нужно уйти от своего тревожного прошлого и забыть о своих заботах, а Симба по мере развития песни превращается из детеныша во взрослого.<br><br>В песне задействована большая часть оркестра, а также много других более необычных инструментов, включая сложную ударную установку.',
      image: 'url(../../assets/img/lion-king.webp',
      audio: '../../assets/sound/lion-king.mp3',
      duration: '00:26',
      wikiEn: 'https://en.wikipedia.org/wiki/Hakuna_Matata_(song)',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%90%D0%BA%D1%83%D0%BD%D0%B0_%D0%BC%D0%B0%D1%82%D0%B0%D1%82%D0%B0',
      youtube: 'https://youtu.be/kaOIxll4LCA'
    },
    {
      id: 4,
      nameEn: 'Frozen',
      nameRu: 'Холодное сердце',
      trackEn: 'Let It Go',
      trackRu: 'Отпусти и забудь',
      authorEn: 'Kristen Anderson-Lopez',
      authorRu: 'Кристен Андерсон-Лопес',
      descriptionEn: '"Let It Go" is a song from Disney\'s 2013 computer-animated feature film Frozen, whose music and lyrics were composed by husband-and-wife songwriting team Kristen Anderson-Lopez and Robert Lopez.<br><br>The song was performed in its original show-tune version in the film by American actress and singer Idina Menzel in her vocal role as Queen Elsa. It was later released as a single, being promoted to adult contemporary radio by Walt Disney Records in January 2014.<br><br>Anderson-Lopez and Lopez also composed a simplified pop version (with shorter lyrics and background chorus) which was performed by actress and singer Demi Lovato over the start of the film\'s closing credits. Disney\'s music division planned to release Lovato\'s version of the song before Menzel\'s, as they did not consider Menzel\'s version a traditional pop song.<br><br>A music video was released separately for Lovato\'s version.',
      descriptionRu: '«Отпусти и забудь» — песня из диснеевского анимационного фильма 2013 года «Холодное сердце». Слова и музыка были написаны мужем и женой Робертом Лопесом и Кристен Андерсон-Лопес. В мультфильме песня исполнялась Эльзой.<br><br>Также Лопес и Андерсон-Лопес написали поп-версию этой песни (с укороченным текстом), которую записала Деми Ловато и на которую был снят видеоклип. Кроме того, для релизов фильма в различных странах были записаны версии этой песни ещё на как минимум 24 языках.<br><br>Песня достигла 5 места в американском чарте Billboard Hot 100 (в исполнении Идины Мензел) и завоевала как премию «Оскар» за лучшую песню к фильму (в 2014 году), так и премию «Грэмми» за лучшую песню, написанную для кино, телевидения или другого визуального представления (в 2015 году).',
      image: 'url(../../assets/img/frozen.webp',
      audio: '../../assets/sound/frozen.mp3',
      duration: '00:26',
      wikiEn: 'https://en.wikipedia.org/wiki/Let_It_Go',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%9E%D1%82%D0%BF%D1%83%D1%81%D1%82%D0%B8_%D0%B8_%D0%B7%D0%B0%D0%B1%D1%83%D0%B4%D1%8C',
      youtube: 'https://youtu.be/moSFlvxnbgk'
    },{
      id: 5,
      nameEn: 'Masha and the Bear',
      nameRu: 'Маша и Медведь',
      trackEn: 'Masha and the Bear Theme',
      trackRu: 'Заставка Маша и Медведь',
      authorEn: 'Vasily Bogatyrev',
      authorRu: 'Василий Богатырёв',
      descriptionEn: '"Masha and the Bear" is a Russian animated television series created by Oleg Kuzovkov and produced by Animaccord Animation Studio, loosely based on the oral children\'s folk story of the same name. The show focuses on the adventures of a little girl named Masha and her caring friend, the bear (mishka) that always keeps her safe from disasters.<br><br>The soundtrack for each episode is written by Russian composer Vasily Bogatyrev. Many compositions are stylized for famous works: Moonlight Sonata, Beethoven\'s Symphony No. 5, a circus theme from the movie Soviet Circus, and in the episode “One-Hit Wonder” the rockstar Masha performs a song in the style of the group AC/DC. Most of the songs used in the cartoon, such as the soundtracks of “Laundry Day” and “The Grand Piano Lesson” episodes, became popular in Russia and abroad.',
      descriptionRu: '«Маша и Медведь» — российский мультсериал, созданный Олегом Кузовковым и выпущенный анимационной студией «Анимаккорд» по мотивам одноименной устной детской народной сказки. Шоу посвящено приключениям маленькой девочки по имени Маша и ее заботливого друга медведя, который всегда оберегает ее от бедствий.<br><br>Саундтрек к каждой серии написан композитором Василием Богатырёвым. Многие композиции стилизованы под известные произведения: «Лунная соната», «Симфония № 5» Бетховена, цирковая тема из фильма «Советский цирк», а в эпизоде «One-Hit Wonder» рок-звезда Маша исполняет песню в стиле группы AC/DC. Большинство песен, использованных в мультфильме, например, саундтреки к эпизодам «День стирки» и «Урок игры на фортепиано», стали популярными в России и за рубежом.',
      image: 'url(../../assets/img/masha-and-bear.webp',
      audio: '../../assets/sound/masha-and-bear.mp3',
      duration: '00:21',
      wikiEn: 'https://en.wikipedia.org/wiki/Masha_and_the_Bear',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%88%D0%B0_%D0%B8_%D0%9C%D0%B5%D0%B4%D0%B2%D0%B5%D0%B4%D1%8C',
      youtube: 'https://youtu.be/nhZkOGbxqZc'
    },
    {
      id: 6,
      nameEn: 'Winnie The Pooh',
      nameRu: 'Винни-Пух',
      trackEn: 'Winnie the Pooh Main Theme',
      trackRu: 'Заставка Винни Пух',
      authorEn: 'Steve Nelson',
      authorRu: 'Стив Нельсон',
      descriptionEn: 'The theme song that opens each episode of The New Adventures of Winnie the Pooh<br><br>The show\'s theme song, entitled "Pooh Bear", was written by Steve Nelson and sung by Steve Wood. A version with Nelson doing the vocals later appeared on his Listen What the Katmandu album. Another version of the song with Jim Cummings doing the vocals (who also voiced Pooh and Tigger) appeared in reruns of the series on Disney Channel in 1994.<br><br>Nelson also composed several additional songs that were shown on the early episodes. The music was particularly praised by critics. An orchestra was used to record the music, using instruments such as trumpets, woodwinds, and a full string section. The composers were given the unique opportunity to examine the animator\'s exposure sheets, enabling them to write music while an episode was being scripted.',
      descriptionRu: 'Музыкальная тема, открывающая каждую серию «Новых приключений Винни-Пуха». Песня была написана Стивом Нельсоном и исполнена Стивом Вудом.<br><br>Версия с вокалом Нельсона позже появилась на его альбоме Listen What the Katmandu. Другая версия песни с вокалом Джима Каммингса (который также озвучивал Пуха и Тигра) появилась в повторах сериала на канале Disney в 1994 году.<br><br>Нельсон также сочинил несколько дополнительных песен, которые были показаны в первых эпизодах.<br><br>Музыка была особенно высоко оценена критиками. Для записи использовался оркестр с использованием таких инструментов, как трубы, деревянные духовые инструменты и полная струнная секция. Композиторам была предоставлена уникальная возможность изучить экспозиционные листы аниматора, что позволило им писать музыку во время написания сценария эпизода.',
      image: 'url(../../assets/img/winnie-the-pooh.webp',
      audio: '../../assets/sound/winnie-the-pooh.mp3',
      duration: '00:14',
      wikiEn: 'https://en.wikipedia.org/wiki/Lux_Aeterna_(Mansell)',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%9D%D0%BE%D0%B2%D1%8B%D0%B5_%D0%BF%D1%80%D0%B8%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F_%D0%92%D0%B8%D0%BD%D0%BD%D0%B8-%D0%9F%D1%83%D1%85%D0%B0',
      youtube: 'https://youtu.be/oc3Cq89P97Y'
    }
  ],
  [
    {
      id: 1,
      nameEn: 'Who Wants to Be a Millionaire?',
      nameRu: 'Кто хочет стать миллионером?',
      trackEn: 'Who Wants to Be a Millionaire',
      trackRu: 'Кто хочет стать миллионером',
      authorEn: 'Matthew Strachan',
      authorRu: 'Мэтью Стрэкан',
      descriptionEn: 'Matthew Strachan was an English composer and singer-songwriter. His best known work is the music for British television game show Who Wants to Be a Millionaire? written with his father Keith, which would become a global franchise, and the BBC Radio 4 World War I drama series Home Front.<br><br>He also wrote music to film and television productions such as Extract, The Detectives, Question Time, Winning Lines, jingles for several television commercials, and scores for stage musicals.',
      descriptionRu: 'Мэттью Стрэкан — английский композитор и певец-поэт-песенник. Его самая известная работа — музыка для телевизионного игрового шоу «Кто хочет стать миллионером?», которую он написал вместе со своим отцом Китом.<br><br>Он также создал музыку к фильмам и телевизионным постановкам, таким как Extract, The Detectives, Question Time, Winning Lines, а также джинглы для нескольких рекламных роликов и сценических мюзиклов.',
      image: 'url(../../assets/img/millionaire.webp',
      audio: '../../assets/sound/millionaire.mp3',
      duration: '00:19',
      wikiEn: '',
      wikiRu: '',
      youtube: ''
    },
    {
      id: 2,
      nameEn: 'Star Wars',
      nameRu: 'Звёздные войны',
      trackEn: 'The Imperial March',
      trackRu: 'Имперский марш',
      authorEn: 'John Williams',
      authorRu: 'Джон Уильямс',
      descriptionEn: '"The Imperial March (Darth Vader\'s Theme)" is a musical theme present in the Star Wars franchise. It was composed by John Williams for the film The Empire Strikes Back.<br><br>Together with "Yoda\'s Theme", "The Imperial March" was premiered on April 29, 1980, three weeks before the opening of the film, on the occasion of John Williams first concert as official conductor-in-residence of the Boston Pops Orchestra.<br><br>One of the best known symphonic movie themes, it is used as a leitmotif throughout the Star Wars franchise.',
      descriptionRu: '«Имперский марш (Тема Дарта Вейдера)» — музыкальная тема, представленная во франшизе «Звёздные войны». Она была написана Джоном Уильямсом для фильма «Звёздные войны. Эпизод V: Империя наносит ответный удар».<br><br>Вместе с «темой Йоды» премьера «Имперского марша» состоялась 29 апреля 1980 года, за три недели до открытия фильма, по случаю первого концерта Джона Уильямса в качестве официального дирижёра Boston Pops Orchestra.<br><br>Одна из самых известных тем симфонического кино, это пример лейтмотива, повторяющейся темы, связанной с персонажами или событиями в драме.',
      image: 'url(../../assets/img/star-wars.webp',
      audio: '../../assets/sound/star-wars.mp3',
      duration: '00:21',
      wikiEn: 'https://en.wikipedia.org/wiki/The_Imperial_March',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%98%D0%BC%D0%BF%D0%B5%D1%80%D1%81%D0%BA%D0%B8%D0%B9_%D0%BC%D0%B0%D1%80%D1%88',
      youtube: 'https://youtu.be/vsMWVW4xtwI'
    },
    {
      id: 3,
      nameEn: 'The Godfather',
      nameRu: 'Крёстный отец',
      trackEn: 'Speak Softly Love',
      trackRu: 'Говори тихо, любовь моя',
      authorEn: 'Nino Rota',
      authorRu: 'Нино Рота',
      descriptionEn: '"Love Theme from The Godfather" is an instrumental theme from the 1972 film The Godfather, composed by Nino Rota.<br><br>The piece was lyricized in English by Larry Kusik into "Speak Softly, Love", a popular song released in 1972.<br><br>The highest-charting rendition of either version was by vocalist Andy Williams, who took "Speak Softly Love" to number 34 on Billboard magazine\'s Hot 100 and number seven on its Easy Listening chart.',
      descriptionRu: '«Говори тихо, любовь моя» — песня композитора Нино Рота на слова Ларри Кьюзика, впервые прозвучавшая в инструментальном исполнении в фильме «Крёстный отец» (1972).<br><br>Наибольшей популярности песня достигла в исполнении Энди Уильямса, поднявшись до 43-й позиции в Billboard Hot 100 и седьмого места в хит-параде Easy Listening.<br><br>Позднее эту песню исполняли также Эл Мартино, София Ротару («Скажи, що любиш», 1975), Бобби Винтон, Муслим Магомаев, Олег Погудин и другие певцы.',
      image: 'url(../../assets/img/godfather.webp',
      audio: '../../assets/sound/godfather.mp3',
      duration: '00:15',
      wikiEn: 'https://en.wikipedia.org/wiki/Love_Theme_from_The_Godfather',
      wikiRu: 'https://ru.wikipedia.org/wiki/Speak_Softly_Love',
      youtube: 'https://youtu.be/zbSMCyJkUmI'
    },
    {
      id: 4,
      nameEn: 'Pulp Fiction',
      nameRu: 'Криминальное чтиво',
      trackEn: 'You Never Can Tell',
      trackRu: 'Никак не угадать',
      authorEn: 'Chuck Berry',
      authorRu: 'Чак Берри',
      descriptionEn: '"You Never Can Tell", also known as "C\'est La Vie" or "Teenage Wedding", is a song written by Chuck Berry.<br><br>It was composed in the early 1960s while Berry was in federal prison for violating the Mann Act. Released in 1964 on the album St. Louis to Liverpool and the follow-up single to Berry\'s final Top Ten hit of the 1960s: "No Particular Place to Go", "You Never Can Tell" reached number 14, becoming Berry\'s final Top 40 hit until "My Ding-a-Ling", a number 1 in October 1972.<br><br>The song became popular again after the 1994 release of the film Pulp Fiction, directed and co-written by Quentin Tarantino. The music was played for a "Twist contest" in which Vincent Vega (John Travolta) and Mia Wallace (Uma Thurman) competed (and were the only contestants shown in the film). The music added an evocative element of sound to the narrative and Tarantino said that the song\'s lyrics of "Pierre" and "Mademoiselle" gave the scene a "uniquely \'50s French New Wave dance sequence feel".',
      descriptionRu: '«You Never Can Tell» — песня американского рок-музыканта Чака Берри, вышедшая на сингле в 1964 году.<br><br>Песня была написана в начале шестидесятых, в то время, когда Чак Берри находился в тюрьме. You Never Can Tell вошла в альбом Берри St. Louis to Liverpool 1964 года, изданный на лейбле Chess Records, как сингл она дошла до 14 места в рейтинге журнала Billboard.<br><br>Вторая волна популярности You Never Can Tell началась после выхода на экраны фильма культового американского режиссёра Квентина Тарантино «Криминальное чтиво» (1994), в саундтрек которого вошла песня. В одном из эпизодов фильма гангстер Винсент Вега (Джон Траволта) и жена его босса Миа Уоллес (Ума Турман) танцуют твист под песню Чака Берри. По словам Тарантино, лирика песни придаёт этой сцене особую атмосферу Французской новой волны.',
      image: 'url(../../assets/img/pulp-fiction.webp',
      audio: '../../assets/sound/pulp-fiction.mp3',
      duration: '00:26',
      wikiEn: 'https://en.wikipedia.org/wiki/You_Never_Can_Tell_(song)',
      wikiRu: 'https://ru.wikipedia.org/wiki/You_Never_Can_Tell',
      youtube: 'https://youtu.be/WSLMN6g_Od4'
    },{
      id: 5,
      nameEn: 'The Bodyguard',
      nameRu: 'Телохранитель',
      trackEn: 'I Will Always Love You',
      trackRu: 'Я всегда буду любить тебя',
      authorEn: 'Whitney Houston',
      authorRu: 'Уитни Хьюстон',
      descriptionEn: '"I Will Always Love You" is a song written and originally recorded in 1973 by American singer-songwriter Dolly Parton.<br><br>Whitney Houston recorded a soul-ballad arrangement of the song for the 1992 film The Bodyguard. Houston\'s version peaked at number one on the Billboard Hot 100 for a then-record-breaking 14 weeks. The single was certified Diamond by the RIAA, making Houston\'s first Diamond single, the third female artist who had both a Diamond single and a Diamond album, and becoming the best-selling single by a woman in the U.S.<br><br>The song was a global success, topping the charts in almost all countries. With 20 million copies sold it became the best-selling single of all time by a female solo artist.<br><br>Houston won the Grammy Award for Record of the Year in 1994 for "I Will Always Love You". The song has been recorded by many other artists including Linda Ronstadt, John Doe, Amber Riley, LeAnn Rimes and Sarah Washington, whose dance version reached number 12 on the UK Singles Chart.',
      descriptionRu: '«Я всегда буду любить тебя» — сингл американской кантри-певицы Долли Партон, выпущенный в 1974 году на лейбле RCA Records.<br><br>Однако с наибольшим успехом исполнила этот хит другая певица — Уитни Хьюстон. Её соул-версия, включённая в саундтрек к фильму «Телохранитель» 1992 года, была удостоена множества наград, в том числе «Грэмми» за лучшую запись года и лучший женский поп-вокал.<br><br>Критики были впечатлены тем, как грустная любовная песня благодаря мощному вокалу и влиянию госпела превратилась в неистовое воплощение драмы покинутой женщины.',
      image: 'url(../../assets/img/bodyguard.webp',
      audio: '../../assets/sound/bodyguard.mp3',
      duration: '00:47',
      wikiEn: 'https://en.wikipedia.org/wiki/I_Will_Always_Love_You',
      wikiRu: 'https://ru.wikipedia.org/wiki/I_Will_Always_Love_You',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 6,
      nameEn: 'Requiem for a Dream',
      nameRu: 'Реквием по мечте',
      trackEn: 'Lux Aeterna',
      trackRu: 'Вечный свет',
      authorEn: 'Clint Mansell',
      authorRu: 'Клинт Мэнселл',
      descriptionEn: '"Lux Aeterna" is an orchestral composition by Clint Mansell. It forms a leitmotif in the 2000 film Requiem for a Dream, and is the penultimate piece in the movie\'s soundtrack.<br><br>The popularity of the piece led to its use in popular culture outside the film, in film and teaser trailers, such as Sunshine and Waking Madison, and multiple remixes and remakes by other producers.<br><br>It was also used in the 2010 season 2 premiere episode of NCIS: LA and a version of the track was re-orchestrated with a choir and full orchestra for The Lord of the Rings: The Two Towers trailer.<br><br>It was arranged by Simone Benyacar, Daniel Nielsen, and Veigar Margeirsson.<br><br>The orchestrated version was used in various trailers and video games. Clint Mansell commented that the piece had "gone on to have a life of its own".',
      descriptionRu: '«Вечный свет» — саундтрек к фильму Даррена Аронофски «Реквием по мечте» (экранизация романа Хьюберта Селби). Выпущен в 2000 году. Композитором является Клинт Мэнселл.<br><br>Эта музыка стала культовым хитом, так как саундтрек был оценён по достоинству многими музыкантами и получил широкое признание, а композиция «Lux Aeterna» и её реаранжированная версия «Requiem for a Tower» впоследствии были использованы в различных формах массовой информации (трейлеры и тизеры фильмов и сериалов, видеоигры, телепередачи, рекламные ролики и другие медиа).<br><br>Саундтрек Requiem for a Dream закрепил свою популярность после издания альбома Requiem for a Dream: Remixed, содержавшего новые ремиксы, созданные Полом Окенфолдом, Джошем Уинком, Джэгзом Кунером, Delerium и многими другими.',
      image: 'url(../../assets/img/requiem.webp',
      audio: '../../assets/sound/requiem.mp3',
      duration: '00:30',
      wikiEn: 'https://en.wikipedia.org/wiki/Lux_Aeterna_(Mansell)',
      wikiRu: 'https://ru.wikipedia.org/wiki/Requiem_for_a_Dream_(%D1%81%D0%B0%D1%83%D0%BD%D0%B4%D1%82%D1%80%D0%B5%D0%BA)',
      youtube: 'https://youtu.be/oc3Cq89P97Y'
    }
  ],
  [
    {
      id: 1,
      nameEn: 'Titanic',
      nameRu: 'Титаник',
      trackEn: 'My Heart Will Go On',
      trackRu: 'Моё сердце будет биться',
      authorEn: 'Céline Dion',
      authorRu: 'Селин Дион',
      descriptionEn: '"My Heart Will Go On" is a 1997 song recorded by Canadian singer Celine Dion.<br><br>The song serves as the main soundtrack to James Cameron\'s blockbuster film Titanic, based on an account of the transatlantic ocean liner of the same name which sank in 1912 after colliding with an iceberg in the North Atlantic Ocean.<br><br>The song\'s music was composed by James Horner, its lyrics were written by Will Jennings, while the production was handled by Walter Afanasieff, Horner and Simon Franglen.',
      descriptionRu: '"Моё сердце будет биться дальше" — песня канадской певицы Селин Дион, главная тема к фильму Джеймса Кэмерона "Титаник".<br><br>Автор музыки — Джеймс Хорнер, слова написал Уилл Дженнингс, продюсером стал Уолтер Афанасьефф. Композиция была выпущена на альбоме Дион Let\'s Talk About Love в 1997 году, она возглавила чарты по всему миру, включая США, Великобританию и Австралию.<br><br>Релиз сингла состоялся в Австралии и Германии 8 декабря 1997 года и в январе и феврале 1998 года в остальном мире, композиция стала одной из самых популярных за всю историю музыки и самой продаваемой в мире песней 1998 года.емыми в более чем 18 миллионов копий, это второй самый продаваемый сингл на физическом носителе в истории музыки и один из самых продаваемых синглов всех времен.<br><br>Он также был самым продаваемым синглом в мире за 1998 год. Песня также была включена в список "Песни века" Американской ассоциацией звукозаписывающей индустрии и Национальным фондом искусств.<br><br>Дион исполнила песню в честь 20-летия фильма "Титаник" на церемонии вручения премии Billboard Music Awards 21 мая 2017 года.',
      image: 'url(../../assets/img/titanic.webp',
      audio: '../../assets/sound/titanic.mp3',
      duration: '00:17',
      wikiEn: 'https://en.wikipedia.org/wiki/My_Heart_Will_Go_On',
      wikiRu: 'https://ru.wikipedia.org/wiki/My_Heart_Will_Go_On',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 2,
      nameEn: 'Star Wars',
      nameRu: 'Звёздные войны',
      trackEn: 'The Imperial March',
      trackRu: 'Имперский марш',
      authorEn: 'John Williams',
      authorRu: 'Джон Уильямс',
      descriptionEn: '"The Imperial March (Darth Vader\'s Theme)" is a musical theme present in the Star Wars franchise. It was composed by John Williams for the film The Empire Strikes Back.<br><br>Together with "Yoda\'s Theme", "The Imperial March" was premiered on April 29, 1980, three weeks before the opening of the film, on the occasion of John Williams first concert as official conductor-in-residence of the Boston Pops Orchestra.<br><br>One of the best known symphonic movie themes, it is used as a leitmotif throughout the Star Wars franchise.',
      descriptionRu: '«Имперский марш (Тема Дарта Вейдера)» — музыкальная тема, представленная во франшизе «Звёздные войны». Она была написана Джоном Уильямсом для фильма «Звёздные войны. Эпизод V: Империя наносит ответный удар».<br><br>Вместе с «темой Йоды» премьера «Имперского марша» состоялась 29 апреля 1980 года, за три недели до открытия фильма, по случаю первого концерта Джона Уильямса в качестве официального дирижёра Boston Pops Orchestra.<br><br>Одна из самых известных тем симфонического кино, это пример лейтмотива, повторяющейся темы, связанной с персонажами или событиями в драме.',
      image: 'url(../../assets/img/star-wars.webp',
      audio: '../../assets/sound/star-wars.mp3',
      duration: '00:21',
      wikiEn: 'https://en.wikipedia.org/wiki/The_Imperial_March',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%98%D0%BC%D0%BF%D0%B5%D1%80%D1%81%D0%BA%D0%B8%D0%B9_%D0%BC%D0%B0%D1%80%D1%88',
      youtube: 'https://youtu.be/vsMWVW4xtwI'
    },
    {
      id: 3,
      nameEn: 'The Godfather',
      nameRu: 'Крёстный отец',
      trackEn: 'Speak Softly Love',
      trackRu: 'Говори тихо, любовь моя',
      authorEn: 'Nino Rota',
      authorRu: 'Нино Рота',
      descriptionEn: '"Love Theme from The Godfather" is an instrumental theme from the 1972 film The Godfather, composed by Nino Rota.<br><br>The piece was lyricized in English by Larry Kusik into "Speak Softly, Love", a popular song released in 1972.<br><br>The highest-charting rendition of either version was by vocalist Andy Williams, who took "Speak Softly Love" to number 34 on Billboard magazine\'s Hot 100 and number seven on its Easy Listening chart.',
      descriptionRu: '«Говори тихо, любовь моя» — песня композитора Нино Рота на слова Ларри Кьюзика, впервые прозвучавшая в инструментальном исполнении в фильме «Крёстный отец» (1972).<br><br>Наибольшей популярности песня достигла в исполнении Энди Уильямса, поднявшись до 43-й позиции в Billboard Hot 100 и седьмого места в хит-параде Easy Listening.<br><br>Позднее эту песню исполняли также Эл Мартино, София Ротару («Скажи, що любиш», 1975), Бобби Винтон, Муслим Магомаев, Олег Погудин и другие певцы.',
      image: 'url(../../assets/img/godfather.webp',
      audio: '../../assets/sound/godfather.mp3',
      duration: '00:15',
      wikiEn: 'https://en.wikipedia.org/wiki/Love_Theme_from_The_Godfather',
      wikiRu: 'https://ru.wikipedia.org/wiki/Speak_Softly_Love',
      youtube: 'https://youtu.be/zbSMCyJkUmI'
    },
    {
      id: 4,
      nameEn: 'Pulp Fiction',
      nameRu: 'Криминальное чтиво',
      trackEn: 'You Never Can Tell',
      trackRu: 'Никак не угадать',
      authorEn: 'Chuck Berry',
      authorRu: 'Чак Берри',
      descriptionEn: '"You Never Can Tell", also known as "C\'est La Vie" or "Teenage Wedding", is a song written by Chuck Berry.<br><br>It was composed in the early 1960s while Berry was in federal prison for violating the Mann Act. Released in 1964 on the album St. Louis to Liverpool and the follow-up single to Berry\'s final Top Ten hit of the 1960s: "No Particular Place to Go", "You Never Can Tell" reached number 14, becoming Berry\'s final Top 40 hit until "My Ding-a-Ling", a number 1 in October 1972.<br><br>The song became popular again after the 1994 release of the film Pulp Fiction, directed and co-written by Quentin Tarantino. The music was played for a "Twist contest" in which Vincent Vega (John Travolta) and Mia Wallace (Uma Thurman) competed (and were the only contestants shown in the film). The music added an evocative element of sound to the narrative and Tarantino said that the song\'s lyrics of "Pierre" and "Mademoiselle" gave the scene a "uniquely \'50s French New Wave dance sequence feel".',
      descriptionRu: '«You Never Can Tell» — песня американского рок-музыканта Чака Берри, вышедшая на сингле в 1964 году.<br><br>Песня была написана в начале шестидесятых, в то время, когда Чак Берри находился в тюрьме. You Never Can Tell вошла в альбом Берри St. Louis to Liverpool 1964 года, изданный на лейбле Chess Records, как сингл она дошла до 14 места в рейтинге журнала Billboard.<br><br>Вторая волна популярности You Never Can Tell началась после выхода на экраны фильма культового американского режиссёра Квентина Тарантино «Криминальное чтиво» (1994), в саундтрек которого вошла песня. В одном из эпизодов фильма гангстер Винсент Вега (Джон Траволта) и жена его босса Миа Уоллес (Ума Турман) танцуют твист под песню Чака Берри. По словам Тарантино, лирика песни придаёт этой сцене особую атмосферу Французской новой волны.',
      image: 'url(../../assets/img/pulp-fiction.webp',
      audio: '../../assets/sound/pulp-fiction.mp3',
      duration: '00:26',
      wikiEn: 'https://en.wikipedia.org/wiki/You_Never_Can_Tell_(song)',
      wikiRu: 'https://ru.wikipedia.org/wiki/You_Never_Can_Tell',
      youtube: 'https://youtu.be/WSLMN6g_Od4'
    },{
      id: 5,
      nameEn: 'The Bodyguard',
      nameRu: 'Телохранитель',
      trackEn: 'I Will Always Love You',
      trackRu: 'Я всегда буду любить тебя',
      authorEn: 'Whitney Houston',
      authorRu: 'Уитни Хьюстон',
      descriptionEn: '"I Will Always Love You" is a song written and originally recorded in 1973 by American singer-songwriter Dolly Parton.<br><br>Whitney Houston recorded a soul-ballad arrangement of the song for the 1992 film The Bodyguard. Houston\'s version peaked at number one on the Billboard Hot 100 for a then-record-breaking 14 weeks. The single was certified Diamond by the RIAA, making Houston\'s first Diamond single, the third female artist who had both a Diamond single and a Diamond album, and becoming the best-selling single by a woman in the U.S.<br><br>The song was a global success, topping the charts in almost all countries. With 20 million copies sold it became the best-selling single of all time by a female solo artist.<br><br>Houston won the Grammy Award for Record of the Year in 1994 for "I Will Always Love You". The song has been recorded by many other artists including Linda Ronstadt, John Doe, Amber Riley, LeAnn Rimes and Sarah Washington, whose dance version reached number 12 on the UK Singles Chart.',
      descriptionRu: '«Я всегда буду любить тебя» — сингл американской кантри-певицы Долли Партон, выпущенный в 1974 году на лейбле RCA Records.<br><br>Однако с наибольшим успехом исполнила этот хит другая певица — Уитни Хьюстон. Её соул-версия, включённая в саундтрек к фильму «Телохранитель» 1992 года, была удостоена множества наград, в том числе «Грэмми» за лучшую запись года и лучший женский поп-вокал.<br><br>Критики были впечатлены тем, как грустная любовная песня благодаря мощному вокалу и влиянию госпела превратилась в неистовое воплощение драмы покинутой женщины.',
      image: 'url(../../assets/img/bodyguard.webp',
      audio: '../../assets/sound/bodyguard.mp3',
      duration: '00:47',
      wikiEn: 'https://en.wikipedia.org/wiki/I_Will_Always_Love_You',
      wikiRu: 'https://ru.wikipedia.org/wiki/I_Will_Always_Love_You',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 6,
      nameEn: 'Requiem for a Dream',
      nameRu: 'Реквием по мечте',
      trackEn: 'Lux Aeterna',
      trackRu: 'Вечный свет',
      authorEn: 'Clint Mansell',
      authorRu: 'Клинт Мэнселл',
      descriptionEn: '"Lux Aeterna" is an orchestral composition by Clint Mansell. It forms a leitmotif in the 2000 film Requiem for a Dream, and is the penultimate piece in the movie\'s soundtrack.<br><br>The popularity of the piece led to its use in popular culture outside the film, in film and teaser trailers, such as Sunshine and Waking Madison, and multiple remixes and remakes by other producers.<br><br>It was also used in the 2010 season 2 premiere episode of NCIS: LA and a version of the track was re-orchestrated with a choir and full orchestra for The Lord of the Rings: The Two Towers trailer.<br><br>It was arranged by Simone Benyacar, Daniel Nielsen, and Veigar Margeirsson.<br><br>The orchestrated version was used in various trailers and video games. Clint Mansell commented that the piece had "gone on to have a life of its own".',
      descriptionRu: '«Вечный свет» — саундтрек к фильму Даррена Аронофски «Реквием по мечте» (экранизация романа Хьюберта Селби). Выпущен в 2000 году. Композитором является Клинт Мэнселл.<br><br>Эта музыка стала культовым хитом, так как саундтрек был оценён по достоинству многими музыкантами и получил широкое признание, а композиция «Lux Aeterna» и её реаранжированная версия «Requiem for a Tower» впоследствии были использованы в различных формах массовой информации (трейлеры и тизеры фильмов и сериалов, видеоигры, телепередачи, рекламные ролики и другие медиа).<br><br>Саундтрек Requiem for a Dream закрепил свою популярность после издания альбома Requiem for a Dream: Remixed, содержавшего новые ремиксы, созданные Полом Окенфолдом, Джошем Уинком, Джэгзом Кунером, Delerium и многими другими.',
      image: 'url(../../assets/img/requiem.webp',
      audio: '../../assets/sound/requiem.mp3',
      duration: '00:30',
      wikiEn: 'https://en.wikipedia.org/wiki/Lux_Aeterna_(Mansell)',
      wikiRu: 'https://ru.wikipedia.org/wiki/Requiem_for_a_Dream_(%D1%81%D0%B0%D1%83%D0%BD%D0%B4%D1%82%D1%80%D0%B5%D0%BA)',
      youtube: 'https://youtu.be/oc3Cq89P97Y'
    }
  ],
  [
    {
      id: 1,
      nameEn: 'Titanic',
      nameRu: 'Титаник',
      trackEn: 'My Heart Will Go On',
      trackRu: 'Моё сердце будет биться',
      authorEn: 'Céline Dion',
      authorRu: 'Селин Дион',
      descriptionEn: '"My Heart Will Go On" is a 1997 song recorded by Canadian singer Celine Dion.<br><br>The song serves as the main soundtrack to James Cameron\'s blockbuster film Titanic, based on an account of the transatlantic ocean liner of the same name which sank in 1912 after colliding with an iceberg in the North Atlantic Ocean.<br><br>The song\'s music was composed by James Horner, its lyrics were written by Will Jennings, while the production was handled by Walter Afanasieff, Horner and Simon Franglen.',
      descriptionRu: '"Моё сердце будет биться дальше" — песня канадской певицы Селин Дион, главная тема к фильму Джеймса Кэмерона "Титаник".<br><br>Автор музыки — Джеймс Хорнер, слова написал Уилл Дженнингс, продюсером стал Уолтер Афанасьефф. Композиция была выпущена на альбоме Дион Let\'s Talk About Love в 1997 году, она возглавила чарты по всему миру, включая США, Великобританию и Австралию.<br><br>Релиз сингла состоялся в Австралии и Германии 8 декабря 1997 года и в январе и феврале 1998 года в остальном мире, композиция стала одной из самых популярных за всю историю музыки и самой продаваемой в мире песней 1998 года.емыми в более чем 18 миллионов копий, это второй самый продаваемый сингл на физическом носителе в истории музыки и один из самых продаваемых синглов всех времен.<br><br>Он также был самым продаваемым синглом в мире за 1998 год. Песня также была включена в список "Песни века" Американской ассоциацией звукозаписывающей индустрии и Национальным фондом искусств.<br><br>Дион исполнила песню в честь 20-летия фильма "Титаник" на церемонии вручения премии Billboard Music Awards 21 мая 2017 года.',
      image: 'url(../../assets/img/titanic.webp',
      audio: '../../assets/sound/titanic.mp3',
      duration: '00:17',
      wikiEn: 'https://en.wikipedia.org/wiki/My_Heart_Will_Go_On',
      wikiRu: 'https://ru.wikipedia.org/wiki/My_Heart_Will_Go_On',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 2,
      nameEn: 'Star Wars',
      nameRu: 'Звёздные войны',
      trackEn: 'The Imperial March',
      trackRu: 'Имперский марш',
      authorEn: 'John Williams',
      authorRu: 'Джон Уильямс',
      descriptionEn: '"The Imperial March (Darth Vader\'s Theme)" is a musical theme present in the Star Wars franchise. It was composed by John Williams for the film The Empire Strikes Back.<br><br>Together with "Yoda\'s Theme", "The Imperial March" was premiered on April 29, 1980, three weeks before the opening of the film, on the occasion of John Williams first concert as official conductor-in-residence of the Boston Pops Orchestra.<br><br>One of the best known symphonic movie themes, it is used as a leitmotif throughout the Star Wars franchise.',
      descriptionRu: '«Имперский марш (Тема Дарта Вейдера)» — музыкальная тема, представленная во франшизе «Звёздные войны». Она была написана Джоном Уильямсом для фильма «Звёздные войны. Эпизод V: Империя наносит ответный удар».<br><br>Вместе с «темой Йоды» премьера «Имперского марша» состоялась 29 апреля 1980 года, за три недели до открытия фильма, по случаю первого концерта Джона Уильямса в качестве официального дирижёра Boston Pops Orchestra.<br><br>Одна из самых известных тем симфонического кино, это пример лейтмотива, повторяющейся темы, связанной с персонажами или событиями в драме.',
      image: 'url(../../assets/img/star-wars.webp',
      audio: '../../assets/sound/star-wars.mp3',
      duration: '00:21',
      wikiEn: 'https://en.wikipedia.org/wiki/The_Imperial_March',
      wikiRu: 'https://ru.wikipedia.org/wiki/%D0%98%D0%BC%D0%BF%D0%B5%D1%80%D1%81%D0%BA%D0%B8%D0%B9_%D0%BC%D0%B0%D1%80%D1%88',
      youtube: 'https://youtu.be/vsMWVW4xtwI'
    },
    {
      id: 3,
      nameEn: 'The Godfather',
      nameRu: 'Крёстный отец',
      trackEn: 'Speak Softly Love',
      trackRu: 'Говори тихо, любовь моя',
      authorEn: 'Nino Rota',
      authorRu: 'Нино Рота',
      descriptionEn: '"Love Theme from The Godfather" is an instrumental theme from the 1972 film The Godfather, composed by Nino Rota.<br><br>The piece was lyricized in English by Larry Kusik into "Speak Softly, Love", a popular song released in 1972.<br><br>The highest-charting rendition of either version was by vocalist Andy Williams, who took "Speak Softly Love" to number 34 on Billboard magazine\'s Hot 100 and number seven on its Easy Listening chart.',
      descriptionRu: '«Говори тихо, любовь моя» — песня композитора Нино Рота на слова Ларри Кьюзика, впервые прозвучавшая в инструментальном исполнении в фильме «Крёстный отец» (1972).<br><br>Наибольшей популярности песня достигла в исполнении Энди Уильямса, поднявшись до 43-й позиции в Billboard Hot 100 и седьмого места в хит-параде Easy Listening.<br><br>Позднее эту песню исполняли также Эл Мартино, София Ротару («Скажи, що любиш», 1975), Бобби Винтон, Муслим Магомаев, Олег Погудин и другие певцы.',
      image: 'url(../../assets/img/godfather.webp',
      audio: '../../assets/sound/godfather.mp3',
      duration: '00:15',
      wikiEn: 'https://en.wikipedia.org/wiki/Love_Theme_from_The_Godfather',
      wikiRu: 'https://ru.wikipedia.org/wiki/Speak_Softly_Love',
      youtube: 'https://youtu.be/zbSMCyJkUmI'
    },
    {
      id: 4,
      nameEn: 'Pulp Fiction',
      nameRu: 'Криминальное чтиво',
      trackEn: 'You Never Can Tell',
      trackRu: 'Никак не угадать',
      authorEn: 'Chuck Berry',
      authorRu: 'Чак Берри',
      descriptionEn: '"You Never Can Tell", also known as "C\'est La Vie" or "Teenage Wedding", is a song written by Chuck Berry.<br><br>It was composed in the early 1960s while Berry was in federal prison for violating the Mann Act. Released in 1964 on the album St. Louis to Liverpool and the follow-up single to Berry\'s final Top Ten hit of the 1960s: "No Particular Place to Go", "You Never Can Tell" reached number 14, becoming Berry\'s final Top 40 hit until "My Ding-a-Ling", a number 1 in October 1972.<br><br>The song became popular again after the 1994 release of the film Pulp Fiction, directed and co-written by Quentin Tarantino. The music was played for a "Twist contest" in which Vincent Vega (John Travolta) and Mia Wallace (Uma Thurman) competed (and were the only contestants shown in the film). The music added an evocative element of sound to the narrative and Tarantino said that the song\'s lyrics of "Pierre" and "Mademoiselle" gave the scene a "uniquely \'50s French New Wave dance sequence feel".',
      descriptionRu: '«You Never Can Tell» — песня американского рок-музыканта Чака Берри, вышедшая на сингле в 1964 году.<br><br>Песня была написана в начале шестидесятых, в то время, когда Чак Берри находился в тюрьме. You Never Can Tell вошла в альбом Берри St. Louis to Liverpool 1964 года, изданный на лейбле Chess Records, как сингл она дошла до 14 места в рейтинге журнала Billboard.<br><br>Вторая волна популярности You Never Can Tell началась после выхода на экраны фильма культового американского режиссёра Квентина Тарантино «Криминальное чтиво» (1994), в саундтрек которого вошла песня. В одном из эпизодов фильма гангстер Винсент Вега (Джон Траволта) и жена его босса Миа Уоллес (Ума Турман) танцуют твист под песню Чака Берри. По словам Тарантино, лирика песни придаёт этой сцене особую атмосферу Французской новой волны.',
      image: 'url(../../assets/img/pulp-fiction.webp',
      audio: '../../assets/sound/pulp-fiction.mp3',
      duration: '00:26',
      wikiEn: 'https://en.wikipedia.org/wiki/You_Never_Can_Tell_(song)',
      wikiRu: 'https://ru.wikipedia.org/wiki/You_Never_Can_Tell',
      youtube: 'https://youtu.be/WSLMN6g_Od4'
    },{
      id: 5,
      nameEn: 'The Bodyguard',
      nameRu: 'Телохранитель',
      trackEn: 'I Will Always Love You',
      trackRu: 'Я всегда буду любить тебя',
      authorEn: 'Whitney Houston',
      authorRu: 'Уитни Хьюстон',
      descriptionEn: '"I Will Always Love You" is a song written and originally recorded in 1973 by American singer-songwriter Dolly Parton.<br><br>Whitney Houston recorded a soul-ballad arrangement of the song for the 1992 film The Bodyguard. Houston\'s version peaked at number one on the Billboard Hot 100 for a then-record-breaking 14 weeks. The single was certified Diamond by the RIAA, making Houston\'s first Diamond single, the third female artist who had both a Diamond single and a Diamond album, and becoming the best-selling single by a woman in the U.S.<br><br>The song was a global success, topping the charts in almost all countries. With 20 million copies sold it became the best-selling single of all time by a female solo artist.<br><br>Houston won the Grammy Award for Record of the Year in 1994 for "I Will Always Love You". The song has been recorded by many other artists including Linda Ronstadt, John Doe, Amber Riley, LeAnn Rimes and Sarah Washington, whose dance version reached number 12 on the UK Singles Chart.',
      descriptionRu: '«Я всегда буду любить тебя» — сингл американской кантри-певицы Долли Партон, выпущенный в 1974 году на лейбле RCA Records.<br><br>Однако с наибольшим успехом исполнила этот хит другая певица — Уитни Хьюстон. Её соул-версия, включённая в саундтрек к фильму «Телохранитель» 1992 года, была удостоена множества наград, в том числе «Грэмми» за лучшую запись года и лучший женский поп-вокал.<br><br>Критики были впечатлены тем, как грустная любовная песня благодаря мощному вокалу и влиянию госпела превратилась в неистовое воплощение драмы покинутой женщины.',
      image: 'url(../../assets/img/bodyguard.webp',
      audio: '../../assets/sound/bodyguard.mp3',
      duration: '00:47',
      wikiEn: 'https://en.wikipedia.org/wiki/I_Will_Always_Love_You',
      wikiRu: 'https://ru.wikipedia.org/wiki/I_Will_Always_Love_You',
      youtube: 'https://youtu.be/8u_T0ZEVD24'
    },
    {
      id: 6,
      nameEn: 'Requiem for a Dream',
      nameRu: 'Реквием по мечте',
      trackEn: 'Lux Aeterna',
      trackRu: 'Вечный свет',
      authorEn: 'Clint Mansell',
      authorRu: 'Клинт Мэнселл',
      descriptionEn: '"Lux Aeterna" is an orchestral composition by Clint Mansell. It forms a leitmotif in the 2000 film Requiem for a Dream, and is the penultimate piece in the movie\'s soundtrack.<br><br>The popularity of the piece led to its use in popular culture outside the film, in film and teaser trailers, such as Sunshine and Waking Madison, and multiple remixes and remakes by other producers.<br><br>It was also used in the 2010 season 2 premiere episode of NCIS: LA and a version of the track was re-orchestrated with a choir and full orchestra for The Lord of the Rings: The Two Towers trailer.<br><br>It was arranged by Simone Benyacar, Daniel Nielsen, and Veigar Margeirsson.<br><br>The orchestrated version was used in various trailers and video games. Clint Mansell commented that the piece had "gone on to have a life of its own".',
      descriptionRu: '«Вечный свет» — саундтрек к фильму Даррена Аронофски «Реквием по мечте» (экранизация романа Хьюберта Селби). Выпущен в 2000 году. Композитором является Клинт Мэнселл.<br><br>Эта музыка стала культовым хитом, так как саундтрек был оценён по достоинству многими музыкантами и получил широкое признание, а композиция «Lux Aeterna» и её реаранжированная версия «Requiem for a Tower» впоследствии были использованы в различных формах массовой информации (трейлеры и тизеры фильмов и сериалов, видеоигры, телепередачи, рекламные ролики и другие медиа).<br><br>Саундтрек Requiem for a Dream закрепил свою популярность после издания альбома Requiem for a Dream: Remixed, содержавшего новые ремиксы, созданные Полом Окенфолдом, Джошем Уинком, Джэгзом Кунером, Delerium и многими другими.',
      image: 'url(../../assets/img/requiem.webp',
      audio: '../../assets/sound/requiem.mp3',
      duration: '00:30',
      wikiEn: 'https://en.wikipedia.org/wiki/Lux_Aeterna_(Mansell)',
      wikiRu: 'https://ru.wikipedia.org/wiki/Requiem_for_a_Dream_(%D1%81%D0%B0%D1%83%D0%BD%D0%B4%D1%82%D1%80%D0%B5%D0%BA)',
      youtube: 'https://youtu.be/oc3Cq89P97Y'
    }
  ]
];

export default soundtracksData;